// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package store

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO account (id, email, password_hash, email_verified_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, email_verified_at, deleted_at, last_login_at, created_at, updated_at
`

type CreateAccountParams struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    *string
	EmailVerifiedAt *time.Time
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccountCredential = `-- name: CreateAccountCredential :one
INSERT INTO account_credential (id, account_id, kind, external_id, label)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, kind, external_id, label, data, last_used_at, created_at, updated_at
`

type CreateAccountCredentialParams struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	Kind       string
	ExternalID string
	Label      *string
}

func (q *Queries) CreateAccountCredential(ctx context.Context, arg CreateAccountCredentialParams) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, createAccountCredential,
		arg.ID,
		arg.AccountID,
		arg.Kind,
		arg.ExternalID,
		arg.Label,
	)
	var i AccountCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.ExternalID,
		&i.Label,
		&i.Data,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO account_session (id, account_id, token_hash, user_agent, ip, country, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, token_hash, user_agent, ip, country, expires_at, revoked_at, last_seen_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
	TokenHash []byte
	UserAgent *string
	Ip        *netip.Addr
	Country   *string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AccountSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.Country,
		arg.ExpiresAt,
	)
	var i AccountSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.Country,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM account_session
WHERE expires_at < now() - interval '30 days'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAccount = `-- name: GetAccount :one
SELECT id, email, password_hash, email_verified_at, deleted_at, last_login_at, created_at, updated_at
FROM account
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, password_hash, email_verified_at, deleted_at, last_login_at, created_at, updated_at
FROM account
WHERE lower(email) = lower($1::text) AND deleted_at IS NULL
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.DeletedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountCredential = `-- name: GetAccountCredential :one
SELECT id, account_id, kind, external_id, label, data, last_used_at, created_at, updated_at
FROM account_credential
WHERE kind = $1::text AND external_id = $2::text
`

type GetAccountCredentialParams struct {
	Kind       string
	ExternalID string
}

func (q *Queries) GetAccountCredential(ctx context.Context, arg GetAccountCredentialParams) (AccountCredential, error) {
	row := q.db.QueryRow(ctx, getAccountCredential, arg.Kind, arg.ExternalID)
	var i AccountCredential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Kind,
		&i.ExternalID,
		&i.Label,
		&i.Data,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, account_id, token_hash, user_agent, ip, country, expires_at, revoked_at, last_seen_at, created_at, updated_at
FROM account_session
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (AccountSession, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i AccountSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.Country,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsForAccount = `-- name: ListSessionsForAccount :many
SELECT id, account_id, token_hash, user_agent, ip, country, expires_at, revoked_at, last_seen_at, created_at, updated_at
FROM account_session
WHERE account_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY last_seen_at DESC
`

func (q *Queries) ListSessionsForAccount(ctx context.Context, accountID uuid.UUID) ([]AccountSession, error) {
	rows, err := q.db.Query(ctx, listSessionsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountSession{}
	for rows.Next() {
		var i AccountSession
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.UserAgent,
			&i.Ip,
			&i.Country,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccountLogin = `-- name: MarkAccountLogin :exec
UPDATE account SET last_login_at = now() WHERE id = $1
`

func (q *Queries) MarkAccountLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAccountLogin, id)
	return err
}

const revokeAllSessionsForAccount = `-- name: RevokeAllSessionsForAccount :exec
UPDATE account_session SET revoked_at = now()
WHERE account_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessionsForAccount(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsForAccount, accountID)
	return err
}

const revokeOtherSessionsForAccount = `-- name: RevokeOtherSessionsForAccount :execrows
UPDATE account_session SET revoked_at = now()
WHERE account_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeOtherSessionsForAccountParams struct {
	AccountID uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) RevokeOtherSessionsForAccount(ctx context.Context, arg RevokeOtherSessionsForAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOtherSessionsForAccount, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE account_session SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionForAccount = `-- name: RevokeSessionForAccount :execrows
UPDATE account_session SET revoked_at = now()
WHERE id = $1 AND account_id = $2 AND revoked_at IS NULL
`

type RevokeSessionForAccountParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

// Scoped to the owner so a foreign id answers like an invented one: not-found, never
// forbidden. Distinguishing those would let somebody confirm a colleague's session exists.
func (q *Queries) RevokeSessionForAccount(ctx context.Context, arg RevokeSessionForAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionForAccount, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSessionToken = `-- name: RotateSessionToken :one
UPDATE account_session
SET token_hash = $1,
    expires_at = $2,
    last_seen_at = now()
WHERE id = $3 AND revoked_at IS NULL
RETURNING id, account_id, token_hash, user_agent, ip, country, expires_at, revoked_at, last_seen_at, created_at, updated_at
`

type RotateSessionTokenParams struct {
	TokenHash []byte
	ExpiresAt time.Time
	ID        uuid.UUID
}

// RotateSessionToken swaps a session's refresh token without changing which session it is.
//
// Rotation used to be a revoke and an insert, which made a session a different row every
// fifteen minutes. That is what broke the Sessions screen: the id it drew a Revoke button
// for stopped existing the moment the device it named refreshed, so pressing Revoke on any
// live device answered "session not found" and left it signed in — the one flow the screen
// exists for. Updating in place keeps the id stable for the life of the login, which is what
// lets somebody point at a device and kill it.
//
// The security property is unchanged: the old token's digest is overwritten, so replaying it
// finds no row and is 401, exactly as revoking it was. created_at survives, so the "Signed
// in" column finally shows when the person actually signed in rather than when their browser
// last refreshed; user_agent, ip and country survive for the same reason.
func (q *Queries) RotateSessionToken(ctx context.Context, arg RotateSessionTokenParams) (AccountSession, error) {
	row := q.db.QueryRow(ctx, rotateSessionToken, arg.TokenHash, arg.ExpiresAt, arg.ID)
	var i AccountSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.Country,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAccountPassword = `-- name: SetAccountPassword :exec
UPDATE account SET password_hash = $1
WHERE id = $2
`

type SetAccountPasswordParams struct {
	PasswordHash *string
	ID           uuid.UUID
}

func (q *Queries) SetAccountPassword(ctx context.Context, arg SetAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, setAccountPassword, arg.PasswordHash, arg.ID)
	return err
}

const touchAccountCredential = `-- name: TouchAccountCredential :exec
UPDATE account_credential SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAccountCredential(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAccountCredential, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE account_session SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const verifyAccountEmail = `-- name: VerifyAccountEmail :exec
UPDATE account SET email_verified_at = now() WHERE id = $1 AND email_verified_at IS NULL
`

func (q *Queries) VerifyAccountEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyAccountEmail, id)
	return err
}
