// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const applyWorkspacePlan = `-- name: ApplyWorkspacePlan :one
UPDATE workspace
SET plan            = $1,
    seat_limit      = $2,
    plan_expires_at = $3,
    plan_lapsed_at  = CASE WHEN $4::boolean THEN NULL
                           ELSE plan_lapsed_at END
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, name, url_key, logo_url, settings, plan,
          archived_at, deleted_at, created_at, updated_at,
          plan_expires_at, seat_limit, plan_lapsed_at,
          project_update_reminder_interval_days, project_update_reminder_weekday,
          project_update_reminder_hour, pulse_enabled, pulse_digest_cadence,
          customer_requests_enabled, customer_default_team_id, customer_revenue_unit,
          customer_tiers
`

type ApplyWorkspacePlanParams struct {
	Plan          string
	SeatLimit     *int32
	PlanExpiresAt *time.Time
	ClearLapsed   bool
	ID            uuid.UUID
}

// ApplyWorkspacePlan is the one statement in the product that sets a workspace's plan.
//
// seat_limit and plan_expires_at are assigned outright rather than COALESCEd onto what is
// already there, because billing states the whole truth on every apply: a subscription that
// stops pinning seats has to be able to say so, and a COALESCE would make "no override" an
// unsayable value that leaves last quarter's deal in place forever.
//
// plan_lapsed_at is the exception, and only ever cleared here — never set. Clearing on a
// healthy subscription is what makes a recovered payment restore writes immediately instead
// of at the next tick of the lapse job; setting it is that job's business, because it is the
// only thing that knows how long past due the account has been.
func (q *Queries) ApplyWorkspacePlan(ctx context.Context, arg ApplyWorkspacePlanParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, applyWorkspacePlan,
		arg.Plan,
		arg.SeatLimit,
		arg.PlanExpiresAt,
		arg.ClearLapsed,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UrlKey,
		&i.LogoUrl,
		&i.Settings,
		&i.Plan,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanExpiresAt,
		&i.SeatLimit,
		&i.PlanLapsedAt,
		&i.ProjectUpdateReminderIntervalDays,
		&i.ProjectUpdateReminderWeekday,
		&i.ProjectUpdateReminderHour,
		&i.PulseEnabled,
		&i.PulseDigestCadence,
		&i.CustomerRequestsEnabled,
		&i.CustomerDefaultTeamID,
		&i.CustomerRevenueUnit,
		&i.CustomerTiers,
	)
	return i, err
}

const clearWorkspacePlanLapsed = `-- name: ClearWorkspacePlanLapsed :one
UPDATE workspace
SET plan_lapsed_at = NULL
WHERE id = $1
  AND deleted_at IS NULL
  AND plan_lapsed_at IS NOT NULL
RETURNING id, name, url_key, logo_url, settings, plan,
          archived_at, deleted_at, created_at, updated_at,
          plan_expires_at, seat_limit, plan_lapsed_at,
          project_update_reminder_interval_days, project_update_reminder_weekday,
          project_update_reminder_hour, pulse_enabled, pulse_digest_cadence,
          customer_requests_enabled, customer_default_team_id, customer_revenue_unit,
          customer_tiers
`

func (q *Queries) ClearWorkspacePlanLapsed(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, clearWorkspacePlanLapsed, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UrlKey,
		&i.LogoUrl,
		&i.Settings,
		&i.Plan,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanExpiresAt,
		&i.SeatLimit,
		&i.PlanLapsedAt,
		&i.ProjectUpdateReminderIntervalDays,
		&i.ProjectUpdateReminderWeekday,
		&i.ProjectUpdateReminderHour,
		&i.PulseEnabled,
		&i.PulseDigestCadence,
		&i.CustomerRequestsEnabled,
		&i.CustomerDefaultTeamID,
		&i.CustomerRevenueUnit,
		&i.CustomerTiers,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, workspace_id, provider, provider_customer_id, provider_subscription_id,
       status, current_period_end, seats_paid, created_at, updated_at
FROM subscription
WHERE workspace_id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, workspaceID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, workspaceID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.SeatsPaid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptionsPastDueBeyondGrace = `-- name: ListSubscriptionsPastDueBeyondGrace :many
SELECT s.workspace_id
FROM subscription s
JOIN workspace w ON w.id = s.workspace_id
WHERE w.deleted_at IS NULL
  AND w.plan_lapsed_at IS NULL
  AND w.plan NOT IN ('free', 'self_hosted')
  AND s.status = 'past_due'
  AND s.current_period_end IS NOT NULL
  AND s.current_period_end < $1::timestamptz
ORDER BY s.current_period_end
`

// ListSubscriptionsPastDueBeyondGrace names the workspaces whose plan should now be marked
// lapsed, and its predicate is the exact negation of the recovery query below — a workspace
// that satisfied both would flap between lapsed and not on every tick.
//
// `plan_lapsed_at IS NULL` keeps the sweep proportional: once a workspace is marked it
// stops appearing, so a long dunning cycle is not re-written every minute.
//
// free is excluded because a free plan cannot lapse (there is nothing to fail to pay) and
// self_hosted because a cloud billing row has no business narrowing an install somebody
// runs themselves — entitlement.New honours the flag on every plan but free, so a stray
// timestamp there would quietly put a self-hoster's writes under the free caps, which is
// the one symptom in this product nobody would think to trace to billing.
func (q *Queries) ListSubscriptionsPastDueBeyondGrace(ctx context.Context, cutoff time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsPastDueBeyondGrace, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var workspace_id uuid.UUID
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsRecoveredFromLapse = `-- name: ListSubscriptionsRecoveredFromLapse :many
SELECT s.workspace_id
FROM subscription s
JOIN workspace w ON w.id = s.workspace_id
WHERE w.deleted_at IS NULL
  AND w.plan_lapsed_at IS NOT NULL
  AND (
    s.status <> 'past_due'
    OR s.current_period_end IS NULL
    OR s.current_period_end >= $1::timestamptz
  )
ORDER BY s.workspace_id
`

// ListSubscriptionsRecoveredFromLapse names the workspaces whose lapse should be lifted.
//
// It requires a subscription row rather than clearing every lapsed workspace it can find.
// A workspace marked lapsed with no billing record is not something this job knows anything
// about — a support script, a migration, a hand-written deal — and "recovering" it would be
// this job silently granting a paid plan it has no evidence for.
func (q *Queries) ListSubscriptionsRecoveredFromLapse(ctx context.Context, cutoff time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsRecoveredFromLapse, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var workspace_id uuid.UUID
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWorkspacePlanLapsed = `-- name: MarkWorkspacePlanLapsed :one
UPDATE workspace
SET plan_lapsed_at = $1
WHERE id = $2
  AND deleted_at IS NULL
  AND plan_lapsed_at IS NULL
  AND plan NOT IN ('free', 'self_hosted')
RETURNING id, name, url_key, logo_url, settings, plan,
          archived_at, deleted_at, created_at, updated_at,
          plan_expires_at, seat_limit, plan_lapsed_at,
          project_update_reminder_interval_days, project_update_reminder_weekday,
          project_update_reminder_hour, pulse_enabled, pulse_digest_cadence,
          customer_requests_enabled, customer_default_team_id, customer_revenue_unit,
          customer_tiers
`

type MarkWorkspacePlanLapsedParams struct {
	LapsedAt *time.Time
	ID       uuid.UUID
}

// MarkWorkspacePlanLapsed and ClearWorkspacePlanLapsed both restate the condition the
// listing query already checked. That is what makes the job idempotent under concurrency:
// two workers sweeping at once, or one sweeping while a webhook applies a recovery, and the
// loser writes nothing and gets pgx.ErrNoRows rather than overwriting the winner's answer
// with a stale one. It also keeps the lapse timestamp honest — it records the first sweep
// that found the workspace past grace, not the most recent one, so "lapsed since" does not
// reset itself every hour.
func (q *Queries) MarkWorkspacePlanLapsed(ctx context.Context, arg MarkWorkspacePlanLapsedParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, markWorkspacePlanLapsed, arg.LapsedAt, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UrlKey,
		&i.LogoUrl,
		&i.Settings,
		&i.Plan,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanExpiresAt,
		&i.SeatLimit,
		&i.PlanLapsedAt,
		&i.ProjectUpdateReminderIntervalDays,
		&i.ProjectUpdateReminderWeekday,
		&i.ProjectUpdateReminderHour,
		&i.PulseEnabled,
		&i.PulseDigestCadence,
		&i.CustomerRequestsEnabled,
		&i.CustomerDefaultTeamID,
		&i.CustomerRevenueUnit,
		&i.CustomerTiers,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :one

INSERT INTO subscription (
  id, workspace_id, provider, provider_customer_id, provider_subscription_id,
  status, current_period_end, seats_paid
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8
)
ON CONFLICT (workspace_id) DO UPDATE
SET provider                 = EXCLUDED.provider,
    provider_customer_id     = EXCLUDED.provider_customer_id,
    provider_subscription_id = EXCLUDED.provider_subscription_id,
    status                   = EXCLUDED.status,
    current_period_end       = EXCLUDED.current_period_end,
    seats_paid               = EXCLUDED.seats_paid
RETURNING id, workspace_id, provider, provider_customer_id, provider_subscription_id,
          status, current_period_end, seats_paid, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	ID                     uuid.UUID
	WorkspaceID            uuid.UUID
	Provider               string
	ProviderCustomerID     string
	ProviderSubscriptionID *string
	Status                 string
	CurrentPeriodEnd       *time.Time
	SeatsPaid              *int32
}

// Billing. Every statement that writes a workspace's plan facts lives in this file, and
// that is not tidiness — `workspace.plan`, `seat_limit`, `plan_expires_at` and
// `plan_lapsed_at` are the four columns the entire entitlement matrix resolves against, and
// the product's rule is that a *request* can never set them. Keeping the writers in one
// place is what makes "is there a second writer" a question somebody can answer by looking.
//
// UpdateWorkspace (workspaces.sql) touches none of them, on purpose. See internal/domain/
// billing.go for the only production callers of anything below.
// Keyed on the workspace rather than on the provider's id, because a webhook replay and a
// reconciliation sweep must both land on the row that is already there. The id column is
// left alone on conflict: it is this row's identity, and churning it would break any future
// reference to it.
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.ID,
		arg.WorkspaceID,
		arg.Provider,
		arg.ProviderCustomerID,
		arg.ProviderSubscriptionID,
		arg.Status,
		arg.CurrentPeriodEnd,
		arg.SeatsPaid,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.SeatsPaid,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
