// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_log.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendChange = `-- name: AppendChange :exec
INSERT INTO change_log (workspace_id, version, entity_type, entity_id, op,
                        team_id, scope, actor_type, actor_id, payload,
                        changed_fields, batch_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11::text[], $12)
`

type AppendChangeParams struct {
	WorkspaceID   uuid.UUID
	Version       int64
	EntityType    string
	EntityID      uuid.UUID
	Op            string
	TeamID        *uuid.UUID
	Scope         json.RawMessage
	ActorType     string
	ActorID       *uuid.UUID
	Payload       []byte
	ChangedFields []string
	BatchKey      *string
}

func (q *Queries) AppendChange(ctx context.Context, arg AppendChangeParams) error {
	_, err := q.db.Exec(ctx, appendChange,
		arg.WorkspaceID,
		arg.Version,
		arg.EntityType,
		arg.EntityID,
		arg.Op,
		arg.TeamID,
		arg.Scope,
		arg.ActorType,
		arg.ActorID,
		arg.Payload,
		arg.ChangedFields,
		arg.BatchKey,
	)
	return err
}

const ensureChangeLogPartition = `-- name: EnsureChangeLogPartition :exec
SELECT create_change_log_partition($1::date)
`

func (q *Queries) EnsureChangeLogPartition(ctx context.Context, month pgtype.Date) error {
	_, err := q.db.Exec(ctx, ensureChangeLogPartition, month)
	return err
}

const oldestRetainedVersion = `-- name: OldestRetainedVersion :one
SELECT coalesce(min(version), 0)::bigint FROM change_log WHERE workspace_id = $1
`

// OldestRetainedVersion tells a resuming client whether its position still exists. If
// the client's version is below this, its deltas have been pruned and it must
// re-bootstrap rather than silently miss changes.
func (q *Queries) OldestRetainedVersion(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, oldestRetainedVersion, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneChangeLogBefore = `-- name: PruneChangeLogBefore :execrows
DELETE FROM change_log WHERE created_at < $1
`

func (q *Queries) PruneChangeLogBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneChangeLogBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const readChangesSince = `-- name: ReadChangesSince :many
SELECT workspace_id, version, entity_type, entity_id, op, team_id, scope,
       actor_type, actor_id, payload, created_at, changed_fields, batch_key
FROM change_log
WHERE workspace_id = $1
  AND version > $2
  AND version <= $3
ORDER BY version
LIMIT $4
`

type ReadChangesSinceParams struct {
	WorkspaceID    uuid.UUID
	AfterVersion   int64
	ThroughVersion int64
	PageSize       int32
}

// ReadChangesSince is the sync hub's only read path, and the notification engine's. The
// predicate maps exactly onto change_log_workspace_version_idx, and the LIMIT is what makes
// the "gap too large -> resync" branch decidable: if the caller gets a full page it asks
// again, and if the backlog exceeds the session's budget it sends {resync} instead of
// streaming forever.
//
// changed_fields and batch_key are selected even though the hub ignores them, because one
// read path is the point: a second query shaped for the fan-out would be a second answer to
// "what happened since V", and the two would drift on the day somebody fixes only one.
func (q *Queries) ReadChangesSince(ctx context.Context, arg ReadChangesSinceParams) ([]ChangeLog, error) {
	rows, err := q.db.Query(ctx, readChangesSince,
		arg.WorkspaceID,
		arg.AfterVersion,
		arg.ThroughVersion,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeLog{}
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Version,
			&i.EntityType,
			&i.EntityID,
			&i.Op,
			&i.TeamID,
			&i.Scope,
			&i.ActorType,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
			&i.ChangedFields,
			&i.BatchKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
