// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cycles.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeCycle = `-- name: CompleteCycle :one
UPDATE cycle SET completed_at = $1
WHERE id = $2 AND completed_at IS NULL
RETURNING id, workspace_id, team_id, number, name, description, starts_at, ends_at,
          completed_at, archived_at, created_at, updated_at
`

type CompleteCycleParams struct {
	CompletedAt *time.Time
	ID          uuid.UUID
}

func (q *Queries) CompleteCycle(ctx context.Context, arg CompleteCycleParams) (Cycle, error) {
	row := q.db.QueryRow(ctx, completeCycle, arg.CompletedAt, arg.ID)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCycle = `-- name: CreateCycle :one

INSERT INTO cycle (id, workspace_id, team_id, number, name, description, starts_at, ends_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
RETURNING id, workspace_id, team_id, number, name, description, starts_at, ends_at,
          completed_at, archived_at, created_at, updated_at
`

type CreateCycleParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
	Number      int32
	Name        string
	Description *string
	StartsAt    time.Time
	EndsAt      time.Time
}

// Cycles. Column lists follow the table order, same rule as issues.sql.
func (q *Queries) CreateCycle(ctx context.Context, arg CreateCycleParams) (Cycle, error) {
	row := q.db.QueryRow(ctx, createCycle,
		arg.ID,
		arg.WorkspaceID,
		arg.TeamID,
		arg.Number,
		arg.Name,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUpcomingCycles = `-- name: DeleteUpcomingCycles :many
DELETE FROM cycle
WHERE team_id = $1
  AND starts_at > $2
  AND completed_at IS NULL
RETURNING id
`

type DeleteUpcomingCyclesParams struct {
	TeamID uuid.UUID
	Now    time.Time
}

// Upcoming cycles that have not started: dropped when the team turns cycles off.
func (q *Queries) DeleteUpcomingCycles(ctx context.Context, arg DeleteUpcomingCyclesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteUpcomingCycles, arg.TeamID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCycle = `-- name: GetCycle :one
SELECT id, workspace_id, team_id, number, name, description, starts_at, ends_at,
       completed_at, archived_at, created_at, updated_at
FROM cycle
WHERE id = $1
`

func (q *Queries) GetCycle(ctx context.Context, id uuid.UUID) (Cycle, error) {
	row := q.db.QueryRow(ctx, getCycle, id)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastCycleNumber = `-- name: LastCycleNumber :one
SELECT number FROM cycle
WHERE team_id = $1
ORDER BY number DESC
LIMIT 1
`

func (q *Queries) LastCycleNumber(ctx context.Context, teamID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, lastCycleNumber, teamID)
	var number int32
	err := row.Scan(&number)
	return number, err
}

const listCyclelessIssuesByCategory = `-- name: ListCyclelessIssuesByCategory :many
SELECT i.id, i.workspace_id, i.team_id, i.number, i.title, i.description, i.state_id,
       i.assignee_id, i.creator_id, i.priority, i.sort_order,
       i.started_at, i.completed_at, i.canceled_at,
       i.archived_at, i.deleted_at, i.created_at, i.updated_at,
       i.estimate, i.due_date, i.due_date_source, i.parent_id, i.sub_issue_sort_order,
       i.template_id, i.deleted_by, i.project_id, i.project_milestone_id, i.cycle_id
FROM issue i
JOIN workflow_state s ON s.id = i.state_id
WHERE i.team_id = $1
  AND i.cycle_id IS NULL
  AND i.archived_at IS NULL AND i.deleted_at IS NULL
  AND s.category = $2
`

type ListCyclelessIssuesByCategoryParams struct {
	TeamID   uuid.UUID
	Category string
}

// Cycle-less issues in a given category, for auto-add.
func (q *Queries) ListCyclelessIssuesByCategory(ctx context.Context, arg ListCyclelessIssuesByCategoryParams) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listCyclelessIssuesByCategory, arg.TeamID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCyclesForTeam = `-- name: ListCyclesForTeam :many
SELECT id, workspace_id, team_id, number, name, description, starts_at, ends_at,
       completed_at, archived_at, created_at, updated_at
FROM cycle
WHERE team_id = $1 AND archived_at IS NULL
ORDER BY starts_at
`

func (q *Queries) ListCyclesForTeam(ctx context.Context, teamID uuid.UUID) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, listCyclesForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIssuesInCycle = `-- name: ListOpenIssuesInCycle :many
SELECT i.id, i.workspace_id, i.team_id, i.number, i.title, i.description, i.state_id,
       i.assignee_id, i.creator_id, i.priority, i.sort_order,
       i.started_at, i.completed_at, i.canceled_at,
       i.archived_at, i.deleted_at, i.created_at, i.updated_at,
       i.estimate, i.due_date, i.due_date_source, i.parent_id, i.sub_issue_sort_order,
       i.template_id, i.deleted_by, i.project_id, i.project_milestone_id, i.cycle_id
FROM issue i
JOIN workflow_state s ON s.id = i.state_id
WHERE i.cycle_id = $1
  AND i.archived_at IS NULL AND i.deleted_at IS NULL
  AND s.category IN ('unstarted', 'started')
`

// Open work in a closing cycle: unstarted and started, not backlog/triage/canceled/completed.
func (q *Queries) ListOpenIssuesInCycle(ctx context.Context, cycleID *uuid.UUID) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listOpenIssuesInCycle, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIssueCycle = `-- name: SetIssueCycle :exec
UPDATE issue SET cycle_id = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SetIssueCycleParams struct {
	CycleID *uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) SetIssueCycle(ctx context.Context, arg SetIssueCycleParams) error {
	_, err := q.db.Exec(ctx, setIssueCycle, arg.CycleID, arg.ID)
	return err
}

const streamCyclesForBootstrap = `-- name: StreamCyclesForBootstrap :many
SELECT id, workspace_id, team_id, number, name, description, starts_at, ends_at,
       completed_at, archived_at, created_at, updated_at
FROM cycle
WHERE workspace_id = $1
  AND team_id = ANY($2::uuid[])
  AND archived_at IS NULL
  AND id > $3
ORDER BY id
LIMIT $4
`

type StreamCyclesForBootstrapParams struct {
	WorkspaceID uuid.UUID
	TeamIds     []uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

func (q *Queries) StreamCyclesForBootstrap(ctx context.Context, arg StreamCyclesForBootstrapParams) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, streamCyclesForBootstrap,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
