// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cycles.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCycle = `-- name: ArchiveCycle :exec
UPDATE cycle SET archived_at = now() WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveCycle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveCycle, id)
	return err
}

const completeCycle = `-- name: CompleteCycle :one
UPDATE cycle SET completed_at = $1
WHERE id = $2 AND completed_at IS NULL
RETURNING id, workspace_id, team_id, number, name, description, starts_at, ends_at,
          completed_at, archived_at, created_at, updated_at
`

type CompleteCycleParams struct {
	CompletedAt *time.Time
	ID          uuid.UUID
}

func (q *Queries) CompleteCycle(ctx context.Context, arg CompleteCycleParams) (Cycle, error) {
	row := q.db.QueryRow(ctx, completeCycle, arg.CompletedAt, arg.ID)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCycle = `-- name: CreateCycle :one

INSERT INTO cycle (id, workspace_id, team_id, number, name, description, starts_at, ends_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
RETURNING id, workspace_id, team_id, number, name, description, starts_at, ends_at,
          completed_at, archived_at, created_at, updated_at
`

type CreateCycleParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
	Number      int32
	Name        string
	Description *string
	StartsAt    time.Time
	EndsAt      time.Time
}

// Cycles. Column lists follow the table order, same rule as issues.sql.
func (q *Queries) CreateCycle(ctx context.Context, arg CreateCycleParams) (Cycle, error) {
	row := q.db.QueryRow(ctx, createCycle,
		arg.ID,
		arg.WorkspaceID,
		arg.TeamID,
		arg.Number,
		arg.Name,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCycle = `-- name: DeleteCycle :one
DELETE FROM cycle WHERE id = $1
RETURNING id
`

// A single window, used when a sub-team remaps upcoming cycles onto a parent schedule.
// Issues on the row SET NULL via the FK; callers re-point open work first.
func (q *Queries) DeleteCycle(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCycle, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const deleteUpcomingCycles = `-- name: DeleteUpcomingCycles :many
DELETE FROM cycle
WHERE team_id = $1
  AND starts_at > $2
  AND completed_at IS NULL
RETURNING id
`

type DeleteUpcomingCyclesParams struct {
	TeamID uuid.UUID
	Now    time.Time
}

// Upcoming cycles that have not started: dropped when the team turns cycles off.
func (q *Queries) DeleteUpcomingCycles(ctx context.Context, arg DeleteUpcomingCyclesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteUpcomingCycles, arg.TeamID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCycle = `-- name: GetCycle :one
SELECT id, workspace_id, team_id, number, name, description, starts_at, ends_at,
       completed_at, archived_at, created_at, updated_at
FROM cycle
WHERE id = $1
`

func (q *Queries) GetCycle(ctx context.Context, id uuid.UUID) (Cycle, error) {
	row := q.db.QueryRow(ctx, getCycle, id)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastCycleNumber = `-- name: LastCycleNumber :one
SELECT number FROM cycle
WHERE team_id = $1
ORDER BY number DESC
LIMIT 1
`

func (q *Queries) LastCycleNumber(ctx context.Context, teamID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, lastCycleNumber, teamID)
	var number int32
	err := row.Scan(&number)
	return number, err
}

const listArchivedCyclesForTeam = `-- name: ListArchivedCyclesForTeam :many
SELECT id, workspace_id, team_id, number, name, description, starts_at, ends_at,
       completed_at, archived_at, created_at, updated_at
FROM cycle
WHERE team_id = $1 AND archived_at IS NOT NULL
ORDER BY archived_at DESC
`

func (q *Queries) ListArchivedCyclesForTeam(ctx context.Context, teamID uuid.UUID) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, listArchivedCyclesForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCyclelessIssuesByCategory = `-- name: ListCyclelessIssuesByCategory :many
SELECT i.id, i.workspace_id, i.team_id, i.number, i.title, i.description, i.state_id,
       i.assignee_id, i.creator_id, i.priority, i.sort_order,
       i.started_at, i.completed_at, i.canceled_at,
       i.archived_at, i.deleted_at, i.created_at, i.updated_at,
       i.estimate, i.due_date, i.due_date_source, i.parent_id, i.sub_issue_sort_order,
       i.template_id, i.form_template_id, i.deleted_by, i.project_id, i.project_milestone_id, i.cycle_id, i.snoozed_until, i.auto_closed_at, i.recurring_issue_id
FROM issue i
JOIN workflow_state s ON s.id = i.state_id
WHERE i.team_id = $1
  AND i.cycle_id IS NULL
  AND i.archived_at IS NULL AND i.deleted_at IS NULL
  AND s.category = $2
`

type ListCyclelessIssuesByCategoryParams struct {
	TeamID   uuid.UUID
	Category string
}

type ListCyclelessIssuesByCategoryRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
	RecurringIssueID   *uuid.UUID
}

// Cycle-less issues in a given category, for auto-add.
func (q *Queries) ListCyclelessIssuesByCategory(ctx context.Context, arg ListCyclelessIssuesByCategoryParams) ([]ListCyclelessIssuesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listCyclelessIssuesByCategory, arg.TeamID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCyclelessIssuesByCategoryRow{}
	for rows.Next() {
		var i ListCyclelessIssuesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
			&i.RecurringIssueID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCyclesForTeam = `-- name: ListCyclesForTeam :many
SELECT id, workspace_id, team_id, number, name, description, starts_at, ends_at,
       completed_at, archived_at, created_at, updated_at
FROM cycle
WHERE team_id = $1 AND archived_at IS NULL
ORDER BY starts_at
`

func (q *Queries) ListCyclesForTeam(ctx context.Context, teamID uuid.UUID) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, listCyclesForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIssuesInCycle = `-- name: ListOpenIssuesInCycle :many
SELECT i.id, i.workspace_id, i.team_id, i.number, i.title, i.description, i.state_id,
       i.assignee_id, i.creator_id, i.priority, i.sort_order,
       i.started_at, i.completed_at, i.canceled_at,
       i.archived_at, i.deleted_at, i.created_at, i.updated_at,
       i.estimate, i.due_date, i.due_date_source, i.parent_id, i.sub_issue_sort_order,
       i.template_id, i.form_template_id, i.deleted_by, i.project_id, i.project_milestone_id, i.cycle_id, i.snoozed_until, i.auto_closed_at, i.recurring_issue_id
FROM issue i
JOIN workflow_state s ON s.id = i.state_id
WHERE i.cycle_id = $1
  AND i.archived_at IS NULL AND i.deleted_at IS NULL
  AND s.category IN ('unstarted', 'started')
`

type ListOpenIssuesInCycleRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
	RecurringIssueID   *uuid.UUID
}

// Open work in a closing cycle: unstarted and started, not backlog/triage/canceled/completed.
func (q *Queries) ListOpenIssuesInCycle(ctx context.Context, cycleID *uuid.UUID) ([]ListOpenIssuesInCycleRow, error) {
	rows, err := q.db.Query(ctx, listOpenIssuesInCycle, cycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenIssuesInCycleRow{}
	for rows.Next() {
		var i ListOpenIssuesInCycleRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
			&i.RecurringIssueID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleCompletedCycles = `-- name: ListStaleCompletedCycles :many
SELECT id, workspace_id, team_id, number, name, description, starts_at, ends_at,
       completed_at, archived_at, created_at, updated_at
FROM cycle
WHERE team_id = $1
  AND archived_at IS NULL
  AND completed_at IS NOT NULL
  AND completed_at < $2
ORDER BY completed_at, id
`

type ListStaleCompletedCyclesParams struct {
	TeamID uuid.UUID
	Cutoff *time.Time
}

// Completed cycles past the team's archive period. A cycle that was never completed
// is still the current or upcoming window and must not disappear under people's feet.
func (q *Queries) ListStaleCompletedCycles(ctx context.Context, arg ListStaleCompletedCyclesParams) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, listStaleCompletedCycles, arg.TeamID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIssueCycle = `-- name: SetIssueCycle :exec
UPDATE issue SET cycle_id = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SetIssueCycleParams struct {
	CycleID *uuid.UUID
	ID      uuid.UUID
}

func (q *Queries) SetIssueCycle(ctx context.Context, arg SetIssueCycleParams) error {
	_, err := q.db.Exec(ctx, setIssueCycle, arg.CycleID, arg.ID)
	return err
}

const streamCyclesForBootstrap = `-- name: StreamCyclesForBootstrap :many
SELECT id, workspace_id, team_id, number, name, description, starts_at, ends_at,
       completed_at, archived_at, created_at, updated_at
FROM cycle
WHERE workspace_id = $1
  AND team_id = ANY($2::uuid[])
  AND archived_at IS NULL
  AND id > $3
ORDER BY id
LIMIT $4
`

type StreamCyclesForBootstrapParams struct {
	WorkspaceID uuid.UUID
	TeamIds     []uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

func (q *Queries) StreamCyclesForBootstrap(ctx context.Context, arg StreamCyclesForBootstrapParams) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, streamCyclesForBootstrap,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveCycle = `-- name: UnarchiveCycle :one
UPDATE cycle SET archived_at = NULL WHERE id = $1
RETURNING id, workspace_id, team_id, number, name, description, starts_at, ends_at,
          completed_at, archived_at, created_at, updated_at
`

func (q *Queries) UnarchiveCycle(ctx context.Context, id uuid.UUID) (Cycle, error) {
	row := q.db.QueryRow(ctx, unarchiveCycle, id)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCycle = `-- name: UpdateCycle :one
UPDATE cycle SET
  name = COALESCE($1, name),
  description = CASE
    WHEN $2::boolean THEN $3
    ELSE description
  END,
  starts_at = COALESCE($4, starts_at),
  ends_at = COALESCE($5, ends_at)
WHERE id = $6 AND archived_at IS NULL
RETURNING id, workspace_id, team_id, number, name, description, starts_at, ends_at,
          completed_at, archived_at, created_at, updated_at
`

type UpdateCycleParams struct {
	Name             *string
	TouchDescription *bool
	Description      *string
	StartsAt         *time.Time
	EndsAt           *time.Time
	ID               uuid.UUID
}

func (q *Queries) UpdateCycle(ctx context.Context, arg UpdateCycleParams) (Cycle, error) {
	row := q.db.QueryRow(ctx, updateCycle,
		arg.Name,
		arg.TouchDescription,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
	)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
