// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drafts.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createDraft = `-- name: CreateDraft :one

INSERT INTO draft (id, workspace_id, user_id, kind, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, user_id, kind, payload, created_at, updated_at
`

type CreateDraftParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Kind        string
	Payload     json.RawMessage
}

// Drafts are not replicated. Every query is scoped to one user in one workspace: a listing
// that omitted user_id would be a way to read somebody else's unsent work.
func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Kind,
		arg.Payload,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraft = `-- name: DeleteDraft :one
DELETE FROM draft
WHERE id = $1
  AND workspace_id = $2
  AND user_id = $3
RETURNING id
`

type DeleteDraftParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteDraft(ctx context.Context, arg DeleteDraftParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteDraft, arg.ID, arg.WorkspaceID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDraft = `-- name: GetDraft :one
SELECT id, workspace_id, user_id, kind, payload, created_at, updated_at
FROM draft
WHERE id = $1
  AND workspace_id = $2
  AND user_id = $3
`

type GetDraftParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) GetDraft(ctx context.Context, arg GetDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, getDraft, arg.ID, arg.WorkspaceID, arg.UserID)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDraftsForUser = `-- name: ListDraftsForUser :many
SELECT id, workspace_id, user_id, kind, payload, created_at, updated_at
FROM draft
WHERE workspace_id = $1
  AND user_id = $2
  AND updated_at >= $3
ORDER BY updated_at DESC
`

type ListDraftsForUserParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Since       time.Time
}

func (q *Queries) ListDraftsForUser(ctx context.Context, arg ListDraftsForUserParams) ([]Draft, error) {
	rows, err := q.db.Query(ctx, listDraftsForUser, arg.WorkspaceID, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Draft{}
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneDrafts = `-- name: PruneDrafts :execrows
DELETE FROM draft
WHERE updated_at < $1
`

func (q *Queries) PruneDrafts(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneDrafts, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDraftPayload = `-- name: UpdateDraftPayload :one
UPDATE draft
SET payload = $1
WHERE id = $2
  AND workspace_id = $3
  AND user_id = $4
RETURNING id, workspace_id, user_id, kind, payload, created_at, updated_at
`

type UpdateDraftPayloadParams struct {
	Payload     json.RawMessage
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateDraftPayload(ctx context.Context, arg UpdateDraftPayloadParams) (Draft, error) {
	row := q.db.QueryRow(ctx, updateDraftPayload,
		arg.Payload,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Kind,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
