// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gitlab.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createGitLabConnection = `-- name: CreateGitLabConnection :one

INSERT INTO gitlab_connection (
  id, workspace_id, creator_id, enabled, instance_url,
  branch_name_format, link_commits, linkbacks, webhook_secret, access_token, connected_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, workspace_id, creator_id, enabled, instance_url,
          branch_name_format, link_commits, linkbacks, connected_at, created_at, updated_at
`

type CreateGitLabConnectionParams struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CreatorID        uuid.UUID
	Enabled          bool
	InstanceUrl      string
	BranchNameFormat string
	LinkCommits      bool
	Linkbacks        bool
	WebhookSecret    string
	AccessToken      *string
	ConnectedAt      *time.Time
}

type CreateGitLabConnectionRow struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CreatorID        uuid.UUID
	Enabled          bool
	InstanceUrl      string
	BranchNameFormat string
	LinkCommits      bool
	Linkbacks        bool
	ConnectedAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// Replicated columns only. access_token and webhook_secret are never selected here.
func (q *Queries) CreateGitLabConnection(ctx context.Context, arg CreateGitLabConnectionParams) (CreateGitLabConnectionRow, error) {
	row := q.db.QueryRow(ctx, createGitLabConnection,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatorID,
		arg.Enabled,
		arg.InstanceUrl,
		arg.BranchNameFormat,
		arg.LinkCommits,
		arg.Linkbacks,
		arg.WebhookSecret,
		arg.AccessToken,
		arg.ConnectedAt,
	)
	var i CreateGitLabConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Enabled,
		&i.InstanceUrl,
		&i.BranchNameFormat,
		&i.LinkCommits,
		&i.Linkbacks,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGitLabUserLink = `-- name: CreateGitLabUserLink :one
INSERT INTO gitlab_user_link (
  id, workspace_id, user_id, gitlab_username, gitlab_user_id
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, workspace_id, user_id, gitlab_username, gitlab_user_id, created_at, updated_at
`

type CreateGitLabUserLinkParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	UserID         uuid.UUID
	GitlabUsername string
	GitlabUserID   *int64
}

func (q *Queries) CreateGitLabUserLink(ctx context.Context, arg CreateGitLabUserLinkParams) (GitlabUserLink, error) {
	row := q.db.QueryRow(ctx, createGitLabUserLink,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.GitlabUsername,
		arg.GitlabUserID,
	)
	var i GitlabUserLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.GitlabUsername,
		&i.GitlabUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGitLabConnection = `-- name: DeleteGitLabConnection :exec
DELETE FROM gitlab_connection WHERE workspace_id = $1
`

func (q *Queries) DeleteGitLabConnection(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGitLabConnection, workspaceID)
	return err
}

const deleteGitLabUserLink = `-- name: DeleteGitLabUserLink :exec
DELETE FROM gitlab_user_link
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteGitLabUserLinkParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteGitLabUserLink(ctx context.Context, arg DeleteGitLabUserLinkParams) error {
	_, err := q.db.Exec(ctx, deleteGitLabUserLink, arg.WorkspaceID, arg.UserID)
	return err
}

const getGitLabConnection = `-- name: GetGitLabConnection :one
SELECT id, workspace_id, creator_id, enabled, instance_url,
       branch_name_format, link_commits, linkbacks, connected_at, created_at, updated_at
FROM gitlab_connection
WHERE workspace_id = $1
`

type GetGitLabConnectionRow struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CreatorID        uuid.UUID
	Enabled          bool
	InstanceUrl      string
	BranchNameFormat string
	LinkCommits      bool
	Linkbacks        bool
	ConnectedAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetGitLabConnection(ctx context.Context, workspaceID uuid.UUID) (GetGitLabConnectionRow, error) {
	row := q.db.QueryRow(ctx, getGitLabConnection, workspaceID)
	var i GetGitLabConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Enabled,
		&i.InstanceUrl,
		&i.BranchNameFormat,
		&i.LinkCommits,
		&i.Linkbacks,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGitLabConnectionAccessToken = `-- name: GetGitLabConnectionAccessToken :one
SELECT COALESCE(access_token, '')::text AS access_token
FROM gitlab_connection
WHERE workspace_id = $1
`

func (q *Queries) GetGitLabConnectionAccessToken(ctx context.Context, workspaceID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getGitLabConnectionAccessToken, workspaceID)
	var access_token string
	err := row.Scan(&access_token)
	return access_token, err
}

const getGitLabConnectionSecret = `-- name: GetGitLabConnectionSecret :one
SELECT webhook_secret
FROM gitlab_connection
WHERE workspace_id = $1
`

func (q *Queries) GetGitLabConnectionSecret(ctx context.Context, workspaceID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getGitLabConnectionSecret, workspaceID)
	var webhook_secret string
	err := row.Scan(&webhook_secret)
	return webhook_secret, err
}

const getGitLabUserLink = `-- name: GetGitLabUserLink :one
SELECT id, workspace_id, user_id, gitlab_username, gitlab_user_id, created_at, updated_at
FROM gitlab_user_link
WHERE workspace_id = $1 AND user_id = $2
`

type GetGitLabUserLinkParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) GetGitLabUserLink(ctx context.Context, arg GetGitLabUserLinkParams) (GitlabUserLink, error) {
	row := q.db.QueryRow(ctx, getGitLabUserLink, arg.WorkspaceID, arg.UserID)
	var i GitlabUserLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.GitlabUsername,
		&i.GitlabUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setGitLabConnectionAccessToken = `-- name: SetGitLabConnectionAccessToken :exec
UPDATE gitlab_connection
SET access_token = $1, connected_at = now()
WHERE workspace_id = $2
`

type SetGitLabConnectionAccessTokenParams struct {
	AccessToken *string
	WorkspaceID uuid.UUID
}

func (q *Queries) SetGitLabConnectionAccessToken(ctx context.Context, arg SetGitLabConnectionAccessTokenParams) error {
	_, err := q.db.Exec(ctx, setGitLabConnectionAccessToken, arg.AccessToken, arg.WorkspaceID)
	return err
}

const streamGitLabConnectionsForBootstrap = `-- name: StreamGitLabConnectionsForBootstrap :many
SELECT id, workspace_id, creator_id, enabled, instance_url,
       branch_name_format, link_commits, linkbacks, connected_at, created_at, updated_at
FROM gitlab_connection
WHERE workspace_id = $1
  AND id > $2
ORDER BY id
LIMIT $3
`

type StreamGitLabConnectionsForBootstrapParams struct {
	WorkspaceID uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

type StreamGitLabConnectionsForBootstrapRow struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CreatorID        uuid.UUID
	Enabled          bool
	InstanceUrl      string
	BranchNameFormat string
	LinkCommits      bool
	Linkbacks        bool
	ConnectedAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) StreamGitLabConnectionsForBootstrap(ctx context.Context, arg StreamGitLabConnectionsForBootstrapParams) ([]StreamGitLabConnectionsForBootstrapRow, error) {
	rows, err := q.db.Query(ctx, streamGitLabConnectionsForBootstrap, arg.WorkspaceID, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreamGitLabConnectionsForBootstrapRow{}
	for rows.Next() {
		var i StreamGitLabConnectionsForBootstrapRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatorID,
			&i.Enabled,
			&i.InstanceUrl,
			&i.BranchNameFormat,
			&i.LinkCommits,
			&i.Linkbacks,
			&i.ConnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamGitLabUserLinksForBootstrap = `-- name: StreamGitLabUserLinksForBootstrap :many
SELECT id, workspace_id, user_id, gitlab_username, gitlab_user_id, created_at, updated_at
FROM gitlab_user_link
WHERE workspace_id = $1
  AND user_id = $2
  AND id > $3
ORDER BY id
LIMIT $4
`

type StreamGitLabUserLinksForBootstrapParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

func (q *Queries) StreamGitLabUserLinksForBootstrap(ctx context.Context, arg StreamGitLabUserLinksForBootstrapParams) ([]GitlabUserLink, error) {
	rows, err := q.db.Query(ctx, streamGitLabUserLinksForBootstrap,
		arg.WorkspaceID,
		arg.UserID,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GitlabUserLink{}
	for rows.Next() {
		var i GitlabUserLink
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.GitlabUsername,
			&i.GitlabUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGitLabConnection = `-- name: UpdateGitLabConnection :one
UPDATE gitlab_connection
SET instance_url = COALESCE($1, instance_url),
    branch_name_format = COALESCE($2, branch_name_format),
    link_commits = COALESCE($3, link_commits),
    linkbacks = COALESCE($4, linkbacks),
    enabled = COALESCE($5, enabled),
    connected_at = COALESCE($6, connected_at)
WHERE workspace_id = $7
RETURNING id, workspace_id, creator_id, enabled, instance_url,
          branch_name_format, link_commits, linkbacks, connected_at, created_at, updated_at
`

type UpdateGitLabConnectionParams struct {
	InstanceUrl      *string
	BranchNameFormat *string
	LinkCommits      *bool
	Linkbacks        *bool
	Enabled          *bool
	ConnectedAt      *time.Time
	WorkspaceID      uuid.UUID
}

type UpdateGitLabConnectionRow struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CreatorID        uuid.UUID
	Enabled          bool
	InstanceUrl      string
	BranchNameFormat string
	LinkCommits      bool
	Linkbacks        bool
	ConnectedAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) UpdateGitLabConnection(ctx context.Context, arg UpdateGitLabConnectionParams) (UpdateGitLabConnectionRow, error) {
	row := q.db.QueryRow(ctx, updateGitLabConnection,
		arg.InstanceUrl,
		arg.BranchNameFormat,
		arg.LinkCommits,
		arg.Linkbacks,
		arg.Enabled,
		arg.ConnectedAt,
		arg.WorkspaceID,
	)
	var i UpdateGitLabConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Enabled,
		&i.InstanceUrl,
		&i.BranchNameFormat,
		&i.LinkCommits,
		&i.Linkbacks,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGitLabUserLink = `-- name: UpdateGitLabUserLink :one
UPDATE gitlab_user_link
SET gitlab_username = $1,
    gitlab_user_id = $2
WHERE workspace_id = $3 AND user_id = $4
RETURNING id, workspace_id, user_id, gitlab_username, gitlab_user_id, created_at, updated_at
`

type UpdateGitLabUserLinkParams struct {
	GitlabUsername string
	GitlabUserID   *int64
	WorkspaceID    uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) UpdateGitLabUserLink(ctx context.Context, arg UpdateGitLabUserLinkParams) (GitlabUserLink, error) {
	row := q.db.QueryRow(ctx, updateGitLabUserLink,
		arg.GitlabUsername,
		arg.GitlabUserID,
		arg.WorkspaceID,
		arg.UserID,
	)
	var i GitlabUserLink
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.GitlabUsername,
		&i.GitlabUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
