// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows
INSERT INTO idempotency_key (client_id, op_id, workspace_id, request_hash, result, version, expires_at)
VALUES ($1, $2, $3, $4, '{}'::jsonb, NULL, $5)
ON CONFLICT (client_id, op_id) DO NOTHING
`

type ClaimIdempotencyKeyParams struct {
	ClientID    uuid.UUID
	OpID        uuid.UUID
	WorkspaceID uuid.UUID
	RequestHash []byte
	ExpiresAt   time.Time
}

// ClaimIdempotencyKey is the first statement of every mutation.
//
// ON CONFLICT DO NOTHING means a concurrent duplicate loses the race and returns no row;
// the caller then reads the winner's stored result. This is what makes a client retry
// after a dropped response safe: the write happens once, and both callers see the same
// answer.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey,
		arg.ClientID,
		arg.OpID,
		arg.WorkspaceID,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_key
SET result = $1, version = $2
WHERE client_id = $3 AND op_id = $4
`

type CompleteIdempotencyKeyParams struct {
	Result   json.RawMessage
	Version  *int64
	ClientID uuid.UUID
	OpID     uuid.UUID
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.Result,
		arg.Version,
		arg.ClientID,
		arg.OpID,
	)
	return err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_key WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT client_id, op_id, workspace_id, request_hash, result, version, expires_at, created_at
FROM idempotency_key
WHERE client_id = $1 AND op_id = $2 AND expires_at > now()
`

type GetIdempotencyKeyParams struct {
	ClientID uuid.UUID
	OpID     uuid.UUID
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ClientID, arg.OpID)
	var i IdempotencyKey
	err := row.Scan(
		&i.ClientID,
		&i.OpID,
		&i.WorkspaceID,
		&i.RequestHash,
		&i.Result,
		&i.Version,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const releaseIdempotencyKey = `-- name: ReleaseIdempotencyKey :exec
DELETE FROM idempotency_key
WHERE client_id = $1 AND op_id = $2
`

type ReleaseIdempotencyKeyParams struct {
	ClientID uuid.UUID
	OpID     uuid.UUID
}

// A mutation that fails must not leave a claimed key behind: the client's retry would
// then read an empty result and believe the write succeeded.
func (q *Queries) ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, releaseIdempotencyKey, arg.ClientID, arg.OpID)
	return err
}
