// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveIssue = `-- name: ArchiveIssue :exec
UPDATE issue SET archived_at = now() WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveIssue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveIssue, id)
	return err
}

const bulkUpdateIssues = `-- name: BulkUpdateIssues :many
UPDATE issue
SET state_id     = COALESCE($1, state_id),
    priority     = COALESCE($2, priority),
    assignee_id  = CASE WHEN $3::boolean THEN NULL
                        ELSE COALESCE($4, assignee_id) END,
    estimate     = CASE WHEN $5::boolean THEN NULL
                        ELSE COALESCE($6, estimate) END,
    due_date     = CASE WHEN $7::boolean THEN NULL
                        ELSE COALESCE($8, due_date) END,
    project_id   = CASE WHEN $9::boolean THEN NULL
                        ELSE COALESCE($10, project_id) END,
    project_milestone_id = CASE
        WHEN $9::boolean OR $11::boolean THEN NULL
        ELSE COALESCE($12, project_milestone_id) END,
    cycle_id     = CASE WHEN $13::boolean THEN NULL
                        ELSE COALESCE($14, cycle_id) END,
    started_at   = CASE WHEN $15::boolean
                        THEN COALESCE(started_at, $16) ELSE started_at END,
    completed_at = CASE WHEN $15::boolean THEN $17 ELSE completed_at END,
    canceled_at  = CASE WHEN $15::boolean THEN $18  ELSE canceled_at  END
WHERE id = ANY($19::uuid[])
  AND workspace_id = $20
  AND team_id = ANY($21::uuid[])
  AND deleted_at IS NULL
RETURNING id, workspace_id, team_id, number, title, description, state_id,
          assignee_id, creator_id, priority, sort_order,
          started_at, completed_at, canceled_at,
          archived_at, deleted_at, created_at, updated_at,
          estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
`

type BulkUpdateIssuesParams struct {
	StateID            *uuid.UUID
	Priority           *int16
	ClearAssignee      bool
	AssigneeID         *uuid.UUID
	ClearEstimate      bool
	Estimate           *int16
	ClearDueDate       bool
	DueDate            pgtype.Date
	ClearProject       bool
	ProjectID          *uuid.UUID
	ClearMilestone     bool
	ProjectMilestoneID *uuid.UUID
	ClearCycle         bool
	CycleID            *uuid.UUID
	SetTimestamps      bool
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	Ids                []uuid.UUID
	WorkspaceID        uuid.UUID
	TeamIds            []uuid.UUID
}

type BulkUpdateIssuesRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// BulkUpdateIssues is the bulk-edit path: one property set across a selection, in one
// statement, under one version block.
//
// It never reorders, which is what lets it be a single statement — sort_order is minted
// per issue from its neighbours, and there is no such thing as one new key for two hundred
// rows.
//
// started_at is COALESCEd against itself rather than overwritten. The single-issue path
// keeps an existing start by reading the row under a lock first; doing that here would
// mean two hundred locks and two hundred round trips, so the rule that started_at is never
// cleared once set is expressed in the statement instead. Cycle time is computed from it.
func (q *Queries) BulkUpdateIssues(ctx context.Context, arg BulkUpdateIssuesParams) ([]BulkUpdateIssuesRow, error) {
	rows, err := q.db.Query(ctx, bulkUpdateIssues,
		arg.StateID,
		arg.Priority,
		arg.ClearAssignee,
		arg.AssigneeID,
		arg.ClearEstimate,
		arg.Estimate,
		arg.ClearDueDate,
		arg.DueDate,
		arg.ClearProject,
		arg.ProjectID,
		arg.ClearMilestone,
		arg.ProjectMilestoneID,
		arg.ClearCycle,
		arg.CycleID,
		arg.SetTimestamps,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CanceledAt,
		arg.Ids,
		arg.WorkspaceID,
		arg.TeamIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BulkUpdateIssuesRow{}
	for rows.Next() {
		var i BulkUpdateIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countIssuesInWorkspace = `-- name: CountIssuesInWorkspace :one
SELECT count(*) FROM issue
WHERE workspace_id = $1 AND archived_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) CountIssuesInWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuesInWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuesToPurge = `-- name: CountIssuesToPurge :one
SELECT count(*) FROM issue
WHERE workspace_id = $1
  AND deleted_at IS NOT NULL
  AND deleted_at <= $2
`

type CountIssuesToPurgeParams struct {
	WorkspaceID   uuid.UUID
	DeletedBefore *time.Time
}

// CountIssuesToPurge is what is left after a batch, so the caller can say whether the trash
// is empty rather than leaving them to call again and find out.
func (q *Queries) CountIssuesToPurge(ctx context.Context, arg CountIssuesToPurgeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuesToPurge, arg.WorkspaceID, arg.DeletedBefore)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :one

INSERT INTO issue (id, workspace_id, team_id, number, title, description,
                   state_id, assignee_id, creator_id, priority, sort_order,
                   started_at, completed_at, canceled_at,
                   estimate, due_date, due_date_source, parent_id, sub_issue_sort_order,
                   template_id, form_template_id, project_id, project_milestone_id, cycle_id, snoozed_until)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10,
        $11,
        $12, $13, $14,
        $15, $16,
        -- NOT NULL with a CHECK, so an absent caller has to mean something. 'manual' is
        -- the only honest default: a date an SLA owns is a fact only the SLA subsystem
        -- knows, and guessing it here would make that date look human-editable.
        COALESCE($17::text, 'manual'),
        $18, $19, $20,
        $21,
        $22, $23, $24,
        $25)
RETURNING id, workspace_id, team_id, number, title, description, state_id,
          assignee_id, creator_id, priority, sort_order,
          started_at, completed_at, canceled_at,
          archived_at, deleted_at, created_at, updated_at,
          estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
`

type CreateIssueParams struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      *string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
}

type CreateIssueRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// Every list below is the issue table's columns, in the table's own order, minus
// search_vector. Minus, because the generated vector is roughly the size of the text it
// indexes and nothing above the store reads it — shipping it would put a copy of every
// title and description on the wire a second time, once per bootstrap row. In the table's
// order, because that is the rule that makes a missing column obvious: a new column lands
// at the end, and so does its addition here.
func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (CreateIssueRow, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ID,
		arg.WorkspaceID,
		arg.TeamID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.StateID,
		arg.AssigneeID,
		arg.CreatorID,
		arg.Priority,
		arg.SortOrder,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CanceledAt,
		arg.Estimate,
		arg.DueDate,
		arg.DueDateSource,
		arg.ParentID,
		arg.SubIssueSortOrder,
		arg.TemplateID,
		arg.FormTemplateID,
		arg.ProjectID,
		arg.ProjectMilestoneID,
		arg.CycleID,
		arg.SnoozedUntil,
	)
	var i CreateIssueRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.AssigneeID,
		&i.CreatorID,
		&i.Priority,
		&i.SortOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Estimate,
		&i.DueDate,
		&i.DueDateSource,
		&i.ParentID,
		&i.SubIssueSortOrder,
		&i.TemplateID,
		&i.FormTemplateID,
		&i.DeletedBy,
		&i.ProjectID,
		&i.ProjectMilestoneID,
		&i.CycleID,
		&i.SnoozedUntil,
		&i.AutoClosedAt,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE id = $1 AND deleted_at IS NULL
`

type GetIssueRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

func (q *Queries) GetIssue(ctx context.Context, id uuid.UUID) (GetIssueRow, error) {
	row := q.db.QueryRow(ctx, getIssue, id)
	var i GetIssueRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.AssigneeID,
		&i.CreatorID,
		&i.Priority,
		&i.SortOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Estimate,
		&i.DueDate,
		&i.DueDateSource,
		&i.ParentID,
		&i.SubIssueSortOrder,
		&i.TemplateID,
		&i.FormTemplateID,
		&i.DeletedBy,
		&i.ProjectID,
		&i.ProjectMilestoneID,
		&i.CycleID,
		&i.SnoozedUntil,
		&i.AutoClosedAt,
	)
	return i, err
}

const getIssueByTeamAndNumber = `-- name: GetIssueByTeamAndNumber :one
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE team_id = $1 AND number = $2 AND deleted_at IS NULL
`

type GetIssueByTeamAndNumberParams struct {
	TeamID uuid.UUID
	Number int64
}

type GetIssueByTeamAndNumberRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

func (q *Queries) GetIssueByTeamAndNumber(ctx context.Context, arg GetIssueByTeamAndNumberParams) (GetIssueByTeamAndNumberRow, error) {
	row := q.db.QueryRow(ctx, getIssueByTeamAndNumber, arg.TeamID, arg.Number)
	var i GetIssueByTeamAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.AssigneeID,
		&i.CreatorID,
		&i.Priority,
		&i.SortOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Estimate,
		&i.DueDate,
		&i.DueDateSource,
		&i.ParentID,
		&i.SubIssueSortOrder,
		&i.TemplateID,
		&i.FormTemplateID,
		&i.DeletedBy,
		&i.ProjectID,
		&i.ProjectMilestoneID,
		&i.CycleID,
		&i.SnoozedUntil,
		&i.AutoClosedAt,
	)
	return i, err
}

const getIssueExists = `-- name: GetIssueExists :one
SELECT id FROM issue WHERE id = $1
`

// GetIssueExists answers "is this id taken", for the client-minted-id path.
//
// Deliberately not GetIssue: that filters deleted_at IS NULL, and a soft-deleted issue's
// id is still occupied — the primary key does not care that the row is hidden. Reusing
// GetIssue here would let a client claim the id of an issue it had just deleted and hit
// the unique constraint instead, which surfaces as an internal error rather than as the
// validation message that explains it.
//
// Returns only the id: this is an existence check and reading the row would be handing
// back an issue the caller may have no right to see.
func (q *Queries) GetIssueExists(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getIssueExists, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getIssueForUpdate = `-- name: GetIssueForUpdate :one
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

type GetIssueForUpdateRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// GetIssueForUpdate locks the row for the rest of the transaction. Used by every update
// path so that read-modify-write on timestamps (started_at, completed_at) cannot
// interleave with a concurrent status change and lose one of them.
func (q *Queries) GetIssueForUpdate(ctx context.Context, id uuid.UUID) (GetIssueForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getIssueForUpdate, id)
	var i GetIssueForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.AssigneeID,
		&i.CreatorID,
		&i.Priority,
		&i.SortOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Estimate,
		&i.DueDate,
		&i.DueDateSource,
		&i.ParentID,
		&i.SubIssueSortOrder,
		&i.TemplateID,
		&i.FormTemplateID,
		&i.DeletedBy,
		&i.ProjectID,
		&i.ProjectMilestoneID,
		&i.CycleID,
		&i.SnoozedUntil,
		&i.AutoClosedAt,
	)
	return i, err
}

const getLastSortOrderForState = `-- name: GetLastSortOrderForState :one
SELECT sort_order FROM issue
WHERE team_id = $1 AND state_id = $2
  AND archived_at IS NULL AND deleted_at IS NULL
ORDER BY sort_order DESC
LIMIT 1
`

type GetLastSortOrderForStateParams struct {
	TeamID  uuid.UUID
	StateID uuid.UUID
}

func (q *Queries) GetLastSortOrderForState(ctx context.Context, arg GetLastSortOrderForStateParams) (string, error) {
	row := q.db.QueryRow(ctx, getLastSortOrderForState, arg.TeamID, arg.StateID)
	var sort_order string
	err := row.Scan(&sort_order)
	return sort_order, err
}

const getLastSubIssueSortOrder = `-- name: GetLastSubIssueSortOrder :one
SELECT sub_issue_sort_order FROM issue
WHERE parent_id = $1 AND sub_issue_sort_order IS NOT NULL AND deleted_at IS NULL
ORDER BY sub_issue_sort_order DESC
LIMIT 1
`

func (q *Queries) GetLastSubIssueSortOrder(ctx context.Context, parentID *uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getLastSubIssueSortOrder, parentID)
	var sub_issue_sort_order *string
	err := row.Scan(&sub_issue_sort_order)
	return sub_issue_sort_order, err
}

const getSortOrderAfter = `-- name: GetSortOrderAfter :one
SELECT sort_order FROM issue
WHERE team_id = $1 AND state_id = $2
  AND sort_order > $3
  AND archived_at IS NULL AND deleted_at IS NULL
ORDER BY sort_order
LIMIT 1
`

type GetSortOrderAfterParams struct {
	TeamID    uuid.UUID
	StateID   uuid.UUID
	SortOrder string
}

func (q *Queries) GetSortOrderAfter(ctx context.Context, arg GetSortOrderAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, getSortOrderAfter, arg.TeamID, arg.StateID, arg.SortOrder)
	var sort_order string
	err := row.Scan(&sort_order)
	return sort_order, err
}

const getSortOrderBefore = `-- name: GetSortOrderBefore :one
SELECT sort_order FROM issue
WHERE team_id = $1 AND state_id = $2
  AND sort_order < $3
  AND archived_at IS NULL AND deleted_at IS NULL
ORDER BY sort_order DESC
LIMIT 1
`

type GetSortOrderBeforeParams struct {
	TeamID    uuid.UUID
	StateID   uuid.UUID
	SortOrder string
}

// Neighbour lookups for fractional-index insertion: find the sort_order either side of
// the target position so a new key can be minted between them.
func (q *Queries) GetSortOrderBefore(ctx context.Context, arg GetSortOrderBeforeParams) (string, error) {
	row := q.db.QueryRow(ctx, getSortOrderBefore, arg.TeamID, arg.StateID, arg.SortOrder)
	var sort_order string
	err := row.Scan(&sort_order)
	return sort_order, err
}

const getSubIssueSortOrderAfter = `-- name: GetSubIssueSortOrderAfter :one
SELECT sub_issue_sort_order FROM issue
WHERE parent_id = $1
  AND sub_issue_sort_order > $2
  AND deleted_at IS NULL
ORDER BY sub_issue_sort_order
LIMIT 1
`

type GetSubIssueSortOrderAfterParams struct {
	ParentID          *uuid.UUID
	SubIssueSortOrder *string
}

// The sibling order is its own sequence per parent, unrelated to the team backlog's, so
// it gets its own neighbour lookups rather than reusing the ones above.
func (q *Queries) GetSubIssueSortOrderAfter(ctx context.Context, arg GetSubIssueSortOrderAfterParams) (*string, error) {
	row := q.db.QueryRow(ctx, getSubIssueSortOrderAfter, arg.ParentID, arg.SubIssueSortOrder)
	var sub_issue_sort_order *string
	err := row.Scan(&sub_issue_sort_order)
	return sub_issue_sort_order, err
}

const listArchivedIssuesForTeam = `-- name: ListArchivedIssuesForTeam :many
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
       project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE team_id = $1 AND archived_at IS NOT NULL AND deleted_at IS NULL
ORDER BY archived_at DESC
`

type ListArchivedIssuesForTeamRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

func (q *Queries) ListArchivedIssuesForTeam(ctx context.Context, teamID uuid.UUID) ([]ListArchivedIssuesForTeamRow, error) {
	rows, err := q.db.Query(ctx, listArchivedIssuesForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArchivedIssuesForTeamRow{}
	for rows.Next() {
		var i ListArchivedIssuesForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildIssues = `-- name: ListChildIssues :many
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE parent_id = $1 AND deleted_at IS NULL
ORDER BY sub_issue_sort_order, id
`

type ListChildIssuesRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// ListChildIssues feeds the sub-issue list and the progress rollup on the parent. The
// rollup counts states rather than sums them, so it needs the rows, not an aggregate —
// and a parent has a handful of children, not a page of them.
//
// Archived children are included on purpose: the parent's "3 of 5 done" must not silently
// become "3 of 4" because somebody archived one, which would make a finished parent look
// unfinished for no visible reason.
func (q *Queries) ListChildIssues(ctx context.Context, parentID *uuid.UUID) ([]ListChildIssuesRow, error) {
	rows, err := q.db.Query(ctx, listChildIssues, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildIssuesRow{}
	for rows.Next() {
		var i ListChildIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildIssuesForParents = `-- name: ListChildIssuesForParents :many
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE parent_id = ANY($1::uuid[])
  AND workspace_id = $2
  AND deleted_at IS NULL
ORDER BY parent_id, sub_issue_sort_order, id
`

type ListChildIssuesForParentsParams struct {
	ParentIds   []uuid.UUID
	WorkspaceID uuid.UUID
}

type ListChildIssuesForParentsRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// ListChildIssuesForParents is ListChildIssues for a whole page of parents at once.
//
// One statement rather than one per row, and that is the entire reason it exists: a list
// view that renders a progress bar on every parent would otherwise issue a query per
// visible issue, which is the N+1 the API's hydration layer is built to avoid. The
// per-parent version above stays for the single-issue path, where the array round trip
// would buy nothing.
//
// Ordered by parent first so the caller can group the rows without sorting them again.
func (q *Queries) ListChildIssuesForParents(ctx context.Context, arg ListChildIssuesForParentsParams) ([]ListChildIssuesForParentsRow, error) {
	rows, err := q.db.Query(ctx, listChildIssuesForParents, arg.ParentIds, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildIssuesForParentsRow{}
	for rows.Next() {
		var i ListChildIssuesForParentsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedIssues = `-- name: ListDeletedIssues :many
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE workspace_id = $1
  AND team_id = ANY($2::uuid[])
  AND deleted_at IS NOT NULL
  AND deleted_at > $3
ORDER BY deleted_at DESC
`

type ListDeletedIssuesParams struct {
	WorkspaceID  uuid.UUID
	TeamIds      []uuid.UUID
	DeletedAfter *time.Time
}

type ListDeletedIssuesRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// ListDeletedIssues is the "recently deleted" screen. Ordered by deletion time rather than
// by sort_order, because the only question being asked here is "what did I just lose".
func (q *Queries) ListDeletedIssues(ctx context.Context, arg ListDeletedIssuesParams) ([]ListDeletedIssuesRow, error) {
	rows, err := q.db.Query(ctx, listDeletedIssues, arg.WorkspaceID, arg.TeamIds, arg.DeletedAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedIssuesRow{}
	for rows.Next() {
		var i ListDeletedIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByIDs = `-- name: ListIssuesByIDs :many
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE id = ANY($1::uuid[])
  AND workspace_id = $2
  AND team_id = ANY($3::uuid[])
  AND deleted_at IS NULL
ORDER BY id
`

type ListIssuesByIDsParams struct {
	Ids         []uuid.UUID
	WorkspaceID uuid.UUID
	TeamIds     []uuid.UUID
}

type ListIssuesByIDsRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// ListIssuesByIDs reads a scattered set of issues in one round trip, filtered to the teams
// the caller can see.
//
// The team filter is in the statement rather than in Go because this is a read by id: a
// caller who could name an issue in a team they are not in would otherwise get it back,
// and "did this uuid come back" is the enumeration oracle every not-found in this package
// exists to close. Archived issues are included — an issue reached by id is reachable
// whether or not it is on a board, which is the same rule GetIssue follows.
func (q *Queries) ListIssuesByIDs(ctx context.Context, arg ListIssuesByIDsParams) ([]ListIssuesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listIssuesByIDs, arg.Ids, arg.WorkspaceID, arg.TeamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesByIDsRow{}
	for rows.Next() {
		var i ListIssuesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesForProject = `-- name: ListIssuesForProject :many
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE project_id = $1 AND archived_at IS NULL AND deleted_at IS NULL
ORDER BY sort_order
`

type ListIssuesForProjectRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// ListIssuesForProject is the project's Issues tab. Live issues only; archived and
// deleted stay off the board the same way they stay off a team list.
func (q *Queries) ListIssuesForProject(ctx context.Context, projectID *uuid.UUID) ([]ListIssuesForProjectRow, error) {
	rows, err := q.db.Query(ctx, listIssuesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesForProjectRow{}
	for rows.Next() {
		var i ListIssuesForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesForTeam = `-- name: ListIssuesForTeam :many
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE team_id = $1 AND archived_at IS NULL AND deleted_at IS NULL
ORDER BY sort_order
`

type ListIssuesForTeamRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

func (q *Queries) ListIssuesForTeam(ctx context.Context, teamID uuid.UUID) ([]ListIssuesForTeamRow, error) {
	rows, err := q.db.Query(ctx, listIssuesForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesForTeamRow{}
	for rows.Next() {
		var i ListIssuesForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyIssues = `-- name: ListMyIssues :many
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE workspace_id = $1
  AND assignee_id = $2
  AND team_id = ANY($3::uuid[])
  AND archived_at IS NULL
  AND deleted_at IS NULL
  AND ($4::boolean
       OR (completed_at IS NULL AND canceled_at IS NULL))
ORDER BY updated_at DESC, id
`

type ListMyIssuesParams struct {
	WorkspaceID      uuid.UUID
	AssigneeID       *uuid.UUID
	TeamIds          []uuid.UUID
	IncludeCompleted bool
}

type ListMyIssuesRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// ListMyIssues is everything assigned to the caller across every team they can see.
//
// Ordered most-recently-touched first rather than by priority: 0 means "no priority", so
// the numeric order puts unprioritised work at the top, and the display order is a client
// concern the replica already implements. This only has to be stable and useful.
func (q *Queries) ListMyIssues(ctx context.Context, arg ListMyIssuesParams) ([]ListMyIssuesRow, error) {
	rows, err := q.db.Query(ctx, listMyIssues,
		arg.WorkspaceID,
		arg.AssigneeID,
		arg.TeamIds,
		arg.IncludeCompleted,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyIssuesRow{}
	for rows.Next() {
		var i ListMyIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleClosedIssues = `-- name: ListStaleClosedIssues :many
SELECT i.id, i.workspace_id, i.team_id, i.number, i.title, i.description, i.state_id,
       i.assignee_id, i.creator_id, i.priority, i.sort_order,
       i.started_at, i.completed_at, i.canceled_at,
       i.archived_at, i.deleted_at, i.created_at, i.updated_at,
       i.estimate, i.due_date, i.due_date_source, i.parent_id, i.sub_issue_sort_order, i.template_id, i.form_template_id, i.deleted_by,
       i.project_id, i.project_milestone_id, i.cycle_id, i.snoozed_until, i.auto_closed_at
FROM issue i
JOIN workflow_state ws ON ws.id = i.state_id
WHERE i.team_id = $1
  AND i.archived_at IS NULL AND i.deleted_at IS NULL
  AND ws.category IN ('completed', 'canceled', 'duplicate')
  AND i.updated_at < $2
ORDER BY i.updated_at, i.id
`

type ListStaleClosedIssuesParams struct {
	TeamID uuid.UUID
	Cutoff time.Time
}

type ListStaleClosedIssuesRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// Stale closed work for auto-archive. The domain layer still refuses a row whose
// parent, children or project would leave the graph inconsistent.
func (q *Queries) ListStaleClosedIssues(ctx context.Context, arg ListStaleClosedIssuesParams) ([]ListStaleClosedIssuesRow, error) {
	rows, err := q.db.Query(ctx, listStaleClosedIssues, arg.TeamID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleClosedIssuesRow{}
	for rows.Next() {
		var i ListStaleClosedIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleOpenIssues = `-- name: ListStaleOpenIssues :many
SELECT i.id, i.workspace_id, i.team_id, i.number, i.title, i.description, i.state_id,
       i.assignee_id, i.creator_id, i.priority, i.sort_order,
       i.started_at, i.completed_at, i.canceled_at,
       i.archived_at, i.deleted_at, i.created_at, i.updated_at,
       i.estimate, i.due_date, i.due_date_source, i.parent_id, i.sub_issue_sort_order, i.template_id, i.form_template_id, i.deleted_by,
       i.project_id, i.project_milestone_id, i.cycle_id, i.snoozed_until, i.auto_closed_at
FROM issue i
JOIN workflow_state ws ON ws.id = i.state_id
WHERE i.team_id = $1
  AND i.archived_at IS NULL AND i.deleted_at IS NULL
  AND ws.category NOT IN ('completed', 'canceled', 'duplicate')
  AND i.updated_at < $2
ORDER BY i.updated_at, i.id
`

type ListStaleOpenIssuesParams struct {
	TeamID uuid.UUID
	Cutoff time.Time
}

type ListStaleOpenIssuesRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// Stale open work for auto-close. Closed categories are already done; the engine
// then applies the cycle/project/due/children skips in the domain layer, because those
// are graph questions a single WHERE cannot answer without lying about a parent in
// another team.
func (q *Queries) ListStaleOpenIssues(ctx context.Context, arg ListStaleOpenIssuesParams) ([]ListStaleOpenIssuesRow, error) {
	rows, err := q.db.Query(ctx, listStaleOpenIssues, arg.TeamID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleOpenIssuesRow{}
	for rows.Next() {
		var i ListStaleOpenIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesWithPurgeableIssues = `-- name: ListWorkspacesWithPurgeableIssues :many
SELECT DISTINCT workspace_id FROM issue
WHERE deleted_at IS NOT NULL AND deleted_at <= $1
`

// ListWorkspacesWithPurgeableIssues drives the retention sweep, which has no principal and
// therefore no workspace of its own. Distinct rather than a join over workspace, because
// the answer wanted is "where is there work to do", and most workspaces have none.
func (q *Queries) ListWorkspacesWithPurgeableIssues(ctx context.Context, deletedBefore *time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWorkspacesWithPurgeableIssues, deletedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var workspace_id uuid.UUID
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDeletedIssues = `-- name: PurgeDeletedIssues :many
WITH doomed AS (
  SELECT d.id FROM issue d
  WHERE d.workspace_id = $1
    AND d.deleted_at IS NOT NULL
    AND d.deleted_at <= $2
  ORDER BY d.deleted_at
  LIMIT $3
  FOR UPDATE
)
DELETE FROM issue i WHERE i.id IN (SELECT doomed.id FROM doomed)
RETURNING i.id, i.team_id
`

type PurgeDeletedIssuesParams struct {
	WorkspaceID   uuid.UUID
	DeletedBefore *time.Time
	PageSize      int32
}

type PurgeDeletedIssuesRow struct {
	ID     uuid.UUID
	TeamID uuid.UUID
}

// PurgeDeletedIssues hard-deletes a bounded batch of trashed issues and is the only
// statement in the product that removes an issue row.
//
// Everything that references the issue goes with it, by foreign key: comment,
// issue_history, issue_label, issue_relation from both ends, issue_subscription and
// notification are all ON DELETE CASCADE. Sub-issues are the exception — issue.parent_id is
// ON DELETE SET NULL — so a child of a purged parent survives, orphaned, which is the same
// choice the client's own cascade makes for the same reason: a cross-team sub-issue belongs
// to a team that has lost nothing.
//
// One statement rather than a SELECT followed by a DELETE. The window between the two would
// be a window in which somebody restores an issue from the trash screen and has it hard
// deleted anyway — the one mistake this table has no way back from. FOR UPDATE inside the
// CTE is what makes the choice of victims and their removal the same instant.
//
// The limit is not a nicety. Every returned id becomes a change_log row inside the caller's
// transaction, and the version counter is a workspace-wide row lock, so an unbounded purge
// of a large trash would hold every other writer in the workspace behind it.
func (q *Queries) PurgeDeletedIssues(ctx context.Context, arg PurgeDeletedIssuesParams) ([]PurgeDeletedIssuesRow, error) {
	rows, err := q.db.Query(ctx, purgeDeletedIssues, arg.WorkspaceID, arg.DeletedBefore, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurgeDeletedIssuesRow{}
	for rows.Next() {
		var i PurgeDeletedIssuesRow
		if err := rows.Scan(&i.ID, &i.TeamID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreIssue = `-- name: RestoreIssue :one
UPDATE issue SET deleted_at = NULL, deleted_by = NULL
WHERE id = $1 AND deleted_at IS NOT NULL AND deleted_at > $2
RETURNING id, workspace_id, team_id, number, title, description, state_id,
          assignee_id, creator_id, priority, sort_order,
          started_at, completed_at, canceled_at,
          archived_at, deleted_at, created_at, updated_at,
          estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
`

type RestoreIssueParams struct {
	ID           uuid.UUID
	DeletedAfter *time.Time
}

type RestoreIssueRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// RestoreIssue returns the row because a restore puts the issue back on the sync stream,
// and the payload has to be the issue as it is now — not as the client last saw it before
// the delete.
//
// The window is a parameter rather than a literal: how long a delete stays undoable is a
// product decision, and burying "30 days" in a query means changing it is a migration.
//
// deleted_by is cleared alongside deleted_at. Leaving it set would make a live issue carry
// the name of somebody who deleted it once and was overruled, which is a fact the activity
// feed already holds and this column would then contradict on the next delete.
func (q *Queries) RestoreIssue(ctx context.Context, arg RestoreIssueParams) (RestoreIssueRow, error) {
	row := q.db.QueryRow(ctx, restoreIssue, arg.ID, arg.DeletedAfter)
	var i RestoreIssueRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.AssigneeID,
		&i.CreatorID,
		&i.Priority,
		&i.SortOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Estimate,
		&i.DueDate,
		&i.DueDateSource,
		&i.ParentID,
		&i.SubIssueSortOrder,
		&i.TemplateID,
		&i.FormTemplateID,
		&i.DeletedBy,
		&i.ProjectID,
		&i.ProjectMilestoneID,
		&i.CycleID,
		&i.SnoozedUntil,
		&i.AutoClosedAt,
	)
	return i, err
}

const setIssueSnooze = `-- name: SetIssueSnooze :one
UPDATE issue SET snoozed_until = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, team_id, number, title, description, state_id,
          assignee_id, creator_id, priority, sort_order,
          started_at, completed_at, canceled_at,
          archived_at, deleted_at, created_at, updated_at,
          estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
`

type SetIssueSnoozeParams struct {
	SnoozedUntil *time.Time
	ID           uuid.UUID
}

type SetIssueSnoozeRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

func (q *Queries) SetIssueSnooze(ctx context.Context, arg SetIssueSnoozeParams) (SetIssueSnoozeRow, error) {
	row := q.db.QueryRow(ctx, setIssueSnooze, arg.SnoozedUntil, arg.ID)
	var i SetIssueSnoozeRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.AssigneeID,
		&i.CreatorID,
		&i.Priority,
		&i.SortOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Estimate,
		&i.DueDate,
		&i.DueDateSource,
		&i.ParentID,
		&i.SubIssueSortOrder,
		&i.TemplateID,
		&i.FormTemplateID,
		&i.DeletedBy,
		&i.ProjectID,
		&i.ProjectMilestoneID,
		&i.CycleID,
		&i.SnoozedUntil,
		&i.AutoClosedAt,
	)
	return i, err
}

const softDeleteIssue = `-- name: SoftDeleteIssue :exec
UPDATE issue SET deleted_at = now(), deleted_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteIssueParams struct {
	DeletedBy *uuid.UUID
	ID        uuid.UUID
}

// SoftDeleteIssue records who as well as when.
//
// deleted_by is nullable and a caller may pass nothing, which is what the retention sweep
// and any future automation want: a deletion nobody instructed has no person to name, and a
// guessed one would be worse than a blank on the trash screen.
func (q *Queries) SoftDeleteIssue(ctx context.Context, arg SoftDeleteIssueParams) error {
	_, err := q.db.Exec(ctx, softDeleteIssue, arg.DeletedBy, arg.ID)
	return err
}

const streamIssuesForBootstrap = `-- name: StreamIssuesForBootstrap :many
SELECT id, workspace_id, team_id, number, title, description, state_id,
       assignee_id, creator_id, priority, sort_order,
       started_at, completed_at, canceled_at,
       archived_at, deleted_at, created_at, updated_at,
       estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
FROM issue
WHERE workspace_id = $1
  AND team_id = ANY($2::uuid[])
  AND archived_at IS NULL
  AND deleted_at IS NULL
  AND id > $3
ORDER BY id
LIMIT $4
`

type StreamIssuesForBootstrapParams struct {
	WorkspaceID uuid.UUID
	TeamIds     []uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

type StreamIssuesForBootstrapRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

// StreamIssuesForBootstrap feeds the initial snapshot. Ordered by id (UUIDv7, so
// effectively creation order) and keyset-paginated: OFFSET would degrade quadratically
// on a workspace with a hundred thousand issues, which is exactly where it matters.
func (q *Queries) StreamIssuesForBootstrap(ctx context.Context, arg StreamIssuesForBootstrapParams) ([]StreamIssuesForBootstrapRow, error) {
	rows, err := q.db.Query(ctx, streamIssuesForBootstrap,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreamIssuesForBootstrapRow{}
	for rows.Next() {
		var i StreamIssuesForBootstrapRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.AssigneeID,
			&i.CreatorID,
			&i.Priority,
			&i.SortOrder,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estimate,
			&i.DueDate,
			&i.DueDateSource,
			&i.ParentID,
			&i.SubIssueSortOrder,
			&i.TemplateID,
			&i.FormTemplateID,
			&i.DeletedBy,
			&i.ProjectID,
			&i.ProjectMilestoneID,
			&i.CycleID,
			&i.SnoozedUntil,
			&i.AutoClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveIssue = `-- name: UnarchiveIssue :exec
UPDATE issue SET archived_at = NULL WHERE id = $1
`

func (q *Queries) UnarchiveIssue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unarchiveIssue, id)
	return err
}

const updateIssue = `-- name: UpdateIssue :one
UPDATE issue
SET title            = COALESCE($1, title),
    description      = COALESCE($2, description),
    state_id         = COALESCE($3, state_id),
    priority         = COALESCE($4, priority),
    sort_order       = COALESCE($5, sort_order),
    team_id          = COALESCE($6, team_id),
    number           = COALESCE($7, number),
    due_date_source  = COALESCE($8, due_date_source),
    sub_issue_sort_order = COALESCE($9, sub_issue_sort_order),
    -- Assignee is three-state: absent (leave alone), set, or explicitly cleared. A plain
    -- COALESCE cannot express "clear", so the caller passes clear_assignee separately.
    assignee_id  = CASE WHEN $10::boolean THEN NULL
                        ELSE COALESCE($11, assignee_id) END,
    -- The same three states, for the same reason. Unestimated is not zero, no due date is
    -- not the epoch, and no parent is not a sub-issue of nothing — each needs a way to say
    -- "remove it" that a nil pointer cannot express.
    estimate     = CASE WHEN $12::boolean THEN NULL
                        ELSE COALESCE($13, estimate) END,
    due_date     = CASE WHEN $14::boolean THEN NULL
                        ELSE COALESCE($15, due_date) END,
    -- Clearing the parent leaves sub_issue_sort_order behind rather than nulling it: if
    -- the issue is re-parented to the same issue by an undo, it lands back where it was.
    parent_id    = CASE WHEN $16::boolean THEN NULL
                        ELSE COALESCE($17, parent_id) END,
    -- Project is three-state for the same reason as parent. Clearing it also drops the
    -- milestone: a milestone without a project is refused by the trigger, and leaving it
    -- set would make the next write fail for a reason the caller cannot see.
    project_id = CASE WHEN $18::boolean THEN NULL
                      ELSE COALESCE($19, project_id) END,
    project_milestone_id = CASE
        WHEN $18::boolean OR $20::boolean THEN NULL
        ELSE COALESCE($21, project_milestone_id) END,
    cycle_id = CASE WHEN $22::boolean THEN NULL
                    ELSE COALESCE($23, cycle_id) END,
    snoozed_until = CASE WHEN $24::boolean THEN NULL
                         ELSE COALESCE($25, snoozed_until) END,
    auto_closed_at = CASE WHEN $26::boolean THEN NULL
                          ELSE COALESCE($27, auto_closed_at) END,
    -- Category timestamps are set by the domain layer, which knows the transition rules
    -- (started_at is never cleared once set, because insights read it).
    started_at   = CASE WHEN $28::boolean THEN $29   ELSE started_at   END,
    completed_at = CASE WHEN $28::boolean THEN $30 ELSE completed_at END,
    canceled_at  = CASE WHEN $28::boolean THEN $31  ELSE canceled_at  END
WHERE id = $32 AND deleted_at IS NULL
RETURNING id, workspace_id, team_id, number, title, description, state_id,
          assignee_id, creator_id, priority, sort_order,
          started_at, completed_at, canceled_at,
          archived_at, deleted_at, created_at, updated_at,
          estimate, due_date, due_date_source, parent_id, sub_issue_sort_order, template_id, form_template_id, deleted_by,
          project_id, project_milestone_id, cycle_id, snoozed_until, auto_closed_at
`

type UpdateIssueParams struct {
	Title              *string
	Description        *string
	StateID            *uuid.UUID
	Priority           *int16
	SortOrder          *string
	TeamID             *uuid.UUID
	Number             *int64
	DueDateSource      *string
	SubIssueSortOrder  *string
	ClearAssignee      bool
	AssigneeID         *uuid.UUID
	ClearEstimate      bool
	Estimate           *int16
	ClearDueDate       bool
	DueDate            pgtype.Date
	ClearParent        bool
	ParentID           *uuid.UUID
	ClearProject       bool
	ProjectID          *uuid.UUID
	ClearMilestone     bool
	ProjectMilestoneID *uuid.UUID
	ClearCycle         bool
	CycleID            *uuid.UUID
	ClearSnooze        bool
	SnoozedUntil       *time.Time
	ClearAutoClosed    bool
	AutoClosedAt       *time.Time
	SetTimestamps      bool
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ID                 uuid.UUID
}

type UpdateIssueRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	FormTemplateID     *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) (UpdateIssueRow, error) {
	row := q.db.QueryRow(ctx, updateIssue,
		arg.Title,
		arg.Description,
		arg.StateID,
		arg.Priority,
		arg.SortOrder,
		arg.TeamID,
		arg.Number,
		arg.DueDateSource,
		arg.SubIssueSortOrder,
		arg.ClearAssignee,
		arg.AssigneeID,
		arg.ClearEstimate,
		arg.Estimate,
		arg.ClearDueDate,
		arg.DueDate,
		arg.ClearParent,
		arg.ParentID,
		arg.ClearProject,
		arg.ProjectID,
		arg.ClearMilestone,
		arg.ProjectMilestoneID,
		arg.ClearCycle,
		arg.CycleID,
		arg.ClearSnooze,
		arg.SnoozedUntil,
		arg.ClearAutoClosed,
		arg.AutoClosedAt,
		arg.SetTimestamps,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CanceledAt,
		arg.ID,
	)
	var i UpdateIssueRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.AssigneeID,
		&i.CreatorID,
		&i.Priority,
		&i.SortOrder,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Estimate,
		&i.DueDate,
		&i.DueDateSource,
		&i.ParentID,
		&i.SubIssueSortOrder,
		&i.TemplateID,
		&i.FormTemplateID,
		&i.DeletedBy,
		&i.ProjectID,
		&i.ProjectMilestoneID,
		&i.CycleID,
		&i.SnoozedUntil,
		&i.AutoClosedAt,
	)
	return i, err
}
