// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveLabel = `-- name: ArchiveLabel :one
UPDATE label SET archived_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, workspace_id, team_id, parent_id, is_group, name, description, color,
          position, archived_at, created_at, updated_at
`

type ArchiveLabelRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	ParentID    *uuid.UUID
	IsGroup     bool
	Name        string
	Description *string
	Color       string
	Position    string
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ArchiveLabel(ctx context.Context, id uuid.UUID) (ArchiveLabelRow, error) {
	row := q.db.QueryRow(ctx, archiveLabel, id)
	var i ArchiveLabelRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.ParentID,
		&i.IsGroup,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countIssuesWithLabel = `-- name: CountIssuesWithLabel :one
SELECT count(*) FROM issue_label il
JOIN issue i ON i.id = il.issue_id
WHERE il.label_id = $1 AND i.archived_at IS NULL AND i.deleted_at IS NULL
`

// CountIssuesWithLabel answers "is this label worth keeping" before an archive, and is the
// number the confirmation dialog shows. Counted through the issue so an archived or
// deleted issue does not inflate it.
func (q *Queries) CountIssuesWithLabel(ctx context.Context, labelID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuesWithLabel, labelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO label (id, workspace_id, team_id, parent_id, is_group, name, description, color, position)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        -- NOT NULL with a product default. A caller that has no opinion about colour must
        -- not be able to write an empty string that renders as a transparent chip.
        COALESCE($8::text, '#6b7280'),
        $9)
RETURNING id, workspace_id, team_id, parent_id, is_group, name, description, color,
          position, archived_at, created_at, updated_at
`

type CreateLabelParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	ParentID    *uuid.UUID
	IsGroup     bool
	Name        string
	Description *string
	Color       *string
	Position    string
}

type CreateLabelRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	ParentID    *uuid.UUID
	IsGroup     bool
	Name        string
	Description *string
	Color       string
	Position    string
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (CreateLabelRow, error) {
	row := q.db.QueryRow(ctx, createLabel,
		arg.ID,
		arg.WorkspaceID,
		arg.TeamID,
		arg.ParentID,
		arg.IsGroup,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Position,
	)
	var i CreateLabelRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.ParentID,
		&i.IsGroup,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLabel = `-- name: GetLabel :one
SELECT id, workspace_id, team_id, parent_id, is_group, name, description, color,
       position, archived_at, created_at, updated_at
FROM label
WHERE id = $1
`

type GetLabelRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	ParentID    *uuid.UUID
	IsGroup     bool
	Name        string
	Description *string
	Color       string
	Position    string
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetLabel(ctx context.Context, id uuid.UUID) (GetLabelRow, error) {
	row := q.db.QueryRow(ctx, getLabel, id)
	var i GetLabelRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.ParentID,
		&i.IsGroup,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLabelPositionAfter = `-- name: GetLabelPositionAfter :one
SELECT position FROM label
WHERE workspace_id = $1
  AND team_id IS NOT DISTINCT FROM $2
  AND position > $3
  AND archived_at IS NULL
ORDER BY position
LIMIT 1
`

type GetLabelPositionAfterParams struct {
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	Position    string
}

func (q *Queries) GetLabelPositionAfter(ctx context.Context, arg GetLabelPositionAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, getLabelPositionAfter, arg.WorkspaceID, arg.TeamID, arg.Position)
	var position string
	err := row.Scan(&position)
	return position, err
}

const getLabelPositionBefore = `-- name: GetLabelPositionBefore :one
SELECT position FROM label
WHERE workspace_id = $1
  AND team_id IS NOT DISTINCT FROM $2
  AND position < $3
  AND archived_at IS NULL
ORDER BY position DESC
LIMIT 1
`

type GetLabelPositionBeforeParams struct {
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	Position    string
}

// Neighbour lookups for fractional-index insertion. Positions are only ever compared
// within one scope, so the predicate matches scope_key's own definition: NULL team means
// the workspace scope, and IS NOT DISTINCT FROM is what makes that comparable in one
// expression instead of two query variants.
func (q *Queries) GetLabelPositionBefore(ctx context.Context, arg GetLabelPositionBeforeParams) (string, error) {
	row := q.db.QueryRow(ctx, getLabelPositionBefore, arg.WorkspaceID, arg.TeamID, arg.Position)
	var position string
	err := row.Scan(&position)
	return position, err
}

const getLastLabelPosition = `-- name: GetLastLabelPosition :one
SELECT position FROM label
WHERE workspace_id = $1
  AND team_id IS NOT DISTINCT FROM $2
  AND archived_at IS NULL
ORDER BY position DESC
LIMIT 1
`

type GetLastLabelPositionParams struct {
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
}

func (q *Queries) GetLastLabelPosition(ctx context.Context, arg GetLastLabelPositionParams) (string, error) {
	row := q.db.QueryRow(ctx, getLastLabelPosition, arg.WorkspaceID, arg.TeamID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const listLabelsForTeam = `-- name: ListLabelsForTeam :many
SELECT id, workspace_id, team_id, parent_id, is_group, name, description, color,
       position, archived_at, created_at, updated_at
FROM label
WHERE workspace_id = $1
  AND (team_id IS NULL OR team_id = $2)
  AND archived_at IS NULL
ORDER BY scope_key, position
`

type ListLabelsForTeamParams struct {
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
}

type ListLabelsForTeamRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	ParentID    *uuid.UUID
	IsGroup     bool
	Name        string
	Description *string
	Color       string
	Position    string
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// ListLabelsForTeam is what the label picker on an issue may offer: the workspace's own
// labels plus that one team's. A label from another team is not merely hidden here — the
// issue_label trigger rejects it — so this list and the write rule agree by construction.
func (q *Queries) ListLabelsForTeam(ctx context.Context, arg ListLabelsForTeamParams) ([]ListLabelsForTeamRow, error) {
	rows, err := q.db.Query(ctx, listLabelsForTeam, arg.WorkspaceID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsForTeamRow{}
	for rows.Next() {
		var i ListLabelsForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.ParentID,
			&i.IsGroup,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Position,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsInGroup = `-- name: ListLabelsInGroup :many
SELECT id, workspace_id, team_id, parent_id, is_group, name, description, color,
       position, archived_at, created_at, updated_at
FROM label
WHERE parent_id = $1 AND archived_at IS NULL
ORDER BY position
`

type ListLabelsInGroupRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	ParentID    *uuid.UUID
	IsGroup     bool
	Name        string
	Description *string
	Color       string
	Position    string
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListLabelsInGroup(ctx context.Context, parentID *uuid.UUID) ([]ListLabelsInGroupRow, error) {
	rows, err := q.db.Query(ctx, listLabelsInGroup, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsInGroupRow{}
	for rows.Next() {
		var i ListLabelsInGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.ParentID,
			&i.IsGroup,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Position,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsInWorkspace = `-- name: ListLabelsInWorkspace :many
SELECT id, workspace_id, team_id, parent_id, is_group, name, description, color,
       position, archived_at, created_at, updated_at
FROM label
WHERE workspace_id = $1 AND archived_at IS NULL
ORDER BY scope_key, position
`

type ListLabelsInWorkspaceRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	ParentID    *uuid.UUID
	IsGroup     bool
	Name        string
	Description *string
	Color       string
	Position    string
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// scope_key sorts workspace labels (the all-zero sentinel) ahead of every team's, so a
// single pass over this result renders the picker's sections in order.
func (q *Queries) ListLabelsInWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListLabelsInWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listLabelsInWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLabelsInWorkspaceRow{}
	for rows.Next() {
		var i ListLabelsInWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.ParentID,
			&i.IsGroup,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Position,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE label
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    color       = COALESCE($3, color),
    position    = COALESCE($4, position),
    is_group    = COALESCE($5, is_group),
    -- The group is three-state: absent (leave alone), moved into a group, or lifted out
    -- of one. Same shape as clear_assignee on issue, for the same reason — a plain
    -- COALESCE cannot say "clear".
    --
    -- Moving a label between groups rewrites issue_label.group_id by trigger, and that
    -- propagation can fail if an issue would end up holding two labels from one group.
    -- Letting it fail is deliberate: the alternative silently drops something a user
    -- applied by hand.
    parent_id   = CASE WHEN $6::boolean THEN NULL
                       ELSE COALESCE($7, parent_id) END
WHERE id = $8
RETURNING id, workspace_id, team_id, parent_id, is_group, name, description, color,
          position, archived_at, created_at, updated_at
`

type UpdateLabelParams struct {
	Name        *string
	Description *string
	Color       *string
	Position    *string
	IsGroup     *bool
	ClearParent bool
	ParentID    *uuid.UUID
	ID          uuid.UUID
}

type UpdateLabelRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	ParentID    *uuid.UUID
	IsGroup     bool
	Name        string
	Description *string
	Color       string
	Position    string
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (UpdateLabelRow, error) {
	row := q.db.QueryRow(ctx, updateLabel,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Position,
		arg.IsGroup,
		arg.ClearParent,
		arg.ParentID,
		arg.ID,
	)
	var i UpdateLabelRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.ParentID,
		&i.IsGroup,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Position,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
