// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           uuid.UUID
	Email        string
	PasswordHash *string
	// RESERVED, NEVER WRITTEN. No email-verification flow exists yet, so this is NULL for every account and NULL does not mean "unverified" — it means "unknown". Do not filter on it until something sets it.
	EmailVerifiedAt *time.Time
	DeletedAt       *time.Time
	LastLoginAt     *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AccountCredential struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	Kind       string
	ExternalID string
	Label      *string
	Data       json.RawMessage
	LastUsedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type AccountSession struct {
	ID         uuid.UUID
	AccountID  uuid.UUID
	TokenHash  []byte
	UserAgent  *string
	Ip         *netip.Addr
	Country    *string
	ExpiresAt  time.Time
	RevokedAt  *time.Time
	LastSeenAt time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type ApiKey struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Name        string
	TokenHash   []byte
	Prefix      string
	Scopes      []string
	LastUsedAt  *time.Time
	ExpiresAt   *time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Attachment struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	IssueID     uuid.UUID
	TeamID      uuid.UUID
	Url         string
	Title       string
	Subtitle    *string
	IconUrl     *string
	Metadata    json.RawMessage
	CreatorID   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ChangeLog struct {
	WorkspaceID   uuid.UUID
	Version       int64
	EntityType    string
	EntityID      uuid.UUID
	Op            string
	TeamID        *uuid.UUID
	Scope         json.RawMessage
	ActorType     string
	ActorID       *uuid.UUID
	Payload       []byte
	CreatedAt     time.Time
	ChangedFields []string
	BatchKey      *string
}

type ChangeLogDefault struct {
	WorkspaceID uuid.UUID
	Version     int64
	EntityType  string
	EntityID    uuid.UUID
	Op          string
	TeamID      *uuid.UUID
	Scope       json.RawMessage
	ActorType   string
	ActorID     *uuid.UUID
	Payload     []byte
	CreatedAt   time.Time
}

type Comment struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	IssueID     uuid.UUID
	ParentID    *uuid.UUID
	Body        string
	ActorType   string
	ActorID     *uuid.UUID
	EditedAt    *time.Time
	ResolvedAt  *time.Time
	ResolvedBy  *uuid.UUID
	ArchivedAt  *time.Time
	DeletedAt   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Cycle struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
	Number      int32
	Name        string
	Description *string
	StartsAt    time.Time
	EndsAt      time.Time
	CompletedAt *time.Time
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Document struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
	ProjectID   *uuid.UUID
	Title       string
	Body        string
	SortOrder   string
	CreatorID   *uuid.UUID
	UpdatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ArchivedAt  *time.Time
	DeletedAt   *time.Time
}

type Favorite struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Kind        string
	TargetID    uuid.UUID
	Position    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type FormTemplate struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	Name        string
	Description *string
	Properties  json.RawMessage
	Position    string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ArchivedAt  *time.Time
}

type FormTemplateField struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	FormTemplateID uuid.UUID
	FieldType      string
	Label          string
	Description    *string
	Required       bool
	SortOrder      string
	Config         json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type IdempotencyKey struct {
	ClientID    uuid.UUID
	OpID        uuid.UUID
	WorkspaceID uuid.UUID
	RequestHash []byte
	Result      json.RawMessage
	Version     *int64
	ExpiresAt   time.Time
	CreatedAt   time.Time
}

type Initiative struct {
	ID                    uuid.UUID
	WorkspaceID           uuid.UUID
	Name                  string
	Description           string
	Status                string
	Priority              int16
	OwnerID               *uuid.UUID
	LeadTeamID            *uuid.UUID
	CreatorID             *uuid.UUID
	SortOrder             string
	TargetDate            pgtype.Date
	TargetDateGranularity *string
	ArchivedAt            *time.Time
	DeletedAt             *time.Time
	DeletedBy             *uuid.UUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type InitiativeProject struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	InitiativeID uuid.UUID
	ProjectID    uuid.UUID
	CreatedAt    time.Time
}

type Invite struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	TokenHash   []byte
	InvitedBy   *uuid.UUID
	TeamIds     []uuid.UUID
	AcceptedAt  *time.Time
	AcceptedBy  *uuid.UUID
	RevokedAt   *time.Time
	ExpiresAt   time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Issue struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             uuid.UUID
	Number             int64
	Title              string
	Description        string
	StateID            uuid.UUID
	AssigneeID         *uuid.UUID
	CreatorID          *uuid.UUID
	Priority           int16
	SortOrder          string
	StartedAt          *time.Time
	CompletedAt        *time.Time
	CanceledAt         *time.Time
	ArchivedAt         *time.Time
	DeletedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Estimate           *int16
	DueDate            pgtype.Date
	DueDateSource      string
	ParentID           *uuid.UUID
	SubIssueSortOrder  *string
	TemplateID         *uuid.UUID
	DeletedBy          *uuid.UUID
	ProjectID          *uuid.UUID
	ProjectMilestoneID *uuid.UUID
	CycleID            *uuid.UUID
	SnoozedUntil       *time.Time
	AutoClosedAt       *time.Time
	FormTemplateID     *uuid.UUID
}

type IssueHistory struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	IssueID     uuid.UUID
	ActorType   string
	ActorID     *uuid.UUID
	Kind        string
	FromValue   []byte
	ToValue     []byte
	GroupedAt   *time.Time
	CreatedAt   time.Time
}

type IssueLabel struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	IssueID     uuid.UUID
	LabelID     uuid.UUID
	TeamID      uuid.UUID
	GroupID     *uuid.UUID
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
}

type IssueRelation struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	IssueID        uuid.UUID
	RelatedIssueID uuid.UUID
	Type           string
	TeamID         uuid.UUID
	RelatedTeamID  uuid.UUID
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
}

type IssueSubscription struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	IssueID      uuid.UUID
	UserID       uuid.UUID
	Reason       string
	Unsubscribed bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type IssueTemplate struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	Name        string
	Description *string
	Title       string
	Body        string
	Properties  json.RawMessage
	Position    string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ArchivedAt  *time.Time
}

type Label struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	ParentID    *uuid.UUID
	IsGroup     bool
	Name        string
	Description *string
	Color       string
	Position    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ArchivedAt  *time.Time
	ScopeKey    uuid.UUID
}

type Notification struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	Type          string
	IssueID       *uuid.UUID
	CommentID     *uuid.UUID
	ActorType     string
	ActorID       *uuid.UUID
	ChangeVersion int64
	GroupKey      string
	Count         int32
	Payload       []byte
	ReadAt        *time.Time
	SnoozedUntil  *time.Time
	DeletedAt     *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	EmailedAt     *time.Time
}

type NotificationCursor struct {
	WorkspaceID uuid.UUID
	Version     int64
	UpdatedAt   time.Time
}

type NotificationEmailCursor struct {
	UserID     uuid.UUID
	LastSentAt time.Time
}

type Project struct {
	ID                         uuid.UUID
	WorkspaceID                uuid.UUID
	Name                       string
	Summary                    *string
	Description                string
	Icon                       *string
	Color                      string
	StatusID                   uuid.UUID
	Priority                   int16
	LeadID                     *uuid.UUID
	CreatorID                  *uuid.UUID
	SortOrder                  string
	StartDate                  pgtype.Date
	StartDateGranularity       *string
	TargetDate                 pgtype.Date
	TargetDateGranularity      *string
	ArchivedAt                 *time.Time
	DeletedAt                  *time.Time
	DeletedBy                  *uuid.UUID
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	UpdateSchedule             string
	UpdateReminderIntervalDays *int16
	UpdateReminderWeekday      *int16
	UpdateReminderHour         *int16
	ProjectTemplateID          *uuid.UUID
}

type ProjectDependency struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	BlockingProjectID uuid.UUID
	BlockedProjectID  uuid.UUID
	CreatedAt         time.Time
}

type ProjectLabel struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ParentID    *uuid.UUID
	IsGroup     bool
	Name        string
	Description *string
	Color       string
	Position    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ArchivedAt  *time.Time
}

type ProjectLabelLink struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	LabelID     uuid.UUID
	GroupID     *uuid.UUID
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
}

type ProjectMember struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	UserID      uuid.UUID
	CreatedAt   time.Time
}

type ProjectMilestone struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Description *string
	TargetDate  pgtype.Date
	SortOrder   string
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProjectStatus struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Description *string
	Color       string
	Category    string
	Position    string
	IsDefault   bool
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProjectTeam struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	TeamID      uuid.UUID
	CreatedAt   time.Time
}

type ProjectTemplate struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	Name        string
	Description *string
	Summary     string
	Body        string
	Properties  json.RawMessage
	Position    string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ArchivedAt  *time.Time
}

type ProjectTemplateIssue struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ProjectTemplateID uuid.UUID
	ParentID          *uuid.UUID
	Title             string
	Description       string
	Properties        json.RawMessage
	SortOrder         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProjectTemplateMilestone struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ProjectTemplateID uuid.UUID
	Name              string
	Description       *string
	TargetDate        pgtype.Date
	SortOrder         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ProjectUpdate struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	Health      string
	Body        string
	AuthorID    uuid.UUID
	EditedAt    *time.Time
	DeletedAt   *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Team struct {
	ID                    uuid.UUID
	WorkspaceID           uuid.UUID
	Key                   string
	Name                  string
	Description           *string
	Icon                  *string
	Color                 *string
	Timezone              string
	ParentTeamID          *uuid.UUID
	Private               bool
	IssueCounter          int64
	Settings              json.RawMessage
	RetiredAt             *time.Time
	ArchivedAt            *time.Time
	DeletedAt             *time.Time
	CreatedAt             time.Time
	UpdatedAt             time.Time
	EstimateScale         string
	EstimateAllowZero     bool
	EstimateExtended      bool
	CyclesEnabled         bool
	CycleDurationWeeks    int16
	CycleCooldownWeeks    int16
	CycleStartDay         string
	CycleUpcomingCount    int16
	CycleAutoAddStarted   bool
	CycleAutoAddCompleted bool
	TriageEnabled         bool
	TriageRequirePriority bool
	AutoCloseDays         int16
	AutoArchiveDays       int16
	AutoCloseParent       bool
	AutoCloseChildren     bool
}

type TeamMembership struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
	UserID      uuid.UUID
	Role        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	AccountID         *uuid.UUID
	Name              string
	DisplayName       string
	AvatarUrl         *string
	Timezone          string
	Role              string
	Status            string
	Kind              string
	LastSeenAt        *time.Time
	ArchivedAt        *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	NotificationPrefs json.RawMessage
}

type View struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	OwnerID     *uuid.UUID
	Name        string
	Description *string
	Icon        *string
	Color       *string
	Filter      json.RawMessage
	Display     json.RawMessage
	Position    string
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ArchivedAt  *time.Time
	ProjectID   *uuid.UUID
}

type ViewPreference struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	ViewKey     string
	Display     json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Webhook struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	CreatorID           uuid.UUID
	Url                 string
	Secret              string
	Enabled             bool
	AllPublicTeams      bool
	TeamID              *uuid.UUID
	ResourceTypes       []string
	ConsecutiveFailures int32
	DisabledAt          *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type WebhookCursor struct {
	WorkspaceID uuid.UUID
	Version     int64
	UpdatedAt   time.Time
}

type WebhookDelivery struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	WebhookID      uuid.UUID
	ChangeVersion  int64
	EntityType     string
	EntityID       uuid.UUID
	Op             string
	Payload        json.RawMessage
	Attempt        int32
	NextAttemptAt  time.Time
	LastStatus     *int32
	LastError      *string
	LastDurationMs *int32
	LastSnippet    *string
	DeliveredAt    *time.Time
	CreatedAt      time.Time
}

type WorkflowState struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      uuid.UUID
	Name        string
	Description *string
	Color       string
	Category    string
	Position    string
	IsDefault   bool
	IsSystem    bool
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Workspace struct {
	ID                                uuid.UUID
	Name                              string
	UrlKey                            string
	LogoUrl                           *string
	Settings                          json.RawMessage
	Plan                              string
	ArchivedAt                        *time.Time
	DeletedAt                         *time.Time
	CreatedAt                         time.Time
	UpdatedAt                         time.Time
	PlanExpiresAt                     *time.Time
	SeatLimit                         *int32
	PlanLapsedAt                      *time.Time
	ProjectUpdateReminderIntervalDays int16
	ProjectUpdateReminderWeekday      int16
	ProjectUpdateReminderHour         int16
}

type WorkspaceVersion struct {
	WorkspaceID uuid.UUID
	Version     int64
}
