// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const advanceNotificationCursor = `-- name: AdvanceNotificationCursor :exec
INSERT INTO notification_cursor (workspace_id, version)
VALUES ($1, $2)
ON CONFLICT (workspace_id) DO UPDATE SET version = EXCLUDED.version
WHERE EXCLUDED.version > notification_cursor.version
`

type AdvanceNotificationCursorParams struct {
	WorkspaceID uuid.UUID
	Version     int64
}

// Advanced only after the batch's rows commit, so a crash re-processes rather than skips.
// The guard makes the advance monotonic: two workers racing on one workspace can otherwise
// rewind the watermark, and everything between the two positions is delivered twice.
func (q *Queries) AdvanceNotificationCursor(ctx context.Context, arg AdvanceNotificationCursorParams) error {
	_, err := q.db.Exec(ctx, advanceNotificationCursor, arg.WorkspaceID, arg.Version)
	return err
}

const advanceNotificationEmailCursor = `-- name: AdvanceNotificationEmailCursor :exec
INSERT INTO notification_email_cursor (user_id, last_sent_at)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET last_sent_at = EXCLUDED.last_sent_at
WHERE EXCLUDED.last_sent_at > notification_email_cursor.last_sent_at
`

type AdvanceNotificationEmailCursorParams struct {
	UserID uuid.UUID
	SentAt time.Time
}

// AdvanceNotificationEmailCursor records that a digest reached the relay.
//
// Written after the send and not before, so the cost of a crash is a pass that finds nothing
// to do rather than a person who hears nothing for a day. The guard makes it monotonic for
// the same reason AdvanceNotificationCursor's does: two workers racing must not be able to
// move a watermark backwards.
func (q *Queries) AdvanceNotificationEmailCursor(ctx context.Context, arg AdvanceNotificationEmailCursorParams) error {
	_, err := q.db.Exec(ctx, advanceNotificationEmailCursor, arg.UserID, arg.SentAt)
	return err
}

const claimNotificationsForEmail = `-- name: ClaimNotificationsForEmail :many
WITH due AS (
  SELECT p.id FROM notification p
  WHERE p.user_id = $1
    AND p.emailed_at IS NULL
    AND p.read_at IS NULL
    AND p.deleted_at IS NULL
    AND (p.snoozed_until IS NULL OR p.snoozed_until <= now())
  ORDER BY p.created_at
  LIMIT $2
  FOR UPDATE
), claimed AS (
  UPDATE notification n SET emailed_at = now()
  FROM due
  WHERE n.id = due.id AND n.emailed_at IS NULL
  RETURNING n.id, n.type, n.issue_id, n.count, n.created_at, n.emailed_at
)
SELECT c.id, c.type, c.issue_id, c.count, c.created_at, c.emailed_at,
       coalesce(i.title, '')::text  AS issue_title,
       coalesce(i.number, 0)::bigint AS issue_number,
       coalesce(t.key, '')::text    AS team_key
FROM claimed c
LEFT JOIN issue i ON i.id = c.issue_id
LEFT JOIN team t ON t.id = i.team_id
ORDER BY c.created_at
`

type ClaimNotificationsForEmailParams struct {
	UserID   uuid.UUID
	PageSize int32
}

type ClaimNotificationsForEmailRow struct {
	ID          uuid.UUID
	Type        string
	IssueID     *uuid.UUID
	Count       int32
	CreatedAt   time.Time
	EmailedAt   *time.Time
	IssueTitle  string
	IssueNumber int64
	TeamKey     string
}

// ClaimNotificationsForEmail takes ownership of one person's pending notifications and
// returns them with what the message has to say about each.
//
// One statement, and that is the point: the rows it describes are the rows it has just
// claimed. Reading first and marking afterwards would leave a window in which a second
// worker, or the same worker after a restart, reads the same rows and sends the same digest
// again — and an email, unlike an inbox row, cannot be folded into the one already there.
// The inner SELECT ... FOR UPDATE takes the locks in created_at order and the UPDATE
// re-checks emailed_at IS NULL under them, so a concurrent claim either waits and then
// matches nothing or is the one that matched: there is no interleaving in which both
// believe they own a row.
//
// The limit is a page and not a nicety. Somebody returning from three weeks off has an inbox
// of hundreds, and a digest that lists all of them is not read by anybody; the rest stay
// unclaimed and are the next pass's digest, which is also the honest thing to do with news
// that old.
//
// The joins are LEFT and coalesced. A notification whose issue has been deleted still has to
// be describable — the row is in somebody's inbox — and coalescing in SQL rather than
// leaving it to sqlc's nullability inference is deliberate: it does not infer nullability
// through an outer join, so an uncoalesced i.title would generate as a plain string and fail
// at scan time, at runtime, on the one row nobody has in their test fixture.
func (q *Queries) ClaimNotificationsForEmail(ctx context.Context, arg ClaimNotificationsForEmailParams) ([]ClaimNotificationsForEmailRow, error) {
	rows, err := q.db.Query(ctx, claimNotificationsForEmail, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimNotificationsForEmailRow{}
	for rows.Next() {
		var i ClaimNotificationsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.IssueID,
			&i.Count,
			&i.CreatedAt,
			&i.EmailedAt,
			&i.IssueTitle,
			&i.IssueNumber,
			&i.TeamKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notification
WHERE user_id = $1 AND read_at IS NULL AND deleted_at IS NULL AND snoozed_until IS NULL
`

// CountUnreadNotifications is the badge, read on every page load. It must stay on
// notification_unread_idx, which is why its predicate is that index's predicate verbatim.
func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNotification = `-- name: DeleteNotification :one
UPDATE notification SET deleted_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, workspace_id, user_id, type, issue_id, comment_id, actor_type, actor_id,
          change_version, group_key, count, payload, read_at, snoozed_until, deleted_at,
          created_at, updated_at, emailed_at
`

type DeleteNotificationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Soft, not a DELETE: the unique index on (user_id, group_key) is what makes the fan-out
// idempotent, and removing the row would let a replayed version deliver the notification a
// second time to somebody who had already dismissed it.
func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, deleteNotification, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Type,
		&i.IssueID,
		&i.CommentID,
		&i.ActorType,
		&i.ActorID,
		&i.ChangeVersion,
		&i.GroupKey,
		&i.Count,
		&i.Payload,
		&i.ReadAt,
		&i.SnoozedUntil,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailedAt,
	)
	return i, err
}

const ensureIssueSubscription = `-- name: EnsureIssueSubscription :one

INSERT INTO issue_subscription (id, workspace_id, issue_id, user_id, reason)
VALUES ($1, $2, $3, $4,
        $5)
ON CONFLICT (issue_id, user_id) DO UPDATE SET reason = issue_subscription.reason
RETURNING id, workspace_id, issue_id, user_id, reason, unsubscribed, created_at, updated_at
`

type EnsureIssueSubscriptionParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	IssueID     uuid.UUID
	UserID      uuid.UUID
	Reason      string
}

// ---------------------------------------------------------------------------------------
// Subscriptions.
// EnsureIssueSubscription is the automatic path: commenting on or being assigned an issue
// subscribes you to it.
//
// It must never touch `unsubscribed`. Resetting it here is the single most commonly
// rediscovered bug in notification systems: the user unsubscribes, the next comment
// re-subscribes them, and the button appears to work for about four minutes. The no-op
// update exists only so the existing row comes back, since the caller needs its id for the
// change stream.
func (q *Queries) EnsureIssueSubscription(ctx context.Context, arg EnsureIssueSubscriptionParams) (IssueSubscription, error) {
	row := q.db.QueryRow(ctx, ensureIssueSubscription,
		arg.ID,
		arg.WorkspaceID,
		arg.IssueID,
		arg.UserID,
		arg.Reason,
	)
	var i IssueSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.UserID,
		&i.Reason,
		&i.Unsubscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueSubscription = `-- name: GetIssueSubscription :one
SELECT id, workspace_id, issue_id, user_id, reason, unsubscribed, created_at, updated_at
FROM issue_subscription
WHERE issue_id = $1 AND user_id = $2
`

type GetIssueSubscriptionParams struct {
	IssueID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetIssueSubscription(ctx context.Context, arg GetIssueSubscriptionParams) (IssueSubscription, error) {
	row := q.db.QueryRow(ctx, getIssueSubscription, arg.IssueID, arg.UserID)
	var i IssueSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.UserID,
		&i.Reason,
		&i.Unsubscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, workspace_id, user_id, type, issue_id, comment_id, actor_type, actor_id,
       change_version, group_key, count, payload, read_at, snoozed_until, deleted_at,
       created_at, updated_at, emailed_at
FROM notification
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetNotificationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Type,
		&i.IssueID,
		&i.CommentID,
		&i.ActorType,
		&i.ActorID,
		&i.ChangeVersion,
		&i.GroupKey,
		&i.Count,
		&i.Payload,
		&i.ReadAt,
		&i.SnoozedUntil,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailedAt,
	)
	return i, err
}

const getNotificationCursor = `-- name: GetNotificationCursor :one

SELECT coalesce((SELECT version FROM notification_cursor WHERE workspace_id = $1), 0)::bigint
`

// ---------------------------------------------------------------------------------------
// The engine's watermark.
// Returns 0 for a workspace that has never been fanned out, which is the correct starting
// version and saves every caller a not-found branch that would otherwise be the difference
// between "start at the beginning" and "crash on first run".
func (q *Queries) GetNotificationCursor(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getNotificationCursor, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listDigestRecipients = `-- name: ListDigestRecipients :many

SELECT u.id AS user_id, u.workspace_id, u.display_name, u.notification_prefs,
       a.email AS email,
       w.name AS workspace_name,
       coalesce(c.last_sent_at, 'epoch'::timestamptz)::timestamptz AS last_sent_at,
       count(n.id)::bigint AS pending
FROM notification n
JOIN "user" u ON u.id = n.user_id
JOIN account a ON a.id = u.account_id
JOIN workspace w ON w.id = u.workspace_id
LEFT JOIN notification_email_cursor c ON c.user_id = u.id
WHERE n.emailed_at IS NULL
  AND n.read_at IS NULL
  AND n.deleted_at IS NULL
  AND (n.snoozed_until IS NULL OR n.snoozed_until <= now())
  AND u.archived_at IS NULL
  AND u.status = 'active'
  AND u.kind = 'human'
  AND a.deleted_at IS NULL
  -- Both sides are coalesced because an absent key is NULL, and NULL in a NOT (...) makes
  -- the whole row disappear: without the coalesce, somebody who has never opened the
  -- preferences screen is silently excluded from every digest the product ever sends.
  AND NOT (coalesce(u.notification_prefs->>'emailDigest', '') = 'off'
           AND coalesce(u.notification_prefs->>'emailPerNotification', '') <> 'true')
GROUP BY u.id, a.id, w.id, c.last_sent_at
ORDER BY u.id
LIMIT $1
`

type ListDigestRecipientsRow struct {
	UserID            uuid.UUID
	WorkspaceID       uuid.UUID
	DisplayName       string
	NotificationPrefs json.RawMessage
	Email             string
	WorkspaceName     string
	LastSentAt        time.Time
	Pending           int64
}

// ---------------------------------------------------------------------------------------
// Email delivery.
//
// Three statements, in the order the job runs them: find who has something waiting, claim
// it, and record that the message went out. The claim is the interesting one — see
// migration 000019 for why at-most-once is the right choice here and repeat-rather-than-lose
// is the right one for the fan-out.
// ListDigestRecipients is one row per person with unread, unsent notifications waiting.
//
// Grouped in SQL rather than in Go because the alternative is reading every pending
// notification in the install to bucket them by recipient, which is the whole table on the
// morning after a busy day. What the job needs per person is a count, an address and enough
// to decide whether they are due; the notifications themselves are read by the claim, one
// recipient at a time, and only for the ones that turn out to be due.
//
// The preferences bag comes back whole and is read in Go, the same way the fan-out reads it:
// cadence lives in jsonb precisely so that adding a delivery channel is not a migration, and
// a jsonb predicate for every cadence here would put half of that decision in SQL and half in
// Go.
//
// With one exception, which is about the page rather than about the preference. Somebody who
// has switched email off keeps their pending notifications forever — they are never claimed,
// because nothing is ever sent — so without this clause they hold a slot in every page of
// every pass, and an install where five hundred people have switched email off would never
// reach the five hundred and first person, who has not. The Go side still checks the cadence
// and is still the authority on it; this excludes only the one value that means "never", and
// only when per-notification email has not been asked for instead.
//
// Who is excluded, and why. An archived or suspended person no longer works here and their
// inbox is not their problem; an app user is an integration's identity and has no mailbox at
// all — the FK to account is NULL for them, so the inner join drops them anyway, and the
// explicit predicate says so rather than leaving it as a side effect somebody could "fix".
// A deleted account is somebody who asked to be forgotten, and continuing to mail them is
// the single most visible way to fail that request.
//
// Not excluded: an unverified address. Nothing in the product sets email_verified_at yet —
// there was no mail to verify with until this feature — so gating on it would make the
// digest a feature that silently never sends. Every address reached here was typed into an
// invitation by a workspace admin. Verification is the correct gate to add the day the
// verification mail itself exists, and this comment is where the next person should look.
//
// last_sent_at coalesces to epoch rather than coming back NULL: "never" and "long ago" are
// the same answer to the only question asked of it, and a pointer here would be a nil check
// at every call site that means nothing.
func (q *Queries) ListDigestRecipients(ctx context.Context, pageSize int32) ([]ListDigestRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listDigestRecipients, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDigestRecipientsRow{}
	for rows.Next() {
		var i ListDigestRecipientsRow
		if err := rows.Scan(
			&i.UserID,
			&i.WorkspaceID,
			&i.DisplayName,
			&i.NotificationPrefs,
			&i.Email,
			&i.WorkspaceName,
			&i.LastSentAt,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueSubscribers = `-- name: ListIssueSubscribers :many
SELECT id, workspace_id, issue_id, user_id, reason, unsubscribed, created_at, updated_at
FROM issue_subscription
WHERE issue_id = $1 AND unsubscribed = false
ORDER BY created_at
`

// ListIssueSubscribers is the fan-out's only read: who is watching this issue and still
// wants to hear. Matches issue_subscription_issue_idx, which is partial on the same
// predicate.
func (q *Queries) ListIssueSubscribers(ctx context.Context, issueID uuid.UUID) ([]IssueSubscription, error) {
	rows, err := q.db.Query(ctx, listIssueSubscribers, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueSubscription{}
	for rows.Next() {
		var i IssueSubscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.IssueID,
			&i.UserID,
			&i.Reason,
			&i.Unsubscribed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueSubscriptionsForIssues = `-- name: ListIssueSubscriptionsForIssues :many
SELECT s.id, s.workspace_id, s.issue_id, s.user_id, s.reason, s.unsubscribed,
       s.created_at, s.updated_at
FROM issue_subscription s
JOIN issue i ON i.id = s.issue_id
WHERE s.issue_id = ANY($1::uuid[])
  AND s.workspace_id = $2
  AND i.team_id = ANY($3::uuid[])
ORDER BY s.issue_id, s.created_at
`

type ListIssueSubscriptionsForIssuesParams struct {
	IssueIds    []uuid.UUID
	WorkspaceID uuid.UUID
	TeamIds     []uuid.UUID
}

// ListIssueSubscriptionsForIssues is the watcher list the issue panel renders, for a whole
// page of issues at once.
//
// Unsubscribed rows are returned, unlike ListIssueSubscribers above, and the difference is
// the caller: the fan-out wants people who still want to hear, while a reader wants to know
// whether *they* are watching — and an explicit unsubscribe is a row, not an absence, so
// dropping it would render the toggle as "not subscribed yet" and re-subscribe them on the
// next comment.
//
// The join is what enforces visibility: issue_subscription carries no team_id of its own,
// and without it naming an id would reveal who watches an issue in a team the caller is not
// in.
func (q *Queries) ListIssueSubscriptionsForIssues(ctx context.Context, arg ListIssueSubscriptionsForIssuesParams) ([]IssueSubscription, error) {
	rows, err := q.db.Query(ctx, listIssueSubscriptionsForIssues, arg.IssueIds, arg.WorkspaceID, arg.TeamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueSubscription{}
	for rows.Next() {
		var i IssueSubscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.IssueID,
			&i.UserID,
			&i.Reason,
			&i.Unsubscribed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueSubscriptionsForUser = `-- name: ListIssueSubscriptionsForUser :many
SELECT id, workspace_id, issue_id, user_id, reason, unsubscribed, created_at, updated_at
FROM issue_subscription
WHERE workspace_id = $1 AND user_id = $2
ORDER BY id
`

type ListIssueSubscriptionsForUserParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) ListIssueSubscriptionsForUser(ctx context.Context, arg ListIssueSubscriptionsForUserParams) ([]IssueSubscription, error) {
	rows, err := q.db.Query(ctx, listIssueSubscriptionsForUser, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueSubscription{}
	for rows.Next() {
		var i IssueSubscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.IssueID,
			&i.UserID,
			&i.Reason,
			&i.Unsubscribed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, workspace_id, user_id, type, issue_id, comment_id, actor_type, actor_id,
       change_version, group_key, count, payload, read_at, snoozed_until, deleted_at,
       created_at, updated_at, emailed_at
FROM notification
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::boolean OR read_at IS NULL)
  AND ($3::boolean OR snoozed_until IS NULL OR snoozed_until <= now())
ORDER BY created_at DESC
LIMIT $4
`

type ListNotificationsParams struct {
	UserID         uuid.UUID
	IncludeRead    bool
	IncludeSnoozed bool
	PageSize       int32
}

// ListNotifications is the inbox. The two flags are passed rather than compiled into
// separate queries so that "unread only" and "everything" cannot drift apart in what they
// consider deleted or snoozed.
//
// A snoozed row reappears on its own once snoozed_until passes, without anything having to
// sweep the table: the predicate is a comparison against now(), not a stored flag.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.IncludeRead,
		arg.IncludeSnoozed,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Type,
			&i.IssueID,
			&i.CommentID,
			&i.ActorType,
			&i.ActorID,
			&i.ChangeVersion,
			&i.GroupKey,
			&i.Count,
			&i.Payload,
			&i.ReadAt,
			&i.SnoozedUntil,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForIssue = `-- name: ListNotificationsForIssue :many
SELECT id, workspace_id, user_id, type, issue_id, comment_id, actor_type, actor_id,
       change_version, group_key, count, payload, read_at, snoozed_until, deleted_at,
       created_at, updated_at, emailed_at
FROM notification
WHERE issue_id = $1
  AND workspace_id = $2
  AND deleted_at IS NULL
ORDER BY id
`

type ListNotificationsForIssueParams struct {
	IssueID     *uuid.UUID
	WorkspaceID uuid.UUID
}

// ListNotificationsForIssue is every live inbox row about one issue, for every recipient.
//
// It exists for the restore, and it is the counterpart to StreamNotificationsForBootstrap
// above: a delete reaches clients as one change row for the issue and the client's cascade
// drops the notifications about it, so the restore owes them back or a replica that watched
// the undo ends up with an emptier inbox than one that bootstrapped a second later.
//
// Not scoped to a user, unlike everything else in this file, because the caller is not a
// recipient — it is republishing on behalf of all of them, and each row goes out under its
// own owner's scope. That is the same shape ListIssueSubscriptionsForIssues has for the same
// reason, and it is why this query returns user_id: the emitter needs it to address the
// change.
func (q *Queries) ListNotificationsForIssue(ctx context.Context, arg ListNotificationsForIssueParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForIssue, arg.IssueID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Type,
			&i.IssueID,
			&i.CommentID,
			&i.ActorType,
			&i.ActorID,
			&i.ChangeVersion,
			&i.GroupKey,
			&i.Count,
			&i.Payload,
			&i.ReadAt,
			&i.SnoozedUntil,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesWithPendingNotifications = `-- name: ListWorkspacesWithPendingNotifications :many
SELECT wv.workspace_id
FROM workspace_version wv
LEFT JOIN notification_cursor nc ON nc.workspace_id = wv.workspace_id
WHERE wv.version > coalesce(nc.version, 0)
`

// ListWorkspacesWithPendingNotifications drives the fan-out job, which like the retention
// sweep has no principal and therefore no workspace of its own to start from.
//
// Asking "where is there work" rather than iterating every workspace and discovering the
// answer per row: this runs on a short interval, and on an install where nobody is typing
// it has to cost one indexed comparison per workspace and no transaction at all.
//
// LEFT JOIN rather than a plain join, because a workspace has no cursor row until its first
// pass writes one — and a workspace that has never been fanned out is precisely the one with
// something waiting. Migration 000022 seeds a row for every workspace that existed before
// the job did, so `coalesce` here covers only the workspaces created since.
func (q *Queries) ListWorkspacesWithPendingNotifications(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWorkspacesWithPendingNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var workspace_id uuid.UUID
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :many
UPDATE notification SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL AND deleted_at IS NULL
RETURNING id, workspace_id, user_id, type, issue_id, comment_id, actor_type, actor_id,
          change_version, group_key, count, payload, read_at, snoozed_until, deleted_at,
          created_at, updated_at, emailed_at
`

// One statement for the whole inbox, and one version block for the sync stream. Marking a
// thousand rows read one at a time would mint a thousand versions and hold the workspace's
// row lock for the duration of all of them.
func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Type,
			&i.IssueID,
			&i.CommentID,
			&i.ActorType,
			&i.ActorID,
			&i.ChangeVersion,
			&i.GroupKey,
			&i.Count,
			&i.Payload,
			&i.ReadAt,
			&i.SnoozedUntil,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notification
SET read_at = CASE WHEN $1::boolean THEN now() ELSE NULL END
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
RETURNING id, workspace_id, user_id, type, issue_id, comment_id, actor_type, actor_id,
          change_version, group_key, count, payload, read_at, snoozed_until, deleted_at,
          created_at, updated_at, emailed_at
`

type MarkNotificationReadParams struct {
	Read   bool
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.Read, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Type,
		&i.IssueID,
		&i.CommentID,
		&i.ActorType,
		&i.ActorID,
		&i.ChangeVersion,
		&i.GroupKey,
		&i.Count,
		&i.Payload,
		&i.ReadAt,
		&i.SnoozedUntil,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailedAt,
	)
	return i, err
}

const releaseNotificationEmailClaim = `-- name: ReleaseNotificationEmailClaim :execrows
UPDATE notification SET emailed_at = NULL
WHERE id = ANY($1::uuid[]) AND emailed_at = $2
`

type ReleaseNotificationEmailClaimParams struct {
	Ids       []uuid.UUID
	ClaimedAt *time.Time
}

// ReleaseNotificationEmailClaim puts rows back when the relay refused the message.
//
// Claiming before sending is what makes a duplicate impossible; releasing on a refusal is
// what keeps that from also making an outage permanent. Without it, a relay that is down for
// an hour would silently swallow every digest due in that hour — the rows would be marked
// sent and never appear in another one.
//
// Guarded on the exact claim timestamp rather than on IS NOT NULL, so it can only ever undo
// the claim this pass made. A blanket clear would be a statement capable of resurrecting
// somebody else's delivery, sitting in the error path where it is least likely to be tested.
func (q *Queries) ReleaseNotificationEmailClaim(ctx context.Context, arg ReleaseNotificationEmailClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseNotificationEmailClaim, arg.Ids, arg.ClaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setIssueSubscription = `-- name: SetIssueSubscription :one
INSERT INTO issue_subscription (id, workspace_id, issue_id, user_id, reason, unsubscribed)
VALUES ($1, $2, $3, $4,
        'subscribed', $5)
ON CONFLICT (issue_id, user_id) DO UPDATE SET unsubscribed = EXCLUDED.unsubscribed
RETURNING id, workspace_id, issue_id, user_id, reason, unsubscribed, created_at, updated_at
`

type SetIssueSubscriptionParams struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	IssueID      uuid.UUID
	UserID       uuid.UUID
	Unsubscribed bool
}

// SetIssueSubscription is the button. This is the one place `unsubscribed` may change,
// because this is the one place the user said so.
func (q *Queries) SetIssueSubscription(ctx context.Context, arg SetIssueSubscriptionParams) (IssueSubscription, error) {
	row := q.db.QueryRow(ctx, setIssueSubscription,
		arg.ID,
		arg.WorkspaceID,
		arg.IssueID,
		arg.UserID,
		arg.Unsubscribed,
	)
	var i IssueSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.UserID,
		&i.Reason,
		&i.Unsubscribed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const snoozeNotification = `-- name: SnoozeNotification :one
UPDATE notification
SET snoozed_until = $1,
    read_at       = COALESCE(read_at, now())
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
RETURNING id, workspace_id, user_id, type, issue_id, comment_id, actor_type, actor_id,
          change_version, group_key, count, payload, read_at, snoozed_until, deleted_at,
          created_at, updated_at, emailed_at
`

type SnoozeNotificationParams struct {
	SnoozedUntil *time.Time
	ID           uuid.UUID
	UserID       uuid.UUID
}

// Snoozing also marks the row read. A notification you have chosen to defer is one you
// have seen, and leaving it in the unread count would make the badge argue with the inbox.
func (q *Queries) SnoozeNotification(ctx context.Context, arg SnoozeNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, snoozeNotification, arg.SnoozedUntil, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Type,
		&i.IssueID,
		&i.CommentID,
		&i.ActorType,
		&i.ActorID,
		&i.ChangeVersion,
		&i.GroupKey,
		&i.Count,
		&i.Payload,
		&i.ReadAt,
		&i.SnoozedUntil,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailedAt,
	)
	return i, err
}

const streamIssueSubscriptionsForBootstrap = `-- name: StreamIssueSubscriptionsForBootstrap :many
SELECT s.id, s.workspace_id, s.issue_id, s.user_id, s.reason, s.unsubscribed,
       s.created_at, s.updated_at
FROM issue_subscription s
JOIN issue i ON i.id = s.issue_id
WHERE s.workspace_id = $1
  AND s.user_id = $2
  AND i.team_id = ANY($3::uuid[])
  AND i.archived_at IS NULL
  AND i.deleted_at IS NULL
  AND s.id > $4
ORDER BY s.id
LIMIT $5
`

type StreamIssueSubscriptionsForBootstrapParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	TeamIds     []uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

// StreamIssueSubscriptionsForBootstrap feeds the initial snapshot with the caller's own
// subscriptions and nobody else's.
//
// That is the change scope, exactly: a subscription is emitted under the subscriber's user
// scope and under no team's, because who is watching what is nobody else's business — and a
// snapshot that shipped the whole watcher list would put one person's subscriptions in every
// teammate's replica, which is precisely what the emitter refuses to do.
//
// The issue is joined for the reason StreamIssueLabelsForBootstrap joins it: the snapshot
// must not carry rows hanging off issues it leaves out. A subscription is user-scoped, so
// nothing revokes it when its issue is archived — but the archive reaches clients as a delete
// for the issue and the client's cascade takes the subscription with it, so a snapshot that
// kept the row would disagree with every replica that watched it happen.
//
// Unsubscribed rows are shipped too. An explicit unsubscribe is a row rather than a missing
// one, and a replica without it renders the toggle as "not watching yet" and re-subscribes
// the user on the next comment — the four-minute unsubscribe button, arrived at from the
// replication side.
func (q *Queries) StreamIssueSubscriptionsForBootstrap(ctx context.Context, arg StreamIssueSubscriptionsForBootstrapParams) ([]IssueSubscription, error) {
	rows, err := q.db.Query(ctx, streamIssueSubscriptionsForBootstrap,
		arg.WorkspaceID,
		arg.UserID,
		arg.TeamIds,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueSubscription{}
	for rows.Next() {
		var i IssueSubscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.IssueID,
			&i.UserID,
			&i.Reason,
			&i.Unsubscribed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamNotificationsForBootstrap = `-- name: StreamNotificationsForBootstrap :many
SELECT n.id, n.workspace_id, n.user_id, n.type, n.issue_id, n.comment_id, n.actor_type,
       n.actor_id, n.change_version, n.group_key, n.count, n.payload, n.read_at,
       n.snoozed_until, n.deleted_at, n.created_at, n.updated_at, n.emailed_at
FROM notification n
WHERE n.workspace_id = $1
  AND n.user_id = $2
  AND n.deleted_at IS NULL
  AND (n.issue_id IS NULL OR EXISTS (
    SELECT 1 FROM issue i
    WHERE i.id = n.issue_id
      AND i.team_id = ANY($3::uuid[])
      AND i.archived_at IS NULL
      AND i.deleted_at IS NULL))
ORDER BY n.created_at DESC, n.id DESC
LIMIT $4
`

type StreamNotificationsForBootstrapParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	TeamIds     []uuid.UUID
	PageSize    int32
}

// StreamNotificationsForBootstrap ships the caller's inbox into the initial snapshot, and
// is the one stream in it with a ceiling.
//
// Volume is why. Every other table the snapshot walks is bounded by something a person
// maintains — a taxonomy, a sidebar, a backlog with archived work excluded — and this one is
// bounded by nothing: the fan-out writes a row per recipient per event, forever, so a
// two-year-old workspace's first load would carry the whole history of somebody's inbox
// before they could see a single issue. StreamCommentsForBootstrap states the same choice as
// a tier — the snapshot carries the recent end and the rest loads on demand — and this is
// that rule applied to the table that has no other end.
//
// The ceiling is the caller's page size and there is no cursor, deliberately: a statement
// that can never return more than the cap is already bounded, and a second page that cannot
// exist would be code with no caller. The number itself is domain.BootstrapNotificationLimit,
// which is where the product decision is written down.
//
// Newest first, which no other stream in the snapshot is. The cap has to keep the rows
// somebody would actually look at, and "the most recent N" is only expressible in the order
// the inbox renders in. Nothing else depends on the order: a notification is a leaf, so no
// client applying rows as they arrive can end up holding a dangling reference to one.
// created_at leads the sort so this stays on notification_inbox_idx; the id breaks ties,
// because rows written by one fan-out batch share a timestamp and an order that is not total
// is an order that silently drops rows at the cap boundary.
//
// Read and snoozed rows are both included. Marking read and snoozing are upserts on the
// change stream, so a replica that watched either happen still holds the row — the badge and
// the inbox are computed from it — and only a dismissal, which is emitted as a delete, takes
// it away.
//
// The join is on the issue and only on the issue, because that is what the client's cascade
// does: forgetting an issue forgets its notifications, and forgetting a comment does not.
func (q *Queries) StreamNotificationsForBootstrap(ctx context.Context, arg StreamNotificationsForBootstrapParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, streamNotificationsForBootstrap,
		arg.WorkspaceID,
		arg.UserID,
		arg.TeamIds,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Type,
			&i.IssueID,
			&i.CommentID,
			&i.ActorType,
			&i.ActorID,
			&i.ChangeVersion,
			&i.GroupKey,
			&i.Count,
			&i.Payload,
			&i.ReadAt,
			&i.SnoozedUntil,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotification = `-- name: UpsertNotification :one

INSERT INTO notification (id, workspace_id, user_id, type, issue_id, comment_id,
                          actor_type, actor_id, change_version, group_key, payload)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10,
        $11)
ON CONFLICT (user_id, group_key) DO UPDATE
SET count          = notification.count + 1,
    change_version = EXCLUDED.change_version,
    payload        = COALESCE(EXCLUDED.payload, notification.payload),
    read_at        = NULL
WHERE EXCLUDED.change_version > notification.change_version
RETURNING id, workspace_id, user_id, type, issue_id, comment_id, actor_type, actor_id,
          change_version, group_key, count, payload, read_at, snoozed_until, deleted_at,
          created_at, updated_at, emailed_at
`

type UpsertNotificationParams struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	Type          string
	IssueID       *uuid.UUID
	CommentID     *uuid.UUID
	ActorType     string
	ActorID       *uuid.UUID
	ChangeVersion int64
	GroupKey      string
	Payload       []byte
}

// The inbox, and the subscriptions that decide who gets one.
//
// Every query that touches a notification is scoped by user_id as well as by id. The id
// alone would be enough to find the row; requiring the recipient too means a mistaken or
// forged id can only ever act on the caller's own inbox, and the check cannot be forgotten
// at a call site because it is not at a call site.
// UpsertNotification is the fan-out's only write.
//
// The conflict target is (user_id, group_key), which is what collapses a bulk edit of two
// hundred issues into one inbox row carrying a count rather than two hundred rows. count
// is bumped, and read_at is cleared so that new activity re-surfaces a notification the
// user had already dismissed — that is the whole point of coalescing rather than
// appending. updated_at is not set here; notification_set_updated_at does it, and setting
// it twice would only invite the two to disagree.
//
// snoozed_until is deliberately left alone. A snooze is the user saying "not now", and
// more activity within the window is precisely the thing they asked not to be shown.
//
// The WHERE on the DO UPDATE is what keeps the engine re-runnable. A worker that crashes
// mid-batch restarts from the last committed cursor and re-processes versions it already
// fanned out; without the guard, every replay would inflate count and un-read rows the
// user had read. With it, a replay updates nothing and returns no row, so a caller that
// gets pgx.ErrNoRows has learnt "already delivered" and emits no change.
func (q *Queries) UpsertNotification(ctx context.Context, arg UpsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, upsertNotification,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Type,
		arg.IssueID,
		arg.CommentID,
		arg.ActorType,
		arg.ActorID,
		arg.ChangeVersion,
		arg.GroupKey,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Type,
		&i.IssueID,
		&i.CommentID,
		&i.ActorType,
		&i.ActorID,
		&i.ChangeVersion,
		&i.GroupKey,
		&i.Count,
		&i.Payload,
		&i.ReadAt,
		&i.SnoozedUntil,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailedAt,
	)
	return i, err
}
