// Package store owns database access. Only internal/domain may import it — see
// scripts/lint-imports.sh. Resolvers, the sync hub and job handlers reach the database
// exclusively through the domain layer, which is what guarantees that every write emits
// a change_log row.
//
// db.go, models.go, querier.go and *.sql.go in this package are generated by sqlc from
// migrations/ and queries/. This file is hand-written and holds the pool and the
// transaction helpers.
package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// DB is a connection pool plus the transaction helpers the domain layer uses.
type DB struct {
	pool *pgxpool.Pool
}

// PoolConfig mirrors the fields platform.Config exposes, kept as a separate struct so
// store does not import platform (and platform does not import store).
type PoolConfig struct {
	URL             string
	MaxConns        int32
	MinConns        int32
	MaxConnLifetime time.Duration
}

func Open(ctx context.Context, cfg PoolConfig) (*DB, error) {
	pc, err := pgxpool.ParseConfig(cfg.URL)
	if err != nil {
		return nil, fmt.Errorf("parse database url: %w", err)
	}
	if cfg.MaxConns > 0 {
		pc.MaxConns = cfg.MaxConns
	}
	if cfg.MinConns > 0 {
		pc.MinConns = cfg.MinConns
	}
	if cfg.MaxConnLifetime > 0 {
		pc.MaxConnLifetime = cfg.MaxConnLifetime
	}

	// pgbouncer runs in transaction mode in production, where server-side prepared
	// statements are not safe across pooled connections. Describing statements on every
	// execution costs a round trip but is the only correct setting behind a transaction
	// pooler, and getting this wrong produces "prepared statement already exists" errors
	// that only surface under concurrency, in production.
	pc.ConnConfig.DefaultQueryExecMode = pgx.QueryExecModeDescribeExec

	pool, err := pgxpool.NewWithConfig(ctx, pc)
	if err != nil {
		return nil, fmt.Errorf("open pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping database: %w", err)
	}
	return &DB{pool: pool}, nil
}

func (db *DB) Close() { db.pool.Close() }

func (db *DB) Pool() *pgxpool.Pool { return db.pool }

// Queries returns the generated query set bound to the pool, for reads outside a
// transaction.
func (db *DB) Queries() *Queries { return New(db.pool) }

// Ping reports whether the database is reachable. Used by /healthz.
func (db *DB) Ping(ctx context.Context) error { return db.pool.Ping(ctx) }

// InTx runs fn inside a transaction and commits if it returns nil.
//
// Every mutation in the product goes through this: the entity write, the workspace
// version bump, the change_log append and the activity-feed row must be one atomic unit.
// If they are not, a client can receive a delta for a row that was rolled back.
func (db *DB) InTx(ctx context.Context, fn func(ctx context.Context, q *Queries) error) error {
	tx, err := db.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin: %w", err)
	}
	// Rollback after a successful commit is a no-op returning ErrTxClosed, so this is
	// safe unconditionally and guarantees no connection leaks on a panic.
	defer func() { _ = tx.Rollback(ctx) }()

	if err := fn(ctx, New(tx)); err != nil {
		return err
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit: %w", err)
	}
	return nil
}

// InReadOnlyTx runs fn at REPEATABLE READ, read-only. Used by the bootstrap snapshot,
// which must stream a consistent view of a workspace while writes continue.
func (db *DB) InReadOnlyTx(ctx context.Context, fn func(ctx context.Context, q *Queries) error) error {
	tx, err := db.pool.BeginTx(ctx, pgx.TxOptions{
		IsoLevel:   pgx.RepeatableRead,
		AccessMode: pgx.ReadOnly,
	})
	if err != nil {
		return fmt.Errorf("begin repeatable read: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }()

	if err := fn(ctx, New(tx)); err != nil {
		return err
	}
	return tx.Commit(ctx)
}

// IsNotFound reports whether err is pgx's no-rows sentinel.
func IsNotFound(err error) bool { return errors.Is(err, pgx.ErrNoRows) }

// IsUniqueViolation reports whether err is a unique constraint failure, optionally
// narrowed to a named constraint. Callers use the constraint name to turn a lost race
// into a precise validation message ("that team key is taken") instead of a generic
// conflict.
func IsUniqueViolation(err error, constraint string) bool {
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) || pgErr.Code != "23505" {
		return false
	}
	return constraint == "" || pgErr.ConstraintName == constraint
}

// IsForeignKeyViolation reports whether err is a foreign key failure.
func IsForeignKeyViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23503"
}

// IsCheckViolation reports whether err is a CHECK constraint failure. These indicate a
// domain-layer bug: validation should have caught it before the write.
func IsCheckViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23514"
}

// IsRaisedException reports whether err came from a PL/pgSQL RAISE EXCEPTION — a trigger
// refusing a write rather than a constraint doing it.
//
// Constraints carry a name the caller can match on; a RAISE carries neither name nor a
// specific code, so this is the only handle the domain layer has on the invariants that are
// too structural to express as a CHECK. The parent-cycle guard is the one that exists
// today, and without this its refusal arrives as an unclassified error — meaning somebody
// who has just dragged an issue underneath its own sub-issue is told "internal error"
// rather than what they did.
func IsRaisedException(err error) bool {
	var pgErr *pgconn.PgError
	// P0001 is raise_exception: what RAISE EXCEPTION produces when no ERRCODE is given.
	return errors.As(err, &pgErr) && pgErr.Code == "P0001"
}

// IsSerializationFailure reports whether err is a serialization or deadlock failure and
// is therefore safe to retry.
func IsSerializationFailure(err error) bool {
	var pgErr *pgconn.PgError
	if !errors.As(err, &pgErr) {
		return false
	}
	return pgErr.Code == "40001" || pgErr.Code == "40P01"
}
