// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :one

INSERT INTO project_member (id, workspace_id, project_id, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, project_id, user_id, created_at
`

type AddProjectMemberParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	UserID      uuid.UUID
}

// ---------------------------------------------------------------------------------------
// project_member
func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.UserID,
	)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const addProjectTeam = `-- name: AddProjectTeam :one

INSERT INTO project_team (id, workspace_id, project_id, team_id)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, project_id, team_id, created_at
`

type AddProjectTeamParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	TeamID      uuid.UUID
}

// ---------------------------------------------------------------------------------------
// project_team
func (q *Queries) AddProjectTeam(ctx context.Context, arg AddProjectTeamParams) (ProjectTeam, error) {
	row := q.db.QueryRow(ctx, addProjectTeam,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TeamID,
	)
	var i ProjectTeam
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}

const archiveProjectMilestone = `-- name: ArchiveProjectMilestone :exec
UPDATE project_milestone SET archived_at = now() WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveProjectMilestone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveProjectMilestone, id)
	return err
}

const archiveProjectStatus = `-- name: ArchiveProjectStatus :exec
UPDATE project_status SET archived_at = now() WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) ArchiveProjectStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveProjectStatus, id)
	return err
}

const clearDefaultProjectStatuses = `-- name: ClearDefaultProjectStatuses :exec
UPDATE project_status SET is_default = false
WHERE workspace_id = $1 AND is_default AND id <> $2
`

type ClearDefaultProjectStatusesParams struct {
	WorkspaceID uuid.UUID
	ExceptID    uuid.UUID
}

func (q *Queries) ClearDefaultProjectStatuses(ctx context.Context, arg ClearDefaultProjectStatusesParams) error {
	_, err := q.db.Exec(ctx, clearDefaultProjectStatuses, arg.WorkspaceID, arg.ExceptID)
	return err
}

const countProjectTeams = `-- name: CountProjectTeams :one
SELECT count(*) FROM project_team WHERE project_id = $1
`

func (q *Queries) CountProjectTeams(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectTeams, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one

INSERT INTO project (id, workspace_id, name, summary, description, icon, color,
                     status_id, priority, lead_id, creator_id, sort_order,
                     start_date, start_date_granularity, target_date, target_date_granularity)
VALUES ($1, $2, $3, $4,
        COALESCE($5, ''), $6,
        COALESCE($7::text, '#6b7280'),
        $8, $9, $10, $11,
        $12,
        $13, $14,
        $15, $16)
RETURNING id, workspace_id, name, summary, description, icon, color,
          status_id, priority, lead_id, creator_id, sort_order,
          start_date, start_date_granularity, target_date, target_date_granularity,
          archived_at, deleted_at, deleted_by, created_at, updated_at
`

type CreateProjectParams struct {
	ID                    uuid.UUID
	WorkspaceID           uuid.UUID
	Name                  string
	Summary               *string
	Description           interface{}
	Icon                  *string
	Color                 *string
	StatusID              uuid.UUID
	Priority              int16
	LeadID                *uuid.UUID
	CreatorID             *uuid.UUID
	SortOrder             string
	StartDate             pgtype.Date
	StartDateGranularity  *string
	TargetDate            pgtype.Date
	TargetDateGranularity *string
}

// ---------------------------------------------------------------------------------------
// project
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Summary,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.StatusID,
		arg.Priority,
		arg.LeadID,
		arg.CreatorID,
		arg.SortOrder,
		arg.StartDate,
		arg.StartDateGranularity,
		arg.TargetDate,
		arg.TargetDateGranularity,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.StatusID,
		&i.Priority,
		&i.LeadID,
		&i.CreatorID,
		&i.SortOrder,
		&i.StartDate,
		&i.StartDateGranularity,
		&i.TargetDate,
		&i.TargetDateGranularity,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectMilestone = `-- name: CreateProjectMilestone :one

INSERT INTO project_milestone (id, workspace_id, project_id, name, description, target_date, sort_order)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
RETURNING id, workspace_id, project_id, name, description, target_date, sort_order,
          archived_at, created_at, updated_at
`

type CreateProjectMilestoneParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ProjectID   uuid.UUID
	Name        string
	Description *string
	TargetDate  pgtype.Date
	SortOrder   string
}

// ---------------------------------------------------------------------------------------
// project_milestone
func (q *Queries) CreateProjectMilestone(ctx context.Context, arg CreateProjectMilestoneParams) (ProjectMilestone, error) {
	row := q.db.QueryRow(ctx, createProjectMilestone,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.TargetDate,
		arg.SortOrder,
	)
	var i ProjectMilestone
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.TargetDate,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectStatus = `-- name: CreateProjectStatus :one


INSERT INTO project_status (id, workspace_id, name, description, color, category, position, is_default)
VALUES ($1, $2, $3, $4,
        COALESCE($5::text, '#6b7280'),
        $6, $7, $8)
RETURNING id, workspace_id, name, description, color, category, position, is_default,
          archived_at, created_at, updated_at
`

type CreateProjectStatusParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Description *string
	Color       *string
	Category    string
	Position    string
	IsDefault   bool
}

// Projects and the four entity types that hang off them.
//
// Every SELECT lists columns in the table's own order, same rule as issues.sql: a new
// column lands at the end, and so does its addition here.
// ---------------------------------------------------------------------------------------
// project_status
func (q *Queries) CreateProjectStatus(ctx context.Context, arg CreateProjectStatusParams) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, createProjectStatus,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Category,
		arg.Position,
		arg.IsDefault,
	)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Category,
		&i.Position,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultProjectStatus = `-- name: GetDefaultProjectStatus :one
SELECT id, workspace_id, name, description, color, category, position, is_default,
       archived_at, created_at, updated_at
FROM project_status
WHERE workspace_id = $1 AND is_default AND archived_at IS NULL
`

func (q *Queries) GetDefaultProjectStatus(ctx context.Context, workspaceID uuid.UUID) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, getDefaultProjectStatus, workspaceID)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Category,
		&i.Position,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, name, summary, description, icon, color,
       status_id, priority, lead_id, creator_id, sort_order,
       start_date, start_date_granularity, target_date, target_date_granularity,
       archived_at, deleted_at, deleted_by, created_at, updated_at
FROM project
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.StatusID,
		&i.Priority,
		&i.LeadID,
		&i.CreatorID,
		&i.SortOrder,
		&i.StartDate,
		&i.StartDateGranularity,
		&i.TargetDate,
		&i.TargetDateGranularity,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForUpdate = `-- name: GetProjectForUpdate :one
SELECT id, workspace_id, name, summary, description, icon, color,
       status_id, priority, lead_id, creator_id, sort_order,
       start_date, start_date_granularity, target_date, target_date_granularity,
       archived_at, deleted_at, deleted_by, created_at, updated_at
FROM project
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// GetProjectForUpdate locks the row so concurrent team/member edits cannot interleave
// with a delete, and so a restore reads the same snapshot it writes.
func (q *Queries) GetProjectForUpdate(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForUpdate, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.StatusID,
		&i.Priority,
		&i.LeadID,
		&i.CreatorID,
		&i.SortOrder,
		&i.StartDate,
		&i.StartDateGranularity,
		&i.TargetDate,
		&i.TargetDateGranularity,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectIncludingDeleted = `-- name: GetProjectIncludingDeleted :one
SELECT id, workspace_id, name, summary, description, icon, color,
       status_id, priority, lead_id, creator_id, sort_order,
       start_date, start_date_granularity, target_date, target_date_granularity,
       archived_at, deleted_at, deleted_by, created_at, updated_at
FROM project
WHERE id = $1
FOR UPDATE
`

// GetProjectIncludingDeleted is the restore path: a live GetProject would 404 the trash.
func (q *Queries) GetProjectIncludingDeleted(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectIncludingDeleted, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.StatusID,
		&i.Priority,
		&i.LeadID,
		&i.CreatorID,
		&i.SortOrder,
		&i.StartDate,
		&i.StartDateGranularity,
		&i.TargetDate,
		&i.TargetDateGranularity,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT id, workspace_id, project_id, user_id, created_at
FROM project_member
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectMilestone = `-- name: GetProjectMilestone :one
SELECT id, workspace_id, project_id, name, description, target_date, sort_order,
       archived_at, created_at, updated_at
FROM project_milestone
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetProjectMilestone(ctx context.Context, id uuid.UUID) (ProjectMilestone, error) {
	row := q.db.QueryRow(ctx, getProjectMilestone, id)
	var i ProjectMilestone
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.TargetDate,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectStatus = `-- name: GetProjectStatus :one
SELECT id, workspace_id, name, description, color, category, position, is_default,
       archived_at, created_at, updated_at
FROM project_status
WHERE id = $1
`

func (q *Queries) GetProjectStatus(ctx context.Context, id uuid.UUID) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, getProjectStatus, id)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Category,
		&i.Position,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectTeam = `-- name: GetProjectTeam :one
SELECT id, workspace_id, project_id, team_id, created_at
FROM project_team
WHERE project_id = $1 AND team_id = $2
`

type GetProjectTeamParams struct {
	ProjectID uuid.UUID
	TeamID    uuid.UUID
}

func (q *Queries) GetProjectTeam(ctx context.Context, arg GetProjectTeamParams) (ProjectTeam, error) {
	row := q.db.QueryRow(ctx, getProjectTeam, arg.ProjectID, arg.TeamID)
	var i ProjectTeam
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TeamID,
		&i.CreatedAt,
	)
	return i, err
}

const lastProjectMilestoneSortOrder = `-- name: LastProjectMilestoneSortOrder :one
SELECT sort_order FROM project_milestone
WHERE project_id = $1 AND archived_at IS NULL
ORDER BY sort_order DESC
LIMIT 1
`

func (q *Queries) LastProjectMilestoneSortOrder(ctx context.Context, projectID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lastProjectMilestoneSortOrder, projectID)
	var sort_order string
	err := row.Scan(&sort_order)
	return sort_order, err
}

const lastProjectSortOrder = `-- name: LastProjectSortOrder :one
SELECT sort_order FROM project
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY sort_order DESC
LIMIT 1
`

func (q *Queries) LastProjectSortOrder(ctx context.Context, workspaceID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lastProjectSortOrder, workspaceID)
	var sort_order string
	err := row.Scan(&sort_order)
	return sort_order, err
}

const lastProjectStatusPosition = `-- name: LastProjectStatusPosition :one
SELECT position FROM project_status
WHERE workspace_id = $1 AND archived_at IS NULL
ORDER BY position DESC
LIMIT 1
`

func (q *Queries) LastProjectStatusPosition(ctx context.Context, workspaceID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lastProjectStatusPosition, workspaceID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const listDeletedProjects = `-- name: ListDeletedProjects :many
SELECT id, workspace_id, name, summary, description, icon, color,
       status_id, priority, lead_id, creator_id, sort_order,
       start_date, start_date_granularity, target_date, target_date_granularity,
       archived_at, deleted_at, deleted_by, created_at, updated_at
FROM project
WHERE workspace_id = $1
  AND deleted_at IS NOT NULL
  AND deleted_at > $2
ORDER BY deleted_at DESC
`

type ListDeletedProjectsParams struct {
	WorkspaceID  uuid.UUID
	DeletedAfter *time.Time
}

func (q *Queries) ListDeletedProjects(ctx context.Context, arg ListDeletedProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listDeletedProjects, arg.WorkspaceID, arg.DeletedAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Summary,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.StatusID,
			&i.Priority,
			&i.LeadID,
			&i.CreatorID,
			&i.SortOrder,
			&i.StartDate,
			&i.StartDateGranularity,
			&i.TargetDate,
			&i.TargetDateGranularity,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT id, workspace_id, project_id, user_id, created_at
FROM project_member
WHERE project_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMilestones = `-- name: ListProjectMilestones :many
SELECT id, workspace_id, project_id, name, description, target_date, sort_order,
       archived_at, created_at, updated_at
FROM project_milestone
WHERE project_id = $1 AND archived_at IS NULL
ORDER BY sort_order
`

func (q *Queries) ListProjectMilestones(ctx context.Context, projectID uuid.UUID) ([]ProjectMilestone, error) {
	rows, err := q.db.Query(ctx, listProjectMilestones, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMilestone{}
	for rows.Next() {
		var i ProjectMilestone
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.TargetDate,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectStatuses = `-- name: ListProjectStatuses :many
SELECT id, workspace_id, name, description, color, category, position, is_default,
       archived_at, created_at, updated_at
FROM project_status
WHERE workspace_id = $1 AND archived_at IS NULL
ORDER BY position
`

func (q *Queries) ListProjectStatuses(ctx context.Context, workspaceID uuid.UUID) ([]ProjectStatus, error) {
	rows, err := q.db.Query(ctx, listProjectStatuses, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectStatus{}
	for rows.Next() {
		var i ProjectStatus
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Category,
			&i.Position,
			&i.IsDefault,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTeamIDs = `-- name: ListProjectTeamIDs :many
SELECT team_id FROM project_team WHERE project_id = $1 ORDER BY team_id
`

func (q *Queries) ListProjectTeamIDs(ctx context.Context, projectID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listProjectTeamIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var team_id uuid.UUID
		if err := rows.Scan(&team_id); err != nil {
			return nil, err
		}
		items = append(items, team_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTeams = `-- name: ListProjectTeams :many
SELECT id, workspace_id, project_id, team_id, created_at
FROM project_team
WHERE project_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListProjectTeams(ctx context.Context, projectID uuid.UUID) ([]ProjectTeam, error) {
	rows, err := q.db.Query(ctx, listProjectTeams, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTeam{}
	for rows.Next() {
		var i ProjectTeam
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TeamID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsInWorkspace = `-- name: ListProjectsInWorkspace :many
SELECT id, workspace_id, name, summary, description, icon, color,
       status_id, priority, lead_id, creator_id, sort_order,
       start_date, start_date_granularity, target_date, target_date_granularity,
       archived_at, deleted_at, deleted_by, created_at, updated_at
FROM project
WHERE workspace_id = $1 AND deleted_at IS NULL AND archived_at IS NULL
ORDER BY sort_order
`

func (q *Queries) ListProjectsInWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsInWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Summary,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.StatusID,
			&i.Priority,
			&i.LeadID,
			&i.CreatorID,
			&i.SortOrder,
			&i.StartDate,
			&i.StartDateGranularity,
			&i.TargetDate,
			&i.TargetDateGranularity,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :execrows
DELETE FROM project_member
WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeProjectTeam = `-- name: RemoveProjectTeam :execrows
DELETE FROM project_team
WHERE project_id = $1 AND team_id = $2
`

type RemoveProjectTeamParams struct {
	ProjectID uuid.UUID
	TeamID    uuid.UUID
}

func (q *Queries) RemoveProjectTeam(ctx context.Context, arg RemoveProjectTeamParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeProjectTeam, arg.ProjectID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreProject = `-- name: RestoreProject :one
UPDATE project SET deleted_at = NULL, deleted_by = NULL
WHERE id = $1 AND deleted_at IS NOT NULL AND deleted_at > $2
RETURNING id, workspace_id, name, summary, description, icon, color,
          status_id, priority, lead_id, creator_id, sort_order,
          start_date, start_date_granularity, target_date, target_date_granularity,
          archived_at, deleted_at, deleted_by, created_at, updated_at
`

type RestoreProjectParams struct {
	ID           uuid.UUID
	DeletedAfter *time.Time
}

func (q *Queries) RestoreProject(ctx context.Context, arg RestoreProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, restoreProject, arg.ID, arg.DeletedAfter)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.StatusID,
		&i.Priority,
		&i.LeadID,
		&i.CreatorID,
		&i.SortOrder,
		&i.StartDate,
		&i.StartDateGranularity,
		&i.TargetDate,
		&i.TargetDateGranularity,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE project SET deleted_at = now(), deleted_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type SoftDeleteProjectParams struct {
	DeletedBy *uuid.UUID
	ID        uuid.UUID
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error {
	_, err := q.db.Exec(ctx, softDeleteProject, arg.DeletedBy, arg.ID)
	return err
}

const streamProjectMembersForBootstrap = `-- name: StreamProjectMembersForBootstrap :many
SELECT pm.id, pm.workspace_id, pm.project_id, pm.user_id, pm.created_at
FROM project_member pm
WHERE pm.workspace_id = $1
  AND EXISTS (
        SELECT 1 FROM project_team visible
        WHERE visible.project_id = pm.project_id
          AND visible.team_id = ANY($2::uuid[])
      )
  AND pm.id > $3
ORDER BY pm.id
LIMIT $4
`

type StreamProjectMembersForBootstrapParams struct {
	WorkspaceID uuid.UUID
	TeamIds     []uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

func (q *Queries) StreamProjectMembersForBootstrap(ctx context.Context, arg StreamProjectMembersForBootstrapParams) ([]ProjectMember, error) {
	rows, err := q.db.Query(ctx, streamProjectMembersForBootstrap,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamProjectMilestonesForBootstrap = `-- name: StreamProjectMilestonesForBootstrap :many
SELECT m.id, m.workspace_id, m.project_id, m.name, m.description, m.target_date, m.sort_order,
       m.archived_at, m.created_at, m.updated_at
FROM project_milestone m
WHERE m.workspace_id = $1
  AND m.archived_at IS NULL
  AND EXISTS (
        SELECT 1 FROM project_team visible
        WHERE visible.project_id = m.project_id
          AND visible.team_id = ANY($2::uuid[])
      )
  AND m.id > $3
ORDER BY m.id
LIMIT $4
`

type StreamProjectMilestonesForBootstrapParams struct {
	WorkspaceID uuid.UUID
	TeamIds     []uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

func (q *Queries) StreamProjectMilestonesForBootstrap(ctx context.Context, arg StreamProjectMilestonesForBootstrapParams) ([]ProjectMilestone, error) {
	rows, err := q.db.Query(ctx, streamProjectMilestonesForBootstrap,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMilestone{}
	for rows.Next() {
		var i ProjectMilestone
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.TargetDate,
			&i.SortOrder,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamProjectStatusesForBootstrap = `-- name: StreamProjectStatusesForBootstrap :many
SELECT id, workspace_id, name, description, color, category, position, is_default,
       archived_at, created_at, updated_at
FROM project_status
WHERE workspace_id = $1
  AND archived_at IS NULL
  AND $2::boolean
  AND id > $3
ORDER BY id
LIMIT $4
`

type StreamProjectStatusesForBootstrapParams struct {
	WorkspaceID            uuid.UUID
	IncludeWorkspaceScoped bool
	AfterID                uuid.UUID
	PageSize               int32
}

func (q *Queries) StreamProjectStatusesForBootstrap(ctx context.Context, arg StreamProjectStatusesForBootstrapParams) ([]ProjectStatus, error) {
	rows, err := q.db.Query(ctx, streamProjectStatusesForBootstrap,
		arg.WorkspaceID,
		arg.IncludeWorkspaceScoped,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectStatus{}
	for rows.Next() {
		var i ProjectStatus
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Category,
			&i.Position,
			&i.IsDefault,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamProjectTeamsForBootstrap = `-- name: StreamProjectTeamsForBootstrap :many
SELECT pt.id, pt.workspace_id, pt.project_id, pt.team_id, pt.created_at
FROM project_team pt
WHERE pt.workspace_id = $1
  AND EXISTS (
        SELECT 1 FROM project_team visible
        WHERE visible.project_id = pt.project_id
          AND visible.team_id = ANY($2::uuid[])
      )
  AND pt.id > $3
ORDER BY pt.id
LIMIT $4
`

type StreamProjectTeamsForBootstrapParams struct {
	WorkspaceID uuid.UUID
	TeamIds     []uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

// StreamProjectTeamsForBootstrap follows the parent project's visibility.
func (q *Queries) StreamProjectTeamsForBootstrap(ctx context.Context, arg StreamProjectTeamsForBootstrapParams) ([]ProjectTeam, error) {
	rows, err := q.db.Query(ctx, streamProjectTeamsForBootstrap,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectTeam{}
	for rows.Next() {
		var i ProjectTeam
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TeamID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamProjectsForBootstrap = `-- name: StreamProjectsForBootstrap :many
SELECT p.id, p.workspace_id, p.name, p.summary, p.description, p.icon, p.color,
       p.status_id, p.priority, p.lead_id, p.creator_id, p.sort_order,
       p.start_date, p.start_date_granularity, p.target_date, p.target_date_granularity,
       p.archived_at, p.deleted_at, p.deleted_by, p.created_at, p.updated_at
FROM project p
WHERE p.workspace_id = $1
  AND p.deleted_at IS NULL
  AND EXISTS (
        SELECT 1 FROM project_team pt
        WHERE pt.project_id = p.id AND pt.team_id = ANY($2::uuid[])
      )
  AND p.id > $3
ORDER BY p.id
LIMIT $4
`

type StreamProjectsForBootstrapParams struct {
	WorkspaceID uuid.UUID
	TeamIds     []uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

// StreamProjectsForBootstrap: a project is visible if the principal is in any of its
// teams — the same predicate authz.Visible uses for ScopeProject.
func (q *Queries) StreamProjectsForBootstrap(ctx context.Context, arg StreamProjectsForBootstrapParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, streamProjectsForBootstrap,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Summary,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.StatusID,
			&i.Priority,
			&i.LeadID,
			&i.CreatorID,
			&i.SortOrder,
			&i.StartDate,
			&i.StartDateGranularity,
			&i.TargetDate,
			&i.TargetDateGranularity,
			&i.ArchivedAt,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveProjectStatus = `-- name: UnarchiveProjectStatus :exec
UPDATE project_status SET archived_at = NULL WHERE id = $1
`

func (q *Queries) UnarchiveProjectStatus(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unarchiveProjectStatus, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE project
SET name                     = COALESCE($1, name),
    summary                  = COALESCE($2, summary),
    description              = COALESCE($3, description),
    icon                     = COALESCE($4, icon),
    color                    = COALESCE($5, color),
    status_id                = COALESCE($6, status_id),
    priority                 = COALESCE($7, priority),
    sort_order               = COALESCE($8, sort_order),
    start_date               = CASE WHEN $9::boolean THEN NULL
                                    ELSE COALESCE($10, start_date) END,
    start_date_granularity   = CASE WHEN $9::boolean THEN NULL
                                    ELSE COALESCE($11, start_date_granularity) END,
    target_date              = CASE WHEN $12::boolean THEN NULL
                                    ELSE COALESCE($13, target_date) END,
    target_date_granularity  = CASE WHEN $12::boolean THEN NULL
                                    ELSE COALESCE($14, target_date_granularity) END,
    lead_id = CASE WHEN $15::boolean THEN NULL
                   ELSE COALESCE($16, lead_id) END
WHERE id = $17 AND deleted_at IS NULL
RETURNING id, workspace_id, name, summary, description, icon, color,
          status_id, priority, lead_id, creator_id, sort_order,
          start_date, start_date_granularity, target_date, target_date_granularity,
          archived_at, deleted_at, deleted_by, created_at, updated_at
`

type UpdateProjectParams struct {
	Name                  *string
	Summary               *string
	Description           *string
	Icon                  *string
	Color                 *string
	StatusID              *uuid.UUID
	Priority              *int16
	SortOrder             *string
	ClearStart            bool
	StartDate             pgtype.Date
	StartDateGranularity  *string
	ClearTarget           bool
	TargetDate            pgtype.Date
	TargetDateGranularity *string
	ClearLead             bool
	LeadID                *uuid.UUID
	ID                    uuid.UUID
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Name,
		arg.Summary,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.StatusID,
		arg.Priority,
		arg.SortOrder,
		arg.ClearStart,
		arg.StartDate,
		arg.StartDateGranularity,
		arg.ClearTarget,
		arg.TargetDate,
		arg.TargetDateGranularity,
		arg.ClearLead,
		arg.LeadID,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Summary,
		&i.Description,
		&i.Icon,
		&i.Color,
		&i.StatusID,
		&i.Priority,
		&i.LeadID,
		&i.CreatorID,
		&i.SortOrder,
		&i.StartDate,
		&i.StartDateGranularity,
		&i.TargetDate,
		&i.TargetDateGranularity,
		&i.ArchivedAt,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectMilestone = `-- name: UpdateProjectMilestone :one
UPDATE project_milestone
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    sort_order  = COALESCE($3, sort_order),
    target_date = CASE WHEN $4::boolean THEN NULL
                       ELSE COALESCE($5, target_date) END
WHERE id = $6 AND archived_at IS NULL
RETURNING id, workspace_id, project_id, name, description, target_date, sort_order,
          archived_at, created_at, updated_at
`

type UpdateProjectMilestoneParams struct {
	Name        *string
	Description *string
	SortOrder   *string
	ClearTarget bool
	TargetDate  pgtype.Date
	ID          uuid.UUID
}

func (q *Queries) UpdateProjectMilestone(ctx context.Context, arg UpdateProjectMilestoneParams) (ProjectMilestone, error) {
	row := q.db.QueryRow(ctx, updateProjectMilestone,
		arg.Name,
		arg.Description,
		arg.SortOrder,
		arg.ClearTarget,
		arg.TargetDate,
		arg.ID,
	)
	var i ProjectMilestone
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.TargetDate,
		&i.SortOrder,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :one
UPDATE project_status
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    color       = COALESCE($3, color),
    category    = COALESCE($4, category),
    position    = COALESCE($5, position),
    is_default  = COALESCE($6, is_default)
WHERE id = $7
RETURNING id, workspace_id, name, description, color, category, position, is_default,
          archived_at, created_at, updated_at
`

type UpdateProjectStatusParams struct {
	Name        *string
	Description *string
	Color       *string
	Category    *string
	Position    *string
	IsDefault   *bool
	ID          uuid.UUID
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (ProjectStatus, error) {
	row := q.db.QueryRow(ctx, updateProjectStatus,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Category,
		arg.Position,
		arg.IsDefault,
		arg.ID,
	)
	var i ProjectStatus
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Category,
		&i.Position,
		&i.IsDefault,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
