// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_devices.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimNotificationsForPush = `-- name: ClaimNotificationsForPush :many
WITH due AS (
  SELECT p.id FROM notification p
  WHERE p.user_id = $1
    AND p.pushed_at IS NULL
    AND p.read_at IS NULL
    AND p.deleted_at IS NULL
    AND (p.snoozed_until IS NULL OR p.snoozed_until <= now())
  ORDER BY p.created_at
  LIMIT $2
  FOR UPDATE
), claimed AS (
  UPDATE notification n SET pushed_at = now()
  FROM due
  WHERE n.id = due.id AND n.pushed_at IS NULL
  RETURNING n.id, n.type, n.issue_id, n.count, n.created_at, n.pushed_at, n.payload
)
SELECT c.id, c.type, c.issue_id, c.count, c.created_at, c.pushed_at, c.payload,
       coalesce(i.title, '')::text AS issue_title,
       coalesce(
         CASE WHEN i.number IS NOT NULL AND t.key IS NOT NULL
              THEN t.key || '-' || i.number::text
              ELSE NULL END,
         'an issue'
       )::text AS issue_identifier
FROM claimed c
LEFT JOIN issue i ON i.id = c.issue_id
LEFT JOIN team t ON t.id = i.team_id
ORDER BY c.created_at
`

type ClaimNotificationsForPushParams struct {
	UserID   uuid.UUID
	PageSize int32
}

type ClaimNotificationsForPushRow struct {
	ID              uuid.UUID
	Type            string
	IssueID         *uuid.UUID
	Count           int32
	CreatedAt       time.Time
	PushedAt        *time.Time
	Payload         []byte
	IssueTitle      string
	IssueIdentifier string
}

// ClaimNotificationsForPush takes ownership of one person's pending notifications.
// Same shape as ClaimNotificationsForEmail: one statement, at-most-once.
func (q *Queries) ClaimNotificationsForPush(ctx context.Context, arg ClaimNotificationsForPushParams) ([]ClaimNotificationsForPushRow, error) {
	rows, err := q.db.Query(ctx, claimNotificationsForPush, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimNotificationsForPushRow{}
	for rows.Next() {
		var i ClaimNotificationsForPushRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.IssueID,
			&i.Count,
			&i.CreatedAt,
			&i.PushedAt,
			&i.Payload,
			&i.IssueTitle,
			&i.IssueIdentifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePushDeviceByID = `-- name: DeletePushDeviceByID :execrows
DELETE FROM push_device WHERE id = $1
`

func (q *Queries) DeletePushDeviceByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushDeviceByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePushDeviceByToken = `-- name: DeletePushDeviceByToken :execrows
DELETE FROM push_device
WHERE token = $1 AND user_id = $2
`

type DeletePushDeviceByTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) DeletePushDeviceByToken(ctx context.Context, arg DeletePushDeviceByTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushDeviceByToken, arg.Token, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPushDevicesForUser = `-- name: ListPushDevicesForUser :many
SELECT id, user_id, workspace_id, token, platform, app_bundle, environment,
       created_at, last_seen_at
FROM push_device
WHERE user_id = $1
ORDER BY last_seen_at DESC
`

func (q *Queries) ListPushDevicesForUser(ctx context.Context, userID uuid.UUID) ([]PushDevice, error) {
	rows, err := q.db.Query(ctx, listPushDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushDevice{}
	for rows.Next() {
		var i PushDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkspaceID,
			&i.Token,
			&i.Platform,
			&i.AppBundle,
			&i.Environment,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushRecipients = `-- name: ListPushRecipients :many
SELECT u.id AS user_id, u.workspace_id, u.display_name,
       count(n.id)::bigint AS pending
FROM notification n
JOIN "user" u ON u.id = n.user_id
WHERE n.pushed_at IS NULL
  AND n.read_at IS NULL
  AND n.deleted_at IS NULL
  AND (n.snoozed_until IS NULL OR n.snoozed_until <= now())
  AND u.archived_at IS NULL
  AND u.status = 'active'
  AND u.kind = 'human'
  AND EXISTS (SELECT 1 FROM push_device d WHERE d.user_id = u.id)
GROUP BY u.id
ORDER BY u.id
LIMIT $1
`

type ListPushRecipientsRow struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	DisplayName string
	Pending     int64
}

// ListPushRecipients is one row per person who has both a registered device and at least
// one unread, unpushed notification. Grouped in SQL for the same reason the email digest
// list is: the alternative is walking every pending notification to discover who to talk
// to.
func (q *Queries) ListPushRecipients(ctx context.Context, pageSize int32) ([]ListPushRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listPushRecipients, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPushRecipientsRow{}
	for rows.Next() {
		var i ListPushRecipientsRow
		if err := rows.Scan(
			&i.UserID,
			&i.WorkspaceID,
			&i.DisplayName,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releasePushClaim = `-- name: ReleasePushClaim :execrows
UPDATE notification SET pushed_at = NULL
WHERE id = ANY($1::uuid[]) AND pushed_at = $2
`

type ReleasePushClaimParams struct {
	Ids       []uuid.UUID
	ClaimedAt *time.Time
}

// ReleasePushClaim puts rows back when every device refused the send.
func (q *Queries) ReleasePushClaim(ctx context.Context, arg ReleasePushClaimParams) (int64, error) {
	result, err := q.db.Exec(ctx, releasePushClaim, arg.Ids, arg.ClaimedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPushDevice = `-- name: UpsertPushDevice :one

INSERT INTO push_device (id, user_id, workspace_id, token, platform, app_bundle, environment)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
ON CONFLICT (token) DO UPDATE
SET user_id      = EXCLUDED.user_id,
    workspace_id = EXCLUDED.workspace_id,
    platform     = EXCLUDED.platform,
    app_bundle   = EXCLUDED.app_bundle,
    environment  = EXCLUDED.environment,
    last_seen_at = now()
RETURNING id, user_id, workspace_id, token, platform, app_bundle, environment,
          created_at, last_seen_at
`

type UpsertPushDeviceParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Token       string
	Platform    string
	AppBundle   string
	Environment string
}

// Push device tokens. Not on the change stream — see migration 000089.
func (q *Queries) UpsertPushDevice(ctx context.Context, arg UpsertPushDeviceParams) (PushDevice, error) {
	row := q.db.QueryRow(ctx, upsertPushDevice,
		arg.ID,
		arg.UserID,
		arg.WorkspaceID,
		arg.Token,
		arg.Platform,
		arg.AppBundle,
		arg.Environment,
	)
	var i PushDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkspaceID,
		&i.Token,
		&i.Platform,
		&i.AppBundle,
		&i.Environment,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
