// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvite(ctx context.Context, arg AcceptInviteParams) error
	// ---------------------------------------------------------------------------------------
	// Favourites.
	// Re-favouriting something already favourited moves it rather than failing: the only way a
	// user reaches this twice is by dragging an entry they had already added, and an error
	// there would read as the drag not having worked.
	//
	AddFavorite(ctx context.Context, arg AddFavoriteParams) (Favorite, error)
	// team_id and group_id are never supplied by a caller: issue_label_denormalise fills them
	// from the issue and the label, and rejects a label the issue's team cannot use. They are
	// still in every RETURNING list because the sync hub judges visibility from them and the
	// client stores them.
	// AddIssueLabel is idempotent on purpose.
	//
	// ON CONFLICT DO NOTHING would return no row, leaving the caller unable to tell "already
	// applied" from "the write failed". The no-op update returns the existing row instead, and
	// keeps its original id — which matters because that id is the entity's name on the sync
	// stream, and minting a second one for the same application would be a second entity.
	//
	// A conflict on issue_label_one_per_group is NOT swallowed: the issue already carries a
	// different label from this group, and only the caller can decide which survives.
	//
	AddIssueLabel(ctx context.Context, arg AddIssueLabelParams) (IssueLabel, error)
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMembership, error)
	// Advanced only after the batch's rows commit, so a crash re-processes rather than skips.
	// The guard makes the advance monotonic: two workers racing on one workspace can otherwise
	// rewind the watermark, and everything between the two positions is delivered twice.
	//
	AdvanceNotificationCursor(ctx context.Context, arg AdvanceNotificationCursorParams) error
	// AdvanceNotificationEmailCursor records that a digest reached the relay.
	//
	// Written after the send and not before, so the cost of a crash is a pass that finds nothing
	// to do rather than a person who hears nothing for a day. The guard makes it monotonic for
	// the same reason AdvanceNotificationCursor's does: two workers racing must not be able to
	// move a watermark backwards.
	//
	AdvanceNotificationEmailCursor(ctx context.Context, arg AdvanceNotificationEmailCursorParams) error
	// AllocateIssueNumber takes a row lock on the team for the rest of the transaction.
	//
	// Deliberately not a sequence: sequences are non-transactional, so a rolled-back issue
	// creation would burn a number and leave a permanent hole in a value that people read
	// aloud in standup. The lock is held for microseconds and only contends with other
	// creations in the same team.
	//
	AllocateIssueNumber(ctx context.Context, id uuid.UUID) (int64, error)
	AppendChange(ctx context.Context, arg AppendChangeParams) error
	AppendIssueHistory(ctx context.Context, arg AppendIssueHistoryParams) error
	ArchiveIssue(ctx context.Context, id uuid.UUID) error
	// Archived rather than deleted: issue.template_id references this row, and the question
	// that column exists to answer — "is this template still worth having" — needs the
	// template to still be there after somebody retires it.
	//
	ArchiveIssueTemplate(ctx context.Context, id uuid.UUID) (ArchiveIssueTemplateRow, error)
	ArchiveLabel(ctx context.Context, id uuid.UUID) (ArchiveLabelRow, error)
	// Deleting a view archives it. Favourites and view_preference rows point at views by id
	// with no foreign key, so a hard delete would leave a sidebar entry nothing can resolve —
	// and the person who deleted a shared view is rarely the only person using it.
	//
	ArchiveView(ctx context.Context, id uuid.UUID) (ArchiveViewRow, error)
	ArchiveWorkflowState(ctx context.Context, id uuid.UUID) error
	// BulkAddIssueLabels applies the whole (issue, label) cross product of a bulk edit in one
	// statement. The caller supplies the pairs already expanded, each with its own minted id,
	// because ids come from Go everywhere else in the system and a database-side uuid would
	// make the bulk path the one place they do not.
	//
	// DO NOTHING here rather than the no-op update AddIssueLabel uses: the bulk path means
	// "make sure these labels are on these issues", and the rows it returns are exactly the
	// ones it created — which is exactly what belongs on the change stream. Labels already
	// present produce no row and no version.
	//
	// The three arrays are zipped by ordinality rather than passed to one multi-argument
	// unnest, which Postgres accepts but sqlc cannot resolve to a catalogue signature.
	//
	BulkAddIssueLabels(ctx context.Context, arg BulkAddIssueLabelsParams) ([]IssueLabel, error)
	BulkRemoveIssueLabels(ctx context.Context, arg BulkRemoveIssueLabelsParams) ([]IssueLabel, error)
	// BulkUpdateIssues is the bulk-edit path: one property set across a selection, in one
	// statement, under one version block.
	//
	// It never reorders, which is what lets it be a single statement — sort_order is minted
	// per issue from its neighbours, and there is no such thing as one new key for two hundred
	// rows.
	//
	// started_at is COALESCEd against itself rather than overwritten. The single-issue path
	// keeps an existing start by reading the row under a lock first; doing that here would
	// mean two hundred locks and two hundred round trips, so the rule that started_at is never
	// cleared once set is expressed in the statement instead. Cycle time is computed from it.
	//
	BulkUpdateIssues(ctx context.Context, arg BulkUpdateIssuesParams) ([]Issue, error)
	// BumpWorkspaceVersion is the serialisation point of the entire sync engine.
	//
	// The UPDATE takes a row lock held until the transaction commits, so writes to one
	// workspace are totally ordered and the version sequence has no gaps. That is what lets
	// a client say "I am at 148213, send me everything after" and trust the answer without
	// reasoning about transactions still in flight.
	//
	// Cost: a few sub-millisecond lock waits per second on a busy workspace. Benefit: the
	// client has no gap-detection logic at all.
	//
	BumpWorkspaceVersion(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// BumpWorkspaceVersionBy reserves n consecutive versions in one statement and returns
	// the LAST one; the caller assigns (version-n+1 .. version) to its change rows.
	//
	// A bulk action touching 200 issues is one round trip and one lock acquisition instead
	// of 200 of each, while keeping the sequence gapless.
	//
	BumpWorkspaceVersionBy(ctx context.Context, arg BumpWorkspaceVersionByParams) (int64, error)
	// ClaimIdempotencyKey is the first statement of every mutation.
	//
	// ON CONFLICT DO NOTHING means a concurrent duplicate loses the race and returns no row;
	// the caller then reads the winner's stored result. This is what makes a client retry
	// after a dropped response safe: the write happens once, and both callers see the same
	// answer.
	//
	ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error)
	// ClaimNotificationsForEmail takes ownership of one person's pending notifications and
	// returns them with what the message has to say about each.
	//
	// One statement, and that is the point: the rows it describes are the rows it has just
	// claimed. Reading first and marking afterwards would leave a window in which a second
	// worker, or the same worker after a restart, reads the same rows and sends the same digest
	// again — and an email, unlike an inbox row, cannot be folded into the one already there.
	// The inner SELECT ... FOR UPDATE takes the locks in created_at order and the UPDATE
	// re-checks emailed_at IS NULL under them, so a concurrent claim either waits and then
	// matches nothing or is the one that matched: there is no interleaving in which both
	// believe they own a row.
	//
	// The limit is a page and not a nicety. Somebody returning from three weeks off has an inbox
	// of hundreds, and a digest that lists all of them is not read by anybody; the rest stay
	// unclaimed and are the next pass's digest, which is also the honest thing to do with news
	// that old.
	//
	// The joins are LEFT and coalesced. A notification whose issue has been deleted still has to
	// be describable — the row is in somebody's inbox — and coalescing in SQL rather than
	// leaving it to sqlc's nullability inference is deliberate: it does not infer nullability
	// through an outer join, so an uncoalesced i.title would generate as a plain string and fail
	// at scan time, at runtime, on the one row nobody has in their test fixture.
	//
	ClaimNotificationsForEmail(ctx context.Context, arg ClaimNotificationsForEmailParams) ([]ClaimNotificationsForEmailRow, error)
	// ClearDefaultWorkflowState must run immediately before setting a new default, in the
	// same transaction: workflow_state_team_default_key is a partial unique index, so doing
	// it the other way round fails.
	//
	ClearDefaultWorkflowState(ctx context.Context, teamID uuid.UUID) error
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	// CountAdminsInWorkspace guards the "you cannot demote or suspend the last admin"
	// rule. Run inside the same transaction as the demotion, or two concurrent demotions
	// each see one remaining admin and lock everyone out of the workspace.
	//
	CountActiveAdminsInWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// CountBlockingIssues is the "this cannot start yet" badge: how many open issues block
	// this one. A completed or cancelled blocker no longer blocks anything, so the count is
	// taken over issues that are still in flight rather than over relations.
	//
	CountBlockingIssues(ctx context.Context, relatedIssueID uuid.UUID) (int64, error)
	// CountIssuesFromTemplate is the only reason issue.template_id exists.
	//
	CountIssuesFromTemplate(ctx context.Context, templateID *uuid.UUID) (int64, error)
	CountIssuesInWorkflowState(ctx context.Context, stateID uuid.UUID) (int64, error)
	CountIssuesInWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// CountIssuesToPurge is what is left after a batch, so the caller can say whether the trash
	// is empty rather than leaving them to call again and find out.
	//
	CountIssuesToPurge(ctx context.Context, arg CountIssuesToPurgeParams) (int64, error)
	// CountIssuesWithLabel answers "is this label worth keeping" before an archive, and is the
	// number the confirmation dialog shows. Counted through the issue so an archived or
	// deleted issue does not inflate it.
	//
	CountIssuesWithLabel(ctx context.Context, labelID uuid.UUID) (int64, error)
	// CountUnreadNotifications is the badge, read on every page load. It must stay on
	// notification_unread_idx, which is why its predicate is that index's predicate verbatim.
	//
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	// CountWorkspaceSeats is the number the seat limit is checked against.
	//
	// App users are excluded because a bot is not a person: charging for an integration's
	// identity would make every integration a purchasing decision. Suspended and archived
	// users are excluded because suspending somebody is how an admin frees a seat, and a
	// suspension that does not is a suspension that does nothing anybody asked for.
	//
	// Run in the same transaction as the write that would consume the seat, or two concurrent
	// invitations each see one seat free and the workspace ends up one over its limit.
	//
	CountWorkspaceSeats(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	// token_hash appears in exactly one place below: the WHERE clause that authenticates a
	// request. It is in no RETURNING and no SELECT list, so it never reaches a Go struct that
	// could be logged, serialised into a payload, or returned by an API that grows a field
	// later. Nothing above the store has a use for it.
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	// Every list below is the issue table's columns, in the table's own order, minus
	// search_vector. Minus, because the generated vector is roughly the size of the text it
	// indexes and nothing above the store reads it — shipping it would put a copy of every
	// title and description on the wire a second time, once per bootstrap row. In the table's
	// order, because that is the rule that makes a missing column obvious: a new column lands
	// at the end, and so does its addition here.
	CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error)
	// Only one row exists per link. "Blocked by" is a `blocks` row read from the other end,
	// and `related` is stored with the smaller id first, so the reverse listing below is not a
	// second table to keep in step — it is the same rows, read backwards.
	//
	// team_id and related_team_id are filled by issue_relation_denormalise and so are absent
	// from every INSERT, but present in every RETURNING: the sync hub decides visibility from
	// them without re-reading issues that may already be gone.
	CreateIssueRelation(ctx context.Context, arg CreateIssueRelationParams) (IssueRelation, error)
	CreateIssueTemplate(ctx context.Context, arg CreateIssueTemplateParams) (CreateIssueTemplateRow, error)
	CreateLabel(ctx context.Context, arg CreateLabelParams) (CreateLabelRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (AccountSession, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Saved views, the display preferences of the views that have no row, and favourites.
	CreateView(ctx context.Context, arg CreateViewParams) (CreateViewRow, error)
	CreateWorkflowState(ctx context.Context, arg CreateWorkflowStateParams) (WorkflowState, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteIssueRelation(ctx context.Context, id uuid.UUID) (IssueRelation, error)
	// Soft, not a DELETE: the unique index on (user_id, group_key) is what makes the fan-out
	// idempotent, and removing the row would let a replayed version deliver the notification a
	// second time to somebody who had already dismissed it.
	//
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (Notification, error)
	EnsureChangeLogPartition(ctx context.Context, month pgtype.Date) error
	// ---------------------------------------------------------------------------------------
	// Subscriptions.
	// EnsureIssueSubscription is the automatic path: commenting on or being assigned an issue
	// subscribes you to it.
	//
	// It must never touch `unsubscribed`. Resetting it here is the single most commonly
	// rediscovered bug in notification systems: the user unsubscribes, the next comment
	// re-subscribes them, and the button appears to work for about four minutes. The no-op
	// update exists only so the existing row comes back, since the caller needs its id for the
	// change stream.
	//
	EnsureIssueSubscription(ctx context.Context, arg EnsureIssueSubscriptionParams) (IssueSubscription, error)
	// FindGroupableHistoryEntry implements the folding rule: a run of same-kind changes by
	// the same actor within a short window shows as one entry in the feed rather than five.
	// Returning the existing row lets the writer update it instead of appending.
	//
	FindGroupableHistoryEntry(ctx context.Context, arg FindGroupableHistoryEntryParams) (IssueHistory, error)
	// GetAPIKeyByTokenHash is the authentication path.
	//
	// Revocation and expiry are filtered here rather than checked by the caller: a revoked key
	// has to be indistinguishable from a key that never existed, and a check that lives in Go
	// is a check some future second caller forgets. Both cases return no row, and both mean
	// 401 to the client, so nothing is lost by not being able to tell them apart.
	//
	GetAPIKeyByTokenHash(ctx context.Context, tokenHash []byte) (GetAPIKeyByTokenHashRow, error)
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	// GetArchivedLabel reads a label the ordinary path treats as gone.
	//
	// Only the unarchive uses it. loadLabel refuses an archived row on purpose — it is absent
	// from every picker, every listing and every replica — and widening that would put the row
	// back in reach of the reads that are meant not to see it.
	//
	GetArchivedLabel(ctx context.Context, id uuid.UUID) (GetArchivedLabelRow, error)
	GetComment(ctx context.Context, id uuid.UUID) (Comment, error)
	GetDefaultWorkflowStateForTeam(ctx context.Context, teamID uuid.UUID) (WorkflowState, error)
	GetFavoritePositionAfter(ctx context.Context, arg GetFavoritePositionAfterParams) (string, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetInviteByTokenHash(ctx context.Context, tokenHash []byte) (Invite, error)
	GetIssue(ctx context.Context, id uuid.UUID) (Issue, error)
	GetIssueByTeamAndNumber(ctx context.Context, arg GetIssueByTeamAndNumberParams) (Issue, error)
	// GetIssueExists answers "is this id taken", for the client-minted-id path.
	//
	// Deliberately not GetIssue: that filters deleted_at IS NULL, and a soft-deleted issue's
	// id is still occupied — the primary key does not care that the row is hidden. Reusing
	// GetIssue here would let a client claim the id of an issue it had just deleted and hit
	// the unique constraint instead, which surfaces as an internal error rather than as the
	// validation message that explains it.
	//
	// Returns only the id: this is an existence check and reading the row would be handing
	// back an issue the caller may have no right to see.
	//
	GetIssueExists(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// GetIssueForUpdate locks the row for the rest of the transaction. Used by every update
	// path so that read-modify-write on timestamps (started_at, completed_at) cannot
	// interleave with a concurrent status change and lose one of them.
	//
	GetIssueForUpdate(ctx context.Context, id uuid.UUID) (Issue, error)
	GetIssueRelation(ctx context.Context, id uuid.UUID) (IssueRelation, error)
	GetIssueSubscription(ctx context.Context, arg GetIssueSubscriptionParams) (IssueSubscription, error)
	GetIssueTemplate(ctx context.Context, id uuid.UUID) (GetIssueTemplateRow, error)
	GetIssueTemplatePositionAfter(ctx context.Context, arg GetIssueTemplatePositionAfterParams) (string, error)
	GetLabel(ctx context.Context, id uuid.UUID) (GetLabelRow, error)
	GetLabelPositionAfter(ctx context.Context, arg GetLabelPositionAfterParams) (string, error)
	// Neighbour lookups for fractional-index insertion. Positions are only ever compared
	// within one scope, so the predicate matches scope_key's own definition: NULL team means
	// the workspace scope, and IS NOT DISTINCT FROM is what makes that comparable in one
	// expression instead of two query variants.
	//
	GetLabelPositionBefore(ctx context.Context, arg GetLabelPositionBeforeParams) (string, error)
	GetLastFavoritePosition(ctx context.Context, userID uuid.UUID) (string, error)
	GetLastIssueTemplatePosition(ctx context.Context, workspaceID uuid.UUID) (string, error)
	GetLastLabelPosition(ctx context.Context, arg GetLastLabelPositionParams) (string, error)
	GetLastSortOrderForState(ctx context.Context, arg GetLastSortOrderForStateParams) (string, error)
	GetLastSubIssueSortOrder(ctx context.Context, parentID *uuid.UUID) (*string, error)
	GetLastViewPosition(ctx context.Context, workspaceID uuid.UUID) (string, error)
	GetNotification(ctx context.Context, arg GetNotificationParams) (Notification, error)
	// ---------------------------------------------------------------------------------------
	// The engine's watermark.
	// Returns 0 for a workspace that has never been fanned out, which is the correct starting
	// version and saves every caller a not-found branch that would otherwise be the difference
	// between "start at the beginning" and "crash on first run".
	//
	GetNotificationCursor(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (AccountSession, error)
	GetSortOrderAfter(ctx context.Context, arg GetSortOrderAfterParams) (string, error)
	// Neighbour lookups for fractional-index insertion: find the sort_order either side of
	// the target position so a new key can be minted between them.
	//
	GetSortOrderBefore(ctx context.Context, arg GetSortOrderBeforeParams) (string, error)
	// The sibling order is its own sequence per parent, unrelated to the team backlog's, so
	// it gets its own neighbour lookups rather than reusing the ones above.
	//
	GetSubIssueSortOrderAfter(ctx context.Context, arg GetSubIssueSortOrderAfterParams) (*string, error)
	GetTeam(ctx context.Context, id uuid.UUID) (Team, error)
	GetTeamByKey(ctx context.Context, arg GetTeamByKeyParams) (Team, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByAccountAndWorkspace(ctx context.Context, arg GetUserByAccountAndWorkspaceParams) (User, error)
	GetView(ctx context.Context, id uuid.UUID) (GetViewRow, error)
	// Positions are compared across every view in the workspace, which is the order the
	// sidebar renders them in after the visibility filter has been applied.
	//
	GetViewPositionAfter(ctx context.Context, arg GetViewPositionAfterParams) (string, error)
	GetWorkflowState(ctx context.Context, id uuid.UUID) (WorkflowState, error)
	GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceByURLKey(ctx context.Context, urlKey string) (Workspace, error)
	GetWorkspaceVersion(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	InitWorkspaceVersion(ctx context.Context, workspaceID uuid.UUID) error
	IsTeamMember(ctx context.Context, arg IsTeamMemberParams) (bool, error)
	ListAPIKeysForUser(ctx context.Context, userID uuid.UUID) ([]ListAPIKeysForUserRow, error)
	// ListChildIssues feeds the sub-issue list and the progress rollup on the parent. The
	// rollup counts states rather than sums them, so it needs the rows, not an aggregate —
	// and a parent has a handful of children, not a page of them.
	//
	// Archived children are included on purpose: the parent's "3 of 5 done" must not silently
	// become "3 of 4" because somebody archived one, which would make a finished parent look
	// unfinished for no visible reason.
	//
	ListChildIssues(ctx context.Context, parentID *uuid.UUID) ([]Issue, error)
	// ListChildIssuesForParents is ListChildIssues for a whole page of parents at once.
	//
	// One statement rather than one per row, and that is the entire reason it exists: a list
	// view that renders a progress bar on every parent would otherwise issue a query per
	// visible issue, which is the N+1 the API's hydration layer is built to avoid. The
	// per-parent version above stays for the single-issue path, where the array round trip
	// would buy nothing.
	//
	// Ordered by parent first so the caller can group the rows without sorting them again.
	//
	ListChildIssuesForParents(ctx context.Context, arg ListChildIssuesForParentsParams) ([]Issue, error)
	ListCommentsForIssue(ctx context.Context, issueID uuid.UUID) ([]Comment, error)
	// ListDeletedIssues is the "recently deleted" screen. Ordered by deletion time rather than
	// by sort_order, because the only question being asked here is "what did I just lose".
	//
	ListDeletedIssues(ctx context.Context, arg ListDeletedIssuesParams) ([]Issue, error)
	// ---------------------------------------------------------------------------------------
	// Email delivery.
	//
	// Three statements, in the order the job runs them: find who has something waiting, claim
	// it, and record that the message went out. The claim is the interesting one — see
	// migration 000019 for why at-most-once is the right choice here and repeat-rather-than-lose
	// is the right one for the fan-out.
	// ListDigestRecipients is one row per person with unread, unsent notifications waiting.
	//
	// Grouped in SQL rather than in Go because the alternative is reading every pending
	// notification in the install to bucket them by recipient, which is the whole table on the
	// morning after a busy day. What the job needs per person is a count, an address and enough
	// to decide whether they are due; the notifications themselves are read by the claim, one
	// recipient at a time, and only for the ones that turn out to be due.
	//
	// The preferences bag comes back whole and is read in Go, the same way the fan-out reads it:
	// cadence lives in jsonb precisely so that adding a delivery channel is not a migration, and
	// a jsonb predicate for every cadence here would put half of that decision in SQL and half in
	// Go.
	//
	// With one exception, which is about the page rather than about the preference. Somebody who
	// has switched email off keeps their pending notifications forever — they are never claimed,
	// because nothing is ever sent — so without this clause they hold a slot in every page of
	// every pass, and an install where five hundred people have switched email off would never
	// reach the five hundred and first person, who has not. The Go side still checks the cadence
	// and is still the authority on it; this excludes only the one value that means "never", and
	// only when per-notification email has not been asked for instead.
	//
	// Who is excluded, and why. An archived or suspended person no longer works here and their
	// inbox is not their problem; an app user is an integration's identity and has no mailbox at
	// all — the FK to account is NULL for them, so the inner join drops them anyway, and the
	// explicit predicate says so rather than leaving it as a side effect somebody could "fix".
	// A deleted account is somebody who asked to be forgotten, and continuing to mail them is
	// the single most visible way to fail that request.
	//
	// Not excluded: an unverified address. Nothing in the product sets email_verified_at yet —
	// there was no mail to verify with until this feature — so gating on it would make the
	// digest a feature that silently never sends. Every address reached here was typed into an
	// invitation by a workspace admin. Verification is the correct gate to add the day the
	// verification mail itself exists, and this comment is where the next person should look.
	//
	// last_sent_at coalesces to epoch rather than coming back NULL: "never" and "long ago" are
	// the same answer to the only question asked of it, and a pointer here would be a nil check
	// at every call site that means nothing.
	//
	ListDigestRecipients(ctx context.Context, pageSize int32) ([]ListDigestRecipientsRow, error)
	ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]Favorite, error)
	// ListFavoritesForTarget is everybody's favourites pointing at one thing.
	//
	// It exists for the restore, and it is the counterpart to StreamFavoritesForBootstrap: the
	// client drops a favourite whose target it forgets, so a deleted issue takes every star on
	// it off every sidebar, and only a republication puts them back. Without it the replica that
	// watched the undo is missing sidebar rows that a bootstrap taken a second later has.
	//
	// Not scoped to a user, unlike every other statement in this section, because the caller is
	// not the owner — it is republishing on behalf of all of them, and each row goes out under
	// its own owner's scope.
	//
	ListFavoritesForTarget(ctx context.Context, arg ListFavoritesForTargetParams) ([]Favorite, error)
	ListIssueHistory(ctx context.Context, issueID uuid.UUID) ([]IssueHistory, error)
	ListIssueLabels(ctx context.Context, issueID uuid.UUID) ([]IssueLabel, error)
	// ListIssueLabelsForIssues is the same listing for a whole page of issues at once.
	//
	// Label chips are drawn on every row of a filtered list, so this is the one collection on
	// an issue that a list view genuinely asks for — reading it per issue would be the N+1 that
	// hurts most, on the screen people spend their day in. The denormalised team_id carries the
	// visibility rule, exactly as it does for the bootstrap stream, so a caller cannot learn
	// which labels sit on an issue in a team they are not in by naming its id.
	//
	ListIssueLabelsForIssues(ctx context.Context, arg ListIssueLabelsForIssuesParams) ([]IssueLabel, error)
	// ListIssueRelations is the forward direction: what this issue blocks, duplicates, or is
	// related to.
	//
	ListIssueRelations(ctx context.Context, issueID uuid.UUID) ([]IssueRelation, error)
	// The two listings above, for a whole page of issues at once. Both are here for the same
	// reason ListIssueLabelsForIssues is: the API hydrates a list of issues in one pass, and a
	// per-issue query there is a query per visible row.
	//
	// Visibility is "a member of either team", the same rule relationScope writes onto the
	// change row, because a link is a fact about two issues and hiding it from one side would
	// leave the two teams disagreeing about whether it exists.
	//
	ListIssueRelationsForIssues(ctx context.Context, arg ListIssueRelationsForIssuesParams) ([]IssueRelation, error)
	// ListIssueSubscribers is the fan-out's only read: who is watching this issue and still
	// wants to hear. Matches issue_subscription_issue_idx, which is partial on the same
	// predicate.
	//
	ListIssueSubscribers(ctx context.Context, issueID uuid.UUID) ([]IssueSubscription, error)
	// ListIssueSubscriptionsForIssues is the watcher list the issue panel renders, for a whole
	// page of issues at once.
	//
	// Unsubscribed rows are returned, unlike ListIssueSubscribers above, and the difference is
	// the caller: the fan-out wants people who still want to hear, while a reader wants to know
	// whether *they* are watching — and an explicit unsubscribe is a row, not an absence, so
	// dropping it would render the toggle as "not subscribed yet" and re-subscribe them on the
	// next comment.
	//
	// The join is what enforces visibility: issue_subscription carries no team_id of its own,
	// and without it naming an id would reveal who watches an issue in a team the caller is not
	// in.
	//
	ListIssueSubscriptionsForIssues(ctx context.Context, arg ListIssueSubscriptionsForIssuesParams) ([]IssueSubscription, error)
	ListIssueSubscriptionsForUser(ctx context.Context, arg ListIssueSubscriptionsForUserParams) ([]IssueSubscription, error)
	// ListIssueTemplatesForTeam is what the create dialog offers in one team: the workspace's
	// templates, which are offered everywhere, plus that team's own.
	//
	ListIssueTemplatesForTeam(ctx context.Context, arg ListIssueTemplatesForTeamParams) ([]ListIssueTemplatesForTeamRow, error)
	ListIssueTemplatesInWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListIssueTemplatesInWorkspaceRow, error)
	// ListIssuesByIDs reads a scattered set of issues in one round trip, filtered to the teams
	// the caller can see.
	//
	// The team filter is in the statement rather than in Go because this is a read by id: a
	// caller who could name an issue in a team they are not in would otherwise get it back,
	// and "did this uuid come back" is the enumeration oracle every not-found in this package
	// exists to close. Archived issues are included — an issue reached by id is reachable
	// whether or not it is on a board, which is the same rule GetIssue follows.
	//
	ListIssuesByIDs(ctx context.Context, arg ListIssuesByIDsParams) ([]Issue, error)
	ListIssuesForTeam(ctx context.Context, teamID uuid.UUID) ([]Issue, error)
	// ListLabelsForTeam is what the label picker on an issue may offer: the workspace's own
	// labels plus that one team's. A label from another team is not merely hidden here — the
	// issue_label trigger rejects it — so this list and the write rule agree by construction.
	//
	ListLabelsForTeam(ctx context.Context, arg ListLabelsForTeamParams) ([]ListLabelsForTeamRow, error)
	ListLabelsInGroup(ctx context.Context, parentID *uuid.UUID) ([]ListLabelsInGroupRow, error)
	// scope_key sorts workspace labels (the all-zero sentinel) ahead of every team's, so a
	// single pass over this result renders the picker's sections in order.
	ListLabelsInWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListLabelsInWorkspaceRow, error)
	// ListLiveIssueRelationsForIssue is both directions at once, filtered exactly the way the
	// bootstrap stream filters.
	//
	// It exists for the restore, which has to put back on the change stream what the delete's
	// cascade took off every replica. "Exactly the way the bootstrap filters" is the whole
	// requirement: a client that applied the delete and then the restore has to end up holding
	// the same rows as one that bootstrapped afterwards, so this predicate and
	// StreamIssueRelationsForBootstrap's must agree — a relation whose far end is archived or
	// deleted is in neither, or the two replicas disagree about a chip nobody can open.
	//
	ListLiveIssueRelationsForIssue(ctx context.Context, issueID uuid.UUID) ([]IssueRelation, error)
	ListMembershipsInWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]TeamMembership, error)
	// ListMyIssues is everything assigned to the caller across every team they can see.
	//
	// Ordered most-recently-touched first rather than by priority: 0 means "no priority", so
	// the numeric order puts unprioritised work at the top, and the display order is a client
	// concern the replica already implements. This only has to be stable and useful.
	//
	ListMyIssues(ctx context.Context, arg ListMyIssuesParams) ([]Issue, error)
	// ListNotifications is the inbox. The two flags are passed rather than compiled into
	// separate queries so that "unread only" and "everything" cannot drift apart in what they
	// consider deleted or snoozed.
	//
	// A snoozed row reappears on its own once snoozed_until passes, without anything having to
	// sweep the table: the predicate is a comparison against now(), not a stored flag.
	//
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	// ListNotificationsForIssue is every live inbox row about one issue, for every recipient.
	//
	// It exists for the restore, and it is the counterpart to StreamNotificationsForBootstrap
	// above: a delete reaches clients as one change row for the issue and the client's cascade
	// drops the notifications about it, so the restore owes them back or a replica that watched
	// the undo ends up with an emptier inbox than one that bootstrapped a second later.
	//
	// Not scoped to a user, unlike everything else in this file, because the caller is not a
	// recipient — it is republishing on behalf of all of them, and each row goes out under its
	// own owner's scope. That is the same shape ListIssueSubscriptionsForIssues has for the same
	// reason, and it is why this query returns user_id: the emitter needs it to address the
	// change.
	//
	ListNotificationsForIssue(ctx context.Context, arg ListNotificationsForIssueParams) ([]Notification, error)
	ListPendingInvites(ctx context.Context, workspaceID uuid.UUID) ([]Invite, error)
	// ListReverseIssueRelations is the same links read from the far end: what blocks this
	// issue, and what it is a duplicate of. Both listings are needed on the issue panel, which
	// is why issue_relation carries an index on each side.
	//
	ListReverseIssueRelations(ctx context.Context, relatedIssueID uuid.UUID) ([]IssueRelation, error)
	ListReverseIssueRelationsForIssues(ctx context.Context, arg ListReverseIssueRelationsForIssuesParams) ([]IssueRelation, error)
	ListSessionsForAccount(ctx context.Context, accountID uuid.UUID) ([]AccountSession, error)
	// ListTeamIDsForUser resolves a session's visibility set. Called on every socket connect
	// and on every permission change, so it must stay an index-only scan on
	// team_membership_user_idx.
	//
	ListTeamIDsForUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]TeamMembership, error)
	// ListTeamMembershipsForTeams is ListTeamMembers for a page of teams: what Team.members
	// resolves from, for every team in one answer rather than one query per team.
	//
	// team_ids is the reader's own visible set and never the set of teams they asked about.
	// The bootstrap ships exactly the memberships of the teams the reader belongs to, so a
	// listing here that reached further would let the API answer a question the sync stream
	// refuses — who is in a team you are not in — which is the leak the visibility predicate
	// exists to prevent. Enforced in the statement rather than filtered afterwards in Go, like
	// every other batched read, so the rows never leave the database in the first place.
	//
	ListTeamMembershipsForTeams(ctx context.Context, arg ListTeamMembershipsForTeamsParams) ([]TeamMembership, error)
	ListTeamsInWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Team, error)
	ListUsersInWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]User, error)
	ListViewPreferences(ctx context.Context, arg ListViewPreferencesParams) ([]ViewPreference, error)
	// ListViewsForUser is the visibility rule, stated once: a view with no team spans the
	// workspace, a view with a team belongs to that team's sidebar, and a view with an owner
	// is private to them. Writing it here rather than filtering in Go is what keeps the
	// bootstrap snapshot and the live change scope agreeing about who may see a view.
	//
	ListViewsForUser(ctx context.Context, arg ListViewsForUserParams) ([]ListViewsForUserRow, error)
	ListWorkflowStatesForTeam(ctx context.Context, teamID uuid.UUID) ([]WorkflowState, error)
	ListWorkflowStatesInWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]WorkflowState, error)
	ListWorkspacesForAccount(ctx context.Context, accountID *uuid.UUID) ([]ListWorkspacesForAccountRow, error)
	// ListWorkspacesWithPendingNotifications drives the fan-out job, which like the retention
	// sweep has no principal and therefore no workspace of its own to start from.
	//
	// Asking "where is there work" rather than iterating every workspace and discovering the
	// answer per row: this runs on a short interval, and on an install where nobody is typing
	// it has to cost one indexed comparison per workspace and no transaction at all.
	//
	// LEFT JOIN rather than a plain join, because a workspace has no cursor row until its first
	// pass writes one — and a workspace that has never been fanned out is precisely the one with
	// something waiting. Migration 000022 seeds a row for every workspace that existed before
	// the job did, so `coalesce` here covers only the workspaces created since.
	//
	ListWorkspacesWithPendingNotifications(ctx context.Context) ([]uuid.UUID, error)
	// ListWorkspacesWithPurgeableIssues drives the retention sweep, which has no principal and
	// therefore no workspace of its own. Distinct rather than a join over workspace, because
	// the answer wanted is "where is there work to do", and most workspaces have none.
	//
	ListWorkspacesWithPurgeableIssues(ctx context.Context, deletedBefore *time.Time) ([]uuid.UUID, error)
	MarkAccountLogin(ctx context.Context, id uuid.UUID) error
	// One statement for the whole inbox, and one version block for the sync stream. Marking a
	// thousand rows read one at a time would mint a thousand versions and hold the workspace's
	// row lock for the duration of all of them.
	//
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) ([]Notification, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error)
	// NotifySyncHub wakes the sync hubs for a workspace.
	//
	// Deliberately pg_notify rather than a Valkey PUBLISH after commit: NOTIFY is delivered
	// by Postgres *on commit* and not at all on rollback, so a wakeup can never be sent for a
	// change that did not happen, and a committed change can never fail to send one. A
	// publish-after-commit has a window where the process dies between the two and the delta
	// sits unseen until someone reconnects.
	//
	// The payload is only the workspace id and the new version watermark. Hubs read the rows
	// themselves, which keeps the message tiny and means a hub that misses one self-heals on
	// the next.
	//
	// Cost: hubs need a session-mode connection for LISTEN, so they connect straight to
	// Postgres rather than through pgbouncer's transaction pool. See POLARIS_LISTEN_DATABASE_URL.
	//
	NotifySyncHub(ctx context.Context, payload string) error
	// OldestRetainedVersion tells a resuming client whether its position still exists. If
	// the client's version is below this, its deltas have been pruned and it must
	// re-bootstrap rather than silently miss changes.
	//
	OldestRetainedVersion(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	PruneChangeLogBefore(ctx context.Context, before time.Time) (int64, error)
	// PurgeDeletedIssues hard-deletes a bounded batch of trashed issues and is the only
	// statement in the product that removes an issue row.
	//
	// Everything that references the issue goes with it, by foreign key: comment,
	// issue_history, issue_label, issue_relation from both ends, issue_subscription and
	// notification are all ON DELETE CASCADE. Sub-issues are the exception — issue.parent_id is
	// ON DELETE SET NULL — so a child of a purged parent survives, orphaned, which is the same
	// choice the client's own cascade makes for the same reason: a cross-team sub-issue belongs
	// to a team that has lost nothing.
	//
	// One statement rather than a SELECT followed by a DELETE. The window between the two would
	// be a window in which somebody restores an issue from the trash screen and has it hard
	// deleted anyway — the one mistake this table has no way back from. FOR UPDATE inside the
	// CTE is what makes the choice of victims and their removal the same instant.
	//
	// The limit is not a nicety. Every returned id becomes a change_log row inside the caller's
	// transaction, and the version counter is a workspace-wide row lock, so an unbounded purge
	// of a large trash would hold every other writer in the workspace behind it.
	//
	PurgeDeletedIssues(ctx context.Context, arg PurgeDeletedIssuesParams) ([]PurgeDeletedIssuesRow, error)
	// ReadChangesSince is the sync hub's only read path, and the notification engine's. The
	// predicate maps exactly onto change_log_workspace_version_idx, and the LIMIT is what makes
	// the "gap too large -> resync" branch decidable: if the caller gets a full page it asks
	// again, and if the backlog exceeds the session's budget it sends {resync} instead of
	// streaming forever.
	//
	// changed_fields and batch_key are selected even though the hub ignores them, because one
	// read path is the point: a second query shaped for the fan-out would be a second answer to
	// "what happened since V", and the two would drift on the day somebody fixes only one.
	//
	ReadChangesSince(ctx context.Context, arg ReadChangesSinceParams) ([]ChangeLog, error)
	// A mutation that fails must not leave a claimed key behind: the client's retry would
	// then read an empty result and believe the write succeeded.
	//
	ReleaseIdempotencyKey(ctx context.Context, arg ReleaseIdempotencyKeyParams) error
	// ReleaseNotificationEmailClaim puts rows back when the relay refused the message.
	//
	// Claiming before sending is what makes a duplicate impossible; releasing on a refusal is
	// what keeps that from also making an outage permanent. Without it, a relay that is down for
	// an hour would silently swallow every digest due in that hour — the rows would be marked
	// sent and never appear in another one.
	//
	// Guarded on the exact claim timestamp rather than on IS NOT NULL, so it can only ever undo
	// the claim this pass made. A blanket clear would be a statement capable of resurrecting
	// somebody else's delivery, sitting in the error path where it is least likely to be tested.
	//
	ReleaseNotificationEmailClaim(ctx context.Context, arg ReleaseNotificationEmailClaimParams) (int64, error)
	// Returns the removed row because the caller knows the target, not the id the change
	// stream needs.
	//
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) (Favorite, error)
	// Returns the row it removed rather than a count, because the change stream needs the id
	// of the entity that disappeared and the caller only knows the issue and the label.
	//
	RemoveIssueLabel(ctx context.Context, arg RemoveIssueLabelParams) (IssueLabel, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) (int64, error)
	// RemoveUserFromWorkspace takes somebody out of the workspace without taking their work.
	//
	// Both columns move together and neither alone is a removal: archived_at is what drops them
	// from the directory, the assignee picker and the seat count, and status is what
	// ResolvePrincipal reads to refuse their next request. Archiving without suspending leaves a
	// removed person still able to work; suspending without archiving is a suspension, which is
	// a different thing and one an admin can undo.
	//
	// The row stays. Every issue, comment and history entry that names them references it, and
	// those foreign keys are ON DELETE SET NULL — deleting the row would not delete their work,
	// it would silently unattribute years of it.
	//
	RemoveUserFromWorkspace(ctx context.Context, id uuid.UUID) (User, error)
	// RestoreIssue returns the row because a restore puts the issue back on the sync stream,
	// and the payload has to be the issue as it is now — not as the client last saw it before
	// the delete.
	//
	// The window is a parameter rather than a literal: how long a delete stays undoable is a
	// product decision, and burying "30 days" in a query means changing it is a migration.
	//
	// deleted_by is cleared alongside deleted_at. Leaving it set would make a live issue carry
	// the name of somebody who deleted it once and was overruled, which is a fact the activity
	// feed already holds and this column would then contradict on the next delete.
	//
	RestoreIssue(ctx context.Context, arg RestoreIssueParams) (Issue, error)
	// Scoped by user_id as well as id: a key acts as its owner, so only its owner may retire
	// it, and the rule is expressed where it cannot be skipped.
	//
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (RevokeAPIKeyRow, error)
	// Removing somebody from a workspace has to take their keys with them, or the account is
	// gone and the access path is not.
	//
	RevokeAPIKeysForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	RevokeAllSessionsForAccount(ctx context.Context, accountID uuid.UUID) error
	// RevokeInvite is scoped to the workspace, and reports whether anything was revoked.
	//
	// Without the workspace_id an admin could cancel an invitation belonging to a workspace they
	// have nothing to do with, by id alone. Without the RETURNING the caller cannot tell a
	// revoked invitation from one that never existed and would answer success either way. An id
	// from another workspace and an invented id both return no row, so neither confirms that an
	// invitation exists somewhere the caller cannot see.
	//
	// An already-accepted invitation is deliberately not revocable: that person is a member now,
	// and revoking it would suggest their access had been taken away when it has not.
	//
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) (uuid.UUID, error)
	// Re-inviting an address replaces the outstanding invite rather than accumulating rows,
	// which is also what invite_workspace_email_pending_key enforces.
	//
	RevokePendingInvitesForEmail(ctx context.Context, arg RevokePendingInvitesForEmailParams) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	SetAccountPassword(ctx context.Context, arg SetAccountPasswordParams) error
	SetCommentResolution(ctx context.Context, arg SetCommentResolutionParams) (Comment, error)
	SetDefaultWorkflowState(ctx context.Context, id uuid.UUID) error
	// SetIssueSubscription is the button. This is the one place `unsubscribed` may change,
	// because this is the one place the user said so.
	//
	SetIssueSubscription(ctx context.Context, arg SetIssueSubscriptionParams) (IssueSubscription, error)
	SetUserRole(ctx context.Context, arg SetUserRoleParams) (User, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (User, error)
	// Snoozing also marks the row read. A notification you have chosen to defer is one you
	// have seen, and leaving it in the unread count would make the badge argue with the inbox.
	//
	SnoozeNotification(ctx context.Context, arg SnoozeNotificationParams) (Notification, error)
	SoftDeleteComment(ctx context.Context, id uuid.UUID) error
	// SoftDeleteIssue records who as well as when.
	//
	// deleted_by is nullable and a caller may pass nothing, which is what the retention sweep
	// and any future automation want: a deletion nobody instructed has no person to name, and a
	// guessed one would be worse than a blank on the trash screen.
	//
	SoftDeleteIssue(ctx context.Context, arg SoftDeleteIssueParams) error
	SoftDeleteTeam(ctx context.Context, id uuid.UUID) error
	// StreamCommentsForBootstrap ships EVERY live comment on every live issue the caller can
	// see, paged by id.
	//
	// This comment used to say it shipped "the most recent comments only", with full history
	// loaded on demand when an issue is opened, and pointed at the tiering table in
	// docs/05-infrastructure/03-sync-engine.md. That was never implemented — there is no bound
	// here beyond the page size, which is a cursor and not a limit. On a seeded ten-thousand
	// issue workspace comments are the second-largest contributor to the snapshot, so the
	// difference is not academic.
	//
	// Left unbounded rather than quietly capped, because capping it is a product decision with a
	// client-side counterpart: the replica would hold a partial thread, and every screen that
	// reads comments straight out of it would need to know when to go and ask for the rest. The
	// honest state is an accurate comment and a known cost.
	//
	StreamCommentsForBootstrap(ctx context.Context, arg StreamCommentsForBootstrapParams) ([]Comment, error)
	// StreamFavoritesForBootstrap ships the caller's own sidebar, minus the entries pointing at
	// something this same snapshot does not carry.
	//
	// A favourite travels under its owner's user scope, so "yours" is the whole of the
	// visibility rule — but it is not the whole of the predicate, because a favourite is a
	// pointer with no foreign key and the client deletes one whose target it forgets
	// (Store.forget in web/src/store/store.ts, the trailing favoriteTarget walk). Losing a team
	// emits one revoke, for the team; the replica that watched it drops the team's issues, its
	// labels, its views and every favourite pointing at any of them. A snapshot that shipped
	// those favourites back would leave a bootstrapped replica holding sidebar rows that cannot
	// be opened, renamed or removed, and that a replica which stayed online does not have.
	//
	// So each arm below is the membership test of the stream that ships that kind, and the four
	// have to keep agreeing with StreamViewsForBootstrap, StreamLabelsForBootstrap,
	// StreamIssuesForBootstrap and the team filter in StreamBootstrap itself. The team arm is
	// the one that is not obviously the same: the snapshot ships archived teams (they are still
	// yours to look at), so this does too, and only a deleted one is dropped.
	//
	StreamFavoritesForBootstrap(ctx context.Context, arg StreamFavoritesForBootstrapParams) ([]Favorite, error)
	// StreamIssueLabelsForBootstrap joins the issue rather than trusting the denormalised
	// team_id alone: bootstrap must not ship applications belonging to issues the snapshot
	// itself excludes, or the client renders label chips on rows it does not hold.
	//
	StreamIssueLabelsForBootstrap(ctx context.Context, arg StreamIssueLabelsForBootstrapParams) ([]IssueLabel, error)
	// StreamIssueRelationsForBootstrap ships a relation when the caller can see either end,
	// which is the same rule the hub applies to a live change. Both issues are joined so a
	// relation pointing at an archived or deleted issue is left out: the client would render
	// it as a chip it cannot resolve.
	//
	StreamIssueRelationsForBootstrap(ctx context.Context, arg StreamIssueRelationsForBootstrapParams) ([]IssueRelation, error)
	// StreamIssueSubscriptionsForBootstrap feeds the initial snapshot with the caller's own
	// subscriptions and nobody else's.
	//
	// That is the change scope, exactly: a subscription is emitted under the subscriber's user
	// scope and under no team's, because who is watching what is nobody else's business — and a
	// snapshot that shipped the whole watcher list would put one person's subscriptions in every
	// teammate's replica, which is precisely what the emitter refuses to do.
	//
	// The issue is joined for the reason StreamIssueLabelsForBootstrap joins it: the snapshot
	// must not carry rows hanging off issues it leaves out. A subscription is user-scoped, so
	// nothing revokes it when its issue is archived — but the archive reaches clients as a delete
	// for the issue and the client's cascade takes the subscription with it, so a snapshot that
	// kept the row would disagree with every replica that watched it happen.
	//
	// Unsubscribed rows are shipped too. An explicit unsubscribe is a row rather than a missing
	// one, and a replica without it renders the toggle as "not watching yet" and re-subscribes
	// the user on the next comment — the four-minute unsubscribe button, arrived at from the
	// replication side.
	//
	StreamIssueSubscriptionsForBootstrap(ctx context.Context, arg StreamIssueSubscriptionsForBootstrapParams) ([]IssueSubscription, error)
	// StreamIssueTemplatesForBootstrap feeds the initial snapshot. The predicate is
	// requireTemplateScope's, the same shape as the label stream's and for the same reason: a
	// template with no team is offered in every create dialog and reaches every non-guest, and
	// a team's template reaches that team's members. Those are the only two scopes a template
	// change is ever emitted under.
	//
	// Archived templates are excluded — archiving emits a delete — even though issue.template_id
	// may still point at one. That column answers "is this template still worth having" from the
	// server side and is not something a replica renders.
	//
	StreamIssueTemplatesForBootstrap(ctx context.Context, arg StreamIssueTemplatesForBootstrapParams) ([]StreamIssueTemplatesForBootstrapRow, error)
	// StreamIssuesForBootstrap feeds the initial snapshot. Ordered by id (UUIDv7, so
	// effectively creation order) and keyset-paginated: OFFSET would degrade quadratically
	// on a workspace with a hundred thousand issues, which is exactly where it matters.
	//
	StreamIssuesForBootstrap(ctx context.Context, arg StreamIssuesForBootstrapParams) ([]Issue, error)
	// StreamLabelsForBootstrap feeds the initial snapshot, and its predicate is
	// requireLabelScope's written out in SQL: a label with no team is workspace-scoped and
	// reaches every non-guest, and a team's label reaches that team's members. Those are the
	// two scopes every label change is emitted under, so the snapshot and the change stream
	// hand the same principal the same rows.
	//
	// The guest arm is a parameter rather than a predicate on the caller's role, because the
	// authority on it is authz.Visible: the caller passes what that function answered for a
	// workspace scope instead of this statement growing a second opinion about who a guest is.
	//
	// Archived labels are excluded because archiving one emits a delete — every replica has
	// already thrown its copy away, and shipping it here would put back a label the picker,
	// the listings and the applications rule all agree is gone.
	//
	// Keyset-paginated by id like every other stream in the snapshot. A workspace's taxonomy
	// is small today; the reason to page it anyway is that nothing about this statement then
	// has to change on the workspace where it is not.
	//
	StreamLabelsForBootstrap(ctx context.Context, arg StreamLabelsForBootstrapParams) ([]StreamLabelsForBootstrapRow, error)
	// StreamNotificationsForBootstrap ships the caller's inbox into the initial snapshot, and
	// is the one stream in it with a ceiling.
	//
	// Volume is why. Every other table the snapshot walks is bounded by something a person
	// maintains — a taxonomy, a sidebar, a backlog with archived work excluded — and this one is
	// bounded by nothing: the fan-out writes a row per recipient per event, forever, so a
	// two-year-old workspace's first load would carry the whole history of somebody's inbox
	// before they could see a single issue. StreamCommentsForBootstrap states the same choice as
	// a tier — the snapshot carries the recent end and the rest loads on demand — and this is
	// that rule applied to the table that has no other end.
	//
	// The ceiling is the caller's page size and there is no cursor, deliberately: a statement
	// that can never return more than the cap is already bounded, and a second page that cannot
	// exist would be code with no caller. The number itself is domain.BootstrapNotificationLimit,
	// which is where the product decision is written down.
	//
	// Newest first, which no other stream in the snapshot is. The cap has to keep the rows
	// somebody would actually look at, and "the most recent N" is only expressible in the order
	// the inbox renders in. Nothing else depends on the order: a notification is a leaf, so no
	// client applying rows as they arrive can end up holding a dangling reference to one.
	// created_at leads the sort so this stays on notification_inbox_idx; the id breaks ties,
	// because rows written by one fan-out batch share a timestamp and an order that is not total
	// is an order that silently drops rows at the cap boundary.
	//
	// Read and snoozed rows are both included. Marking read and snoozing are upserts on the
	// change stream, so a replica that watched either happen still holds the row — the badge and
	// the inbox are computed from it — and only a dismissal, which is emitted as a delete, takes
	// it away.
	//
	// The join is on the issue and only on the issue, because that is what the client's cascade
	// does: forgetting an issue forgets its notifications, and forgetting a comment does not.
	//
	StreamNotificationsForBootstrap(ctx context.Context, arg StreamNotificationsForBootstrapParams) ([]Notification, error)
	// StreamViewPreferencesForBootstrap feeds the initial snapshot. A preference travels under
	// its owner's user scope and under nothing else, so the whole visibility rule is "yours".
	//
	// Ordered by id rather than by view_key, which is what ListViewPreferences sorts on: the
	// snapshot pages by id and a key order would need an offset to resume.
	//
	StreamViewPreferencesForBootstrap(ctx context.Context, arg StreamViewPreferencesForBootstrapParams) ([]ViewPreference, error)
	// StreamViewsForBootstrap is ListViewsForUser as the snapshot needs it: keyset-paginated,
	// and with the guest arm the listing above leaves to Go stated here instead.
	//
	// The three-way rule is scopeForView's — an owner makes the view personal, a team makes it
	// the team's, and neither makes it the workspace's — so this and the change scope agree
	// about who may see a view.
	//
	// The team clause applies to private views too, and that is not a mistake. A private view
	// anchored to a team travels under its owner's scope, so nothing revokes it when the owner
	// leaves that team — but the client drops a team's views along with the team when the
	// revoke for the team itself arrives (Store.forget in web/src/store/store.ts, the team arm,
	// which walks viewTeam without asking who owns the row). A snapshot that shipped it back
	// would hand a bootstrapped replica a sidebar entry that a replica which watched the
	// removal happen does not have.
	//
	StreamViewsForBootstrap(ctx context.Context, arg StreamViewsForBootstrapParams) ([]StreamViewsForBootstrapRow, error)
	// TouchAPIKeyLastUsed rate-limits itself.
	//
	// The point of last_used_at is answering "is this key still in use before I revoke it",
	// which a minute's resolution settles completely. Writing on every request would turn a
	// read-only API call into a row update, and put the busiest key's row in every checkpoint.
	// The predicate is here rather than in the auth middleware so the limit holds no matter
	// who calls it.
	//
	TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	TouchUserLastSeen(ctx context.Context, id uuid.UUID) error
	UnarchiveIssue(ctx context.Context, id uuid.UUID) error
	// UnarchiveIssueTemplate returns the row for the reason UnarchiveLabel does: the archive
	// reached every client as a delete, so only a payload can put it back.
	//
	UnarchiveIssueTemplate(ctx context.Context, id uuid.UUID) (UnarchiveIssueTemplateRow, error)
	// UnarchiveLabel is the way back, and it returns the row because putting a label back is an
	// upsert on the sync stream — every client dropped it when the archive arrived as a delete,
	// so the payload is the only thing that can restore it.
	//
	// label_scope_name_key is partial on archived_at IS NULL, so archiving a label frees its
	// name and somebody may since have taken it. This statement lets the unique violation
	// happen rather than checking first: the check would be a read the index re-does anyway,
	// and between the two somebody can still take the name.
	//
	UnarchiveLabel(ctx context.Context, id uuid.UUID) (UnarchiveLabelRow, error)
	// UnarchiveWorkflowState returns the row: the archive reached every client as a delete, so
	// putting the status back is an upsert and needs the payload.
	//
	// workflow_state_team_name_key is partial on archived_at IS NULL, so the name this status
	// held was released when it was archived and the team may have reused it. The violation is
	// allowed to happen and translated above, rather than pre-checked — a check would be a read
	// the index performs again a moment later, and it would still be racing.
	//
	UnarchiveWorkflowState(ctx context.Context, id uuid.UUID) (WorkflowState, error)
	UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) (Comment, error)
	UpdateIssue(ctx context.Context, arg UpdateIssueParams) (Issue, error)
	UpdateIssueHistoryTarget(ctx context.Context, arg UpdateIssueHistoryTargetParams) error
	UpdateIssueTemplate(ctx context.Context, arg UpdateIssueTemplateParams) (UpdateIssueTemplateRow, error)
	UpdateLabel(ctx context.Context, arg UpdateLabelParams) (UpdateLabelRow, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	// UpdateTeamEstimates is separate from UpdateTeam because the three settings are one
	// decision: allow_zero and extended only mean anything relative to a scale, and letting a
	// partial update change the scale without them would leave a team offering "16" on a
	// Fibonacci sequence. The mutation takes all three, so this sets all three.
	//
	UpdateTeamEstimates(ctx context.Context, arg UpdateTeamEstimatesParams) (Team, error)
	// Preferences are replaced whole, not merged.
	//
	// The client sends the complete bag it is holding, because a per-key patch would need a
	// delete sentinel to turn a channel off — jsonb_set cannot express "remove this key" and a
	// toggle that can only ever be switched on is not a preference. The bag is small and read
	// by one user at a time, so there is nothing to save by being cleverer.
	//
	UpdateUserNotificationPrefs(ctx context.Context, arg UpdateUserNotificationPrefsParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateView(ctx context.Context, arg UpdateViewParams) (UpdateViewRow, error)
	UpdateWorkflowState(ctx context.Context, arg UpdateWorkflowStateParams) (WorkflowState, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	// The inbox, and the subscriptions that decide who gets one.
	//
	// Every query that touches a notification is scoped by user_id as well as by id. The id
	// alone would be enough to find the row; requiring the recipient too means a mistaken or
	// forged id can only ever act on the caller's own inbox, and the check cannot be forgotten
	// at a call site because it is not at a call site.
	// UpsertNotification is the fan-out's only write.
	//
	// The conflict target is (user_id, group_key), which is what collapses a bulk edit of two
	// hundred issues into one inbox row carrying a count rather than two hundred rows. count
	// is bumped, and read_at is cleared so that new activity re-surfaces a notification the
	// user had already dismissed — that is the whole point of coalescing rather than
	// appending. updated_at is not set here; notification_set_updated_at does it, and setting
	// it twice would only invite the two to disagree.
	//
	// snoozed_until is deliberately left alone. A snooze is the user saying "not now", and
	// more activity within the window is precisely the thing they asked not to be shown.
	//
	// The WHERE on the DO UPDATE is what keeps the engine re-runnable. A worker that crashes
	// mid-batch restarts from the last committed cursor and re-processes versions it already
	// fanned out; without the guard, every replay would inflate count and un-read rows the
	// user had read. With it, a replay updates nothing and returns no row, so a caller that
	// gets pgx.ErrNoRows has learnt "already delivered" and emits no change.
	//
	UpsertNotification(ctx context.Context, arg UpsertNotificationParams) (Notification, error)
	// ---------------------------------------------------------------------------------------
	// Display preferences for the built-in views.
	// The id is only ever used when the row is created; the natural key is (user_id, view_key)
	// and the upsert conflicts on it. A caller therefore mints an id every time and usually
	// throws it away, which is the price of every entity on the sync stream being addressed by
	// a uuid.
	//
	UpsertViewPreference(ctx context.Context, arg UpsertViewPreferenceParams) (ViewPreference, error)
	VerifyAccountEmail(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
