// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sentry.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearSentryConnectionOrganizationSlug = `-- name: ClearSentryConnectionOrganizationSlug :exec
UPDATE sentry_connection
SET organization_slug = NULL
WHERE workspace_id = $1
`

func (q *Queries) ClearSentryConnectionOrganizationSlug(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearSentryConnectionOrganizationSlug, workspaceID)
	return err
}

const createSentryConnection = `-- name: CreateSentryConnection :one

INSERT INTO sentry_connection (
  id, workspace_id, creator_id, enabled, default_team_id,
  organization_slug, webhook_secret, connected_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, workspace_id, creator_id, enabled, default_team_id,
          organization_slug, connected_at, created_at, updated_at
`

type CreateSentryConnectionParams struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CreatorID        uuid.UUID
	Enabled          bool
	DefaultTeamID    uuid.UUID
	OrganizationSlug *string
	WebhookSecret    string
	ConnectedAt      *time.Time
}

type CreateSentryConnectionRow struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CreatorID        uuid.UUID
	Enabled          bool
	DefaultTeamID    uuid.UUID
	OrganizationSlug *string
	ConnectedAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// Replicated columns only. webhook_secret is never selected here.
func (q *Queries) CreateSentryConnection(ctx context.Context, arg CreateSentryConnectionParams) (CreateSentryConnectionRow, error) {
	row := q.db.QueryRow(ctx, createSentryConnection,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatorID,
		arg.Enabled,
		arg.DefaultTeamID,
		arg.OrganizationSlug,
		arg.WebhookSecret,
		arg.ConnectedAt,
	)
	var i CreateSentryConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Enabled,
		&i.DefaultTeamID,
		&i.OrganizationSlug,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSentryConnection = `-- name: DeleteSentryConnection :exec
DELETE FROM sentry_connection WHERE workspace_id = $1
`

func (q *Queries) DeleteSentryConnection(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSentryConnection, workspaceID)
	return err
}

const getSentryConnection = `-- name: GetSentryConnection :one
SELECT id, workspace_id, creator_id, enabled, default_team_id,
       organization_slug, connected_at, created_at, updated_at
FROM sentry_connection
WHERE workspace_id = $1
`

type GetSentryConnectionRow struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CreatorID        uuid.UUID
	Enabled          bool
	DefaultTeamID    uuid.UUID
	OrganizationSlug *string
	ConnectedAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) GetSentryConnection(ctx context.Context, workspaceID uuid.UUID) (GetSentryConnectionRow, error) {
	row := q.db.QueryRow(ctx, getSentryConnection, workspaceID)
	var i GetSentryConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Enabled,
		&i.DefaultTeamID,
		&i.OrganizationSlug,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSentryConnectionSecret = `-- name: GetSentryConnectionSecret :one
SELECT webhook_secret
FROM sentry_connection
WHERE workspace_id = $1
`

func (q *Queries) GetSentryConnectionSecret(ctx context.Context, workspaceID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getSentryConnectionSecret, workspaceID)
	var webhook_secret string
	err := row.Scan(&webhook_secret)
	return webhook_secret, err
}

const setSentryConnectionSecret = `-- name: SetSentryConnectionSecret :exec
UPDATE sentry_connection
SET webhook_secret = $1
WHERE workspace_id = $2
`

type SetSentryConnectionSecretParams struct {
	WebhookSecret string
	WorkspaceID   uuid.UUID
}

func (q *Queries) SetSentryConnectionSecret(ctx context.Context, arg SetSentryConnectionSecretParams) error {
	_, err := q.db.Exec(ctx, setSentryConnectionSecret, arg.WebhookSecret, arg.WorkspaceID)
	return err
}

const streamSentryConnectionsForBootstrap = `-- name: StreamSentryConnectionsForBootstrap :many
SELECT id, workspace_id, creator_id, enabled, default_team_id,
       organization_slug, connected_at, created_at, updated_at
FROM sentry_connection
WHERE workspace_id = $1
  AND id > $2
ORDER BY id
LIMIT $3
`

type StreamSentryConnectionsForBootstrapParams struct {
	WorkspaceID uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

type StreamSentryConnectionsForBootstrapRow struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CreatorID        uuid.UUID
	Enabled          bool
	DefaultTeamID    uuid.UUID
	OrganizationSlug *string
	ConnectedAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) StreamSentryConnectionsForBootstrap(ctx context.Context, arg StreamSentryConnectionsForBootstrapParams) ([]StreamSentryConnectionsForBootstrapRow, error) {
	rows, err := q.db.Query(ctx, streamSentryConnectionsForBootstrap, arg.WorkspaceID, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreamSentryConnectionsForBootstrapRow{}
	for rows.Next() {
		var i StreamSentryConnectionsForBootstrapRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatorID,
			&i.Enabled,
			&i.DefaultTeamID,
			&i.OrganizationSlug,
			&i.ConnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSentryConnection = `-- name: UpdateSentryConnection :one
UPDATE sentry_connection
SET default_team_id = COALESCE($1, default_team_id),
    organization_slug = COALESCE($2, organization_slug),
    enabled = COALESCE($3, enabled),
    connected_at = COALESCE($4, connected_at)
WHERE workspace_id = $5
RETURNING id, workspace_id, creator_id, enabled, default_team_id,
          organization_slug, connected_at, created_at, updated_at
`

type UpdateSentryConnectionParams struct {
	DefaultTeamID    *uuid.UUID
	OrganizationSlug *string
	Enabled          *bool
	ConnectedAt      *time.Time
	WorkspaceID      uuid.UUID
}

type UpdateSentryConnectionRow struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	CreatorID        uuid.UUID
	Enabled          bool
	DefaultTeamID    uuid.UUID
	OrganizationSlug *string
	ConnectedAt      *time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) UpdateSentryConnection(ctx context.Context, arg UpdateSentryConnectionParams) (UpdateSentryConnectionRow, error) {
	row := q.db.QueryRow(ctx, updateSentryConnection,
		arg.DefaultTeamID,
		arg.OrganizationSlug,
		arg.Enabled,
		arg.ConnectedAt,
		arg.WorkspaceID,
	)
	var i UpdateSentryConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Enabled,
		&i.DefaultTeamID,
		&i.OrganizationSlug,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
