// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: slack.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceSlackNotifyCursor = `-- name: AdvanceSlackNotifyCursor :exec
UPDATE slack_connection
SET notify_cursor = $1
WHERE workspace_id = $2
`

type AdvanceSlackNotifyCursorParams struct {
	NotifyCursor int64
	WorkspaceID  uuid.UUID
}

func (q *Queries) AdvanceSlackNotifyCursor(ctx context.Context, arg AdvanceSlackNotifyCursorParams) error {
	_, err := q.db.Exec(ctx, advanceSlackNotifyCursor, arg.NotifyCursor, arg.WorkspaceID)
	return err
}

const clearSlackConnectionChannelName = `-- name: ClearSlackConnectionChannelName :exec
UPDATE slack_connection
SET channel_name = NULL
WHERE workspace_id = $1
`

func (q *Queries) ClearSlackConnectionChannelName(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearSlackConnectionChannelName, workspaceID)
	return err
}

const createSlackConnection = `-- name: CreateSlackConnection :one

INSERT INTO slack_connection (
  id, workspace_id, creator_id, enabled, default_team_id,
  channel_name, notify_issues, notify_comments, webhook_url, notify_cursor, connected_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, workspace_id, creator_id, enabled, default_team_id,
          channel_name, notify_issues, notify_comments, asks_enabled,
          connected_at, created_at, updated_at
`

type CreateSlackConnectionParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	CreatorID      uuid.UUID
	Enabled        bool
	DefaultTeamID  uuid.UUID
	ChannelName    *string
	NotifyIssues   bool
	NotifyComments bool
	WebhookUrl     *string
	NotifyCursor   int64
	ConnectedAt    *time.Time
}

type CreateSlackConnectionRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	CreatorID      uuid.UUID
	Enabled        bool
	DefaultTeamID  uuid.UUID
	ChannelName    *string
	NotifyIssues   bool
	NotifyComments bool
	AsksEnabled    bool
	ConnectedAt    *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Replicated columns only. webhook_url and notify_cursor are never selected here.
func (q *Queries) CreateSlackConnection(ctx context.Context, arg CreateSlackConnectionParams) (CreateSlackConnectionRow, error) {
	row := q.db.QueryRow(ctx, createSlackConnection,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatorID,
		arg.Enabled,
		arg.DefaultTeamID,
		arg.ChannelName,
		arg.NotifyIssues,
		arg.NotifyComments,
		arg.WebhookUrl,
		arg.NotifyCursor,
		arg.ConnectedAt,
	)
	var i CreateSlackConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Enabled,
		&i.DefaultTeamID,
		&i.ChannelName,
		&i.NotifyIssues,
		&i.NotifyComments,
		&i.AsksEnabled,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSlackConnection = `-- name: DeleteSlackConnection :exec
DELETE FROM slack_connection WHERE workspace_id = $1
`

func (q *Queries) DeleteSlackConnection(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSlackConnection, workspaceID)
	return err
}

const getSlackConnection = `-- name: GetSlackConnection :one
SELECT id, workspace_id, creator_id, enabled, default_team_id,
       channel_name, notify_issues, notify_comments, asks_enabled,
       connected_at, created_at, updated_at
FROM slack_connection
WHERE workspace_id = $1
`

type GetSlackConnectionRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	CreatorID      uuid.UUID
	Enabled        bool
	DefaultTeamID  uuid.UUID
	ChannelName    *string
	NotifyIssues   bool
	NotifyComments bool
	AsksEnabled    bool
	ConnectedAt    *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetSlackConnection(ctx context.Context, workspaceID uuid.UUID) (GetSlackConnectionRow, error) {
	row := q.db.QueryRow(ctx, getSlackConnection, workspaceID)
	var i GetSlackConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Enabled,
		&i.DefaultTeamID,
		&i.ChannelName,
		&i.NotifyIssues,
		&i.NotifyComments,
		&i.AsksEnabled,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlackConnectionForNotify = `-- name: GetSlackConnectionForNotify :one
SELECT id, workspace_id, enabled, notify_issues, notify_comments, webhook_url, notify_cursor
FROM slack_connection
WHERE workspace_id = $1
`

type GetSlackConnectionForNotifyRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	Enabled        bool
	NotifyIssues   bool
	NotifyComments bool
	WebhookUrl     *string
	NotifyCursor   int64
}

func (q *Queries) GetSlackConnectionForNotify(ctx context.Context, workspaceID uuid.UUID) (GetSlackConnectionForNotifyRow, error) {
	row := q.db.QueryRow(ctx, getSlackConnectionForNotify, workspaceID)
	var i GetSlackConnectionForNotifyRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Enabled,
		&i.NotifyIssues,
		&i.NotifyComments,
		&i.WebhookUrl,
		&i.NotifyCursor,
	)
	return i, err
}

const getSlackConnectionWebhookURL = `-- name: GetSlackConnectionWebhookURL :one
SELECT webhook_url
FROM slack_connection
WHERE workspace_id = $1
`

func (q *Queries) GetSlackConnectionWebhookURL(ctx context.Context, workspaceID uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getSlackConnectionWebhookURL, workspaceID)
	var webhook_url *string
	err := row.Scan(&webhook_url)
	return webhook_url, err
}

const listWorkspacesWithPendingSlack = `-- name: ListWorkspacesWithPendingSlack :many
SELECT sc.workspace_id
FROM slack_connection sc
JOIN workspace_version wv ON wv.workspace_id = sc.workspace_id
WHERE sc.enabled = true
  AND sc.webhook_url IS NOT NULL
  AND length(btrim(sc.webhook_url)) > 0
  AND wv.version > sc.notify_cursor
`

func (q *Queries) ListWorkspacesWithPendingSlack(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWorkspacesWithPendingSlack)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var workspace_id uuid.UUID
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSlackConnectionWebhookURL = `-- name: SetSlackConnectionWebhookURL :exec
UPDATE slack_connection
SET webhook_url = $1
WHERE workspace_id = $2
`

type SetSlackConnectionWebhookURLParams struct {
	WebhookUrl  *string
	WorkspaceID uuid.UUID
}

func (q *Queries) SetSlackConnectionWebhookURL(ctx context.Context, arg SetSlackConnectionWebhookURLParams) error {
	_, err := q.db.Exec(ctx, setSlackConnectionWebhookURL, arg.WebhookUrl, arg.WorkspaceID)
	return err
}

const streamSlackConnectionsForBootstrap = `-- name: StreamSlackConnectionsForBootstrap :many
SELECT id, workspace_id, creator_id, enabled, default_team_id,
       channel_name, notify_issues, notify_comments, asks_enabled,
       connected_at, created_at, updated_at
FROM slack_connection
WHERE workspace_id = $1
  AND id > $2
ORDER BY id
LIMIT $3
`

type StreamSlackConnectionsForBootstrapParams struct {
	WorkspaceID uuid.UUID
	AfterID     uuid.UUID
	PageSize    int32
}

type StreamSlackConnectionsForBootstrapRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	CreatorID      uuid.UUID
	Enabled        bool
	DefaultTeamID  uuid.UUID
	ChannelName    *string
	NotifyIssues   bool
	NotifyComments bool
	AsksEnabled    bool
	ConnectedAt    *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) StreamSlackConnectionsForBootstrap(ctx context.Context, arg StreamSlackConnectionsForBootstrapParams) ([]StreamSlackConnectionsForBootstrapRow, error) {
	rows, err := q.db.Query(ctx, streamSlackConnectionsForBootstrap, arg.WorkspaceID, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreamSlackConnectionsForBootstrapRow{}
	for rows.Next() {
		var i StreamSlackConnectionsForBootstrapRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatorID,
			&i.Enabled,
			&i.DefaultTeamID,
			&i.ChannelName,
			&i.NotifyIssues,
			&i.NotifyComments,
			&i.AsksEnabled,
			&i.ConnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSlackConnection = `-- name: UpdateSlackConnection :one
UPDATE slack_connection
SET default_team_id = COALESCE($1, default_team_id),
    channel_name = COALESCE($2, channel_name),
    notify_issues = COALESCE($3, notify_issues),
    notify_comments = COALESCE($4, notify_comments),
    asks_enabled = COALESCE($5, asks_enabled),
    enabled = COALESCE($6, enabled),
    connected_at = COALESCE($7, connected_at)
WHERE workspace_id = $8
RETURNING id, workspace_id, creator_id, enabled, default_team_id,
          channel_name, notify_issues, notify_comments, asks_enabled,
          connected_at, created_at, updated_at
`

type UpdateSlackConnectionParams struct {
	DefaultTeamID  *uuid.UUID
	ChannelName    *string
	NotifyIssues   *bool
	NotifyComments *bool
	AsksEnabled    *bool
	Enabled        *bool
	ConnectedAt    *time.Time
	WorkspaceID    uuid.UUID
}

type UpdateSlackConnectionRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	CreatorID      uuid.UUID
	Enabled        bool
	DefaultTeamID  uuid.UUID
	ChannelName    *string
	NotifyIssues   bool
	NotifyComments bool
	AsksEnabled    bool
	ConnectedAt    *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateSlackConnection(ctx context.Context, arg UpdateSlackConnectionParams) (UpdateSlackConnectionRow, error) {
	row := q.db.QueryRow(ctx, updateSlackConnection,
		arg.DefaultTeamID,
		arg.ChannelName,
		arg.NotifyIssues,
		arg.NotifyComments,
		arg.AsksEnabled,
		arg.Enabled,
		arg.ConnectedAt,
		arg.WorkspaceID,
	)
	var i UpdateSlackConnectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Enabled,
		&i.DefaultTeamID,
		&i.ChannelName,
		&i.NotifyIssues,
		&i.NotifyComments,
		&i.AsksEnabled,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
