// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const archiveIssueTemplate = `-- name: ArchiveIssueTemplate :one
UPDATE issue_template SET archived_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, workspace_id, team_id, name, description, title, body, properties, sub_issues,
          position, created_by, archived_at, created_at, updated_at,
          email_intake_enabled, email_intake_token, email_intake_address
`

type ArchiveIssueTemplateRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             *uuid.UUID
	Name               string
	Description        *string
	Title              string
	Body               string
	Properties         json.RawMessage
	SubIssues          json.RawMessage
	Position           string
	CreatedBy          *uuid.UUID
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
}

// Archived rather than deleted: issue.template_id references this row, and the question
// that column exists to answer — "is this template still worth having" — needs the
// template to still be there after somebody retires it.
func (q *Queries) ArchiveIssueTemplate(ctx context.Context, id uuid.UUID) (ArchiveIssueTemplateRow, error) {
	row := q.db.QueryRow(ctx, archiveIssueTemplate, id)
	var i ArchiveIssueTemplateRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Body,
		&i.Properties,
		&i.SubIssues,
		&i.Position,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailIntakeEnabled,
		&i.EmailIntakeToken,
		&i.EmailIntakeAddress,
	)
	return i, err
}

const countIssuesFromTemplate = `-- name: CountIssuesFromTemplate :one
SELECT count(*) FROM issue
WHERE template_id = $1 AND deleted_at IS NULL
`

// CountIssuesFromTemplate is the only reason issue.template_id exists.
func (q *Queries) CountIssuesFromTemplate(ctx context.Context, templateID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuesFromTemplate, templateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssueTemplate = `-- name: CreateIssueTemplate :one
INSERT INTO issue_template (id, workspace_id, team_id, name, description, title, body,
                            properties, sub_issues, position, created_by)
VALUES ($1, $2, $3, $4,
        $5,
        -- title and body are NOT NULL with an empty default: a template that prefills
        -- nothing but a set of properties is a legitimate thing to want.
        COALESCE($6::text, ''), COALESCE($7::text, ''),
        $8, $9, $10, $11)
RETURNING id, workspace_id, team_id, name, description, title, body, properties, sub_issues,
          position, created_by, archived_at, created_at, updated_at,
          email_intake_enabled, email_intake_token, email_intake_address
`

type CreateIssueTemplateParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
	Name        string
	Description *string
	Title       *string
	Body        *string
	Properties  json.RawMessage
	SubIssues   json.RawMessage
	Position    string
	CreatedBy   *uuid.UUID
}

type CreateIssueTemplateRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             *uuid.UUID
	Name               string
	Description        *string
	Title              string
	Body               string
	Properties         json.RawMessage
	SubIssues          json.RawMessage
	Position           string
	CreatedBy          *uuid.UUID
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
}

func (q *Queries) CreateIssueTemplate(ctx context.Context, arg CreateIssueTemplateParams) (CreateIssueTemplateRow, error) {
	row := q.db.QueryRow(ctx, createIssueTemplate,
		arg.ID,
		arg.WorkspaceID,
		arg.TeamID,
		arg.Name,
		arg.Description,
		arg.Title,
		arg.Body,
		arg.Properties,
		arg.SubIssues,
		arg.Position,
		arg.CreatedBy,
	)
	var i CreateIssueTemplateRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Body,
		&i.Properties,
		&i.SubIssues,
		&i.Position,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailIntakeEnabled,
		&i.EmailIntakeToken,
		&i.EmailIntakeAddress,
	)
	return i, err
}

const getIssueTemplate = `-- name: GetIssueTemplate :one
SELECT id, workspace_id, team_id, name, description, title, body, properties, sub_issues,
       position, created_by, archived_at, created_at, updated_at,
          email_intake_enabled, email_intake_token, email_intake_address
FROM issue_template
WHERE id = $1
`

type GetIssueTemplateRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             *uuid.UUID
	Name               string
	Description        *string
	Title              string
	Body               string
	Properties         json.RawMessage
	SubIssues          json.RawMessage
	Position           string
	CreatedBy          *uuid.UUID
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
}

func (q *Queries) GetIssueTemplate(ctx context.Context, id uuid.UUID) (GetIssueTemplateRow, error) {
	row := q.db.QueryRow(ctx, getIssueTemplate, id)
	var i GetIssueTemplateRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Body,
		&i.Properties,
		&i.SubIssues,
		&i.Position,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailIntakeEnabled,
		&i.EmailIntakeToken,
		&i.EmailIntakeAddress,
	)
	return i, err
}

const getIssueTemplateByEmailIntakeToken = `-- name: GetIssueTemplateByEmailIntakeToken :one
SELECT id, workspace_id, team_id, name, description, title, body, properties, sub_issues,
       position, created_by, archived_at, created_at, updated_at,
          email_intake_enabled, email_intake_token, email_intake_address
FROM issue_template
WHERE email_intake_token = $1
  AND email_intake_enabled
  AND archived_at IS NULL
`

type GetIssueTemplateByEmailIntakeTokenRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             *uuid.UUID
	Name               string
	Description        *string
	Title              string
	Body               string
	Properties         json.RawMessage
	SubIssues          json.RawMessage
	Position           string
	CreatedBy          *uuid.UUID
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
}

func (q *Queries) GetIssueTemplateByEmailIntakeToken(ctx context.Context, token *string) (GetIssueTemplateByEmailIntakeTokenRow, error) {
	row := q.db.QueryRow(ctx, getIssueTemplateByEmailIntakeToken, token)
	var i GetIssueTemplateByEmailIntakeTokenRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Body,
		&i.Properties,
		&i.SubIssues,
		&i.Position,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailIntakeEnabled,
		&i.EmailIntakeToken,
		&i.EmailIntakeAddress,
	)
	return i, err
}

const getIssueTemplatePositionAfter = `-- name: GetIssueTemplatePositionAfter :one
SELECT position FROM issue_template
WHERE workspace_id = $1
  AND position > $2
  AND archived_at IS NULL
ORDER BY position
LIMIT 1
`

type GetIssueTemplatePositionAfterParams struct {
	WorkspaceID uuid.UUID
	Position    string
}

func (q *Queries) GetIssueTemplatePositionAfter(ctx context.Context, arg GetIssueTemplatePositionAfterParams) (string, error) {
	row := q.db.QueryRow(ctx, getIssueTemplatePositionAfter, arg.WorkspaceID, arg.Position)
	var position string
	err := row.Scan(&position)
	return position, err
}

const getLastIssueTemplatePosition = `-- name: GetLastIssueTemplatePosition :one
SELECT position FROM issue_template
WHERE workspace_id = $1 AND archived_at IS NULL
ORDER BY position DESC
LIMIT 1
`

func (q *Queries) GetLastIssueTemplatePosition(ctx context.Context, workspaceID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLastIssueTemplatePosition, workspaceID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const listIssueTemplatesForTeam = `-- name: ListIssueTemplatesForTeam :many
SELECT id, workspace_id, team_id, name, description, title, body, properties, sub_issues,
       position, created_by, archived_at, created_at, updated_at,
          email_intake_enabled, email_intake_token, email_intake_address
FROM issue_template
WHERE workspace_id = $1
  AND (team_id IS NULL OR team_id = $2)
  AND archived_at IS NULL
ORDER BY position
`

type ListIssueTemplatesForTeamParams struct {
	WorkspaceID uuid.UUID
	TeamID      *uuid.UUID
}

type ListIssueTemplatesForTeamRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             *uuid.UUID
	Name               string
	Description        *string
	Title              string
	Body               string
	Properties         json.RawMessage
	SubIssues          json.RawMessage
	Position           string
	CreatedBy          *uuid.UUID
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
}

// ListIssueTemplatesForTeam is what the create dialog offers in one team: the workspace's
// templates, which are offered everywhere, plus that team's own.
func (q *Queries) ListIssueTemplatesForTeam(ctx context.Context, arg ListIssueTemplatesForTeamParams) ([]ListIssueTemplatesForTeamRow, error) {
	rows, err := q.db.Query(ctx, listIssueTemplatesForTeam, arg.WorkspaceID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueTemplatesForTeamRow{}
	for rows.Next() {
		var i ListIssueTemplatesForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Title,
			&i.Body,
			&i.Properties,
			&i.SubIssues,
			&i.Position,
			&i.CreatedBy,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailIntakeEnabled,
			&i.EmailIntakeToken,
			&i.EmailIntakeAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueTemplatesInWorkspace = `-- name: ListIssueTemplatesInWorkspace :many
SELECT id, workspace_id, team_id, name, description, title, body, properties, sub_issues,
       position, created_by, archived_at, created_at, updated_at,
          email_intake_enabled, email_intake_token, email_intake_address
FROM issue_template
WHERE workspace_id = $1 AND archived_at IS NULL
ORDER BY position
`

type ListIssueTemplatesInWorkspaceRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             *uuid.UUID
	Name               string
	Description        *string
	Title              string
	Body               string
	Properties         json.RawMessage
	SubIssues          json.RawMessage
	Position           string
	CreatedBy          *uuid.UUID
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
}

func (q *Queries) ListIssueTemplatesInWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListIssueTemplatesInWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listIssueTemplatesInWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueTemplatesInWorkspaceRow{}
	for rows.Next() {
		var i ListIssueTemplatesInWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Title,
			&i.Body,
			&i.Properties,
			&i.SubIssues,
			&i.Position,
			&i.CreatedBy,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailIntakeEnabled,
			&i.EmailIntakeToken,
			&i.EmailIntakeAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const streamIssueTemplatesForBootstrap = `-- name: StreamIssueTemplatesForBootstrap :many
SELECT id, workspace_id, team_id, name, description, title, body, properties, sub_issues,
       position, created_by, archived_at, created_at, updated_at,
          email_intake_enabled, email_intake_token, email_intake_address
FROM issue_template
WHERE workspace_id = $1
  AND archived_at IS NULL
  AND (team_id = ANY($2::uuid[])
       OR (team_id IS NULL AND $3::boolean))
  AND id > $4
ORDER BY id
LIMIT $5
`

type StreamIssueTemplatesForBootstrapParams struct {
	WorkspaceID            uuid.UUID
	TeamIds                []uuid.UUID
	IncludeWorkspaceScoped bool
	AfterID                uuid.UUID
	PageSize               int32
}

type StreamIssueTemplatesForBootstrapRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             *uuid.UUID
	Name               string
	Description        *string
	Title              string
	Body               string
	Properties         json.RawMessage
	SubIssues          json.RawMessage
	Position           string
	CreatedBy          *uuid.UUID
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
}

// StreamIssueTemplatesForBootstrap feeds the initial snapshot. The predicate is
// requireTemplateScope's, the same shape as the label stream's and for the same reason: a
// template with no team is offered in every create dialog and reaches every non-guest, and
// a team's template reaches that team's members. Those are the only two scopes a template
// change is ever emitted under.
//
// Archived templates are excluded — archiving emits a delete — even though issue.template_id
// may still point at one. That column answers "is this template still worth having" from the
// server side and is not something a replica renders.
func (q *Queries) StreamIssueTemplatesForBootstrap(ctx context.Context, arg StreamIssueTemplatesForBootstrapParams) ([]StreamIssueTemplatesForBootstrapRow, error) {
	rows, err := q.db.Query(ctx, streamIssueTemplatesForBootstrap,
		arg.WorkspaceID,
		arg.TeamIds,
		arg.IncludeWorkspaceScoped,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreamIssueTemplatesForBootstrapRow{}
	for rows.Next() {
		var i StreamIssueTemplatesForBootstrapRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TeamID,
			&i.Name,
			&i.Description,
			&i.Title,
			&i.Body,
			&i.Properties,
			&i.SubIssues,
			&i.Position,
			&i.CreatedBy,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailIntakeEnabled,
			&i.EmailIntakeToken,
			&i.EmailIntakeAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveIssueTemplate = `-- name: UnarchiveIssueTemplate :one
UPDATE issue_template SET archived_at = NULL
WHERE id = $1 AND archived_at IS NOT NULL
RETURNING id, workspace_id, team_id, name, description, title, body, properties, sub_issues,
          position, created_by, archived_at, created_at, updated_at,
          email_intake_enabled, email_intake_token, email_intake_address
`

type UnarchiveIssueTemplateRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             *uuid.UUID
	Name               string
	Description        *string
	Title              string
	Body               string
	Properties         json.RawMessage
	SubIssues          json.RawMessage
	Position           string
	CreatedBy          *uuid.UUID
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
}

// UnarchiveIssueTemplate returns the row for the reason UnarchiveLabel does: the archive
// reached every client as a delete, so only a payload can put it back.
func (q *Queries) UnarchiveIssueTemplate(ctx context.Context, id uuid.UUID) (UnarchiveIssueTemplateRow, error) {
	row := q.db.QueryRow(ctx, unarchiveIssueTemplate, id)
	var i UnarchiveIssueTemplateRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Body,
		&i.Properties,
		&i.SubIssues,
		&i.Position,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailIntakeEnabled,
		&i.EmailIntakeToken,
		&i.EmailIntakeAddress,
	)
	return i, err
}

const updateIssueTemplate = `-- name: UpdateIssueTemplate :one
UPDATE issue_template
SET name        = COALESCE($1, name),
    description = COALESCE($2, description),
    title       = COALESCE($3, title),
    body        = COALESCE($4, body),
    properties  = COALESCE($5, properties),
    sub_issues  = COALESCE($6, sub_issues),
    position    = COALESCE($7, position)
WHERE id = $8 AND archived_at IS NULL
RETURNING id, workspace_id, team_id, name, description, title, body, properties, sub_issues,
          position, created_by, archived_at, created_at, updated_at,
          email_intake_enabled, email_intake_token, email_intake_address
`

type UpdateIssueTemplateParams struct {
	Name        *string
	Description *string
	Title       *string
	Body        *string
	Properties  []byte
	SubIssues   []byte
	Position    *string
	ID          uuid.UUID
}

type UpdateIssueTemplateRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             *uuid.UUID
	Name               string
	Description        *string
	Title              string
	Body               string
	Properties         json.RawMessage
	SubIssues          json.RawMessage
	Position           string
	CreatedBy          *uuid.UUID
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
}

func (q *Queries) UpdateIssueTemplate(ctx context.Context, arg UpdateIssueTemplateParams) (UpdateIssueTemplateRow, error) {
	row := q.db.QueryRow(ctx, updateIssueTemplate,
		arg.Name,
		arg.Description,
		arg.Title,
		arg.Body,
		arg.Properties,
		arg.SubIssues,
		arg.Position,
		arg.ID,
	)
	var i UpdateIssueTemplateRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Body,
		&i.Properties,
		&i.SubIssues,
		&i.Position,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailIntakeEnabled,
		&i.EmailIntakeToken,
		&i.EmailIntakeAddress,
	)
	return i, err
}

const updateIssueTemplateEmailIntake = `-- name: UpdateIssueTemplateEmailIntake :one
UPDATE issue_template
SET email_intake_enabled = $1,
    email_intake_token   = COALESCE($2, email_intake_token),
    email_intake_address = COALESCE($3, email_intake_address)
WHERE id = $4 AND archived_at IS NULL
RETURNING id, workspace_id, team_id, name, description, title, body, properties, sub_issues,
          position, created_by, archived_at, created_at, updated_at,
          email_intake_enabled, email_intake_token, email_intake_address
`

type UpdateIssueTemplateEmailIntakeParams struct {
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
	ID                 uuid.UUID
}

type UpdateIssueTemplateEmailIntakeRow struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	TeamID             *uuid.UUID
	Name               string
	Description        *string
	Title              string
	Body               string
	Properties         json.RawMessage
	SubIssues          json.RawMessage
	Position           string
	CreatedBy          *uuid.UUID
	ArchivedAt         *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	EmailIntakeEnabled bool
	EmailIntakeToken   *string
	EmailIntakeAddress *string
}

// UpdateIssueTemplateEmailIntake is the per-template intake address. Team templates
// only: a workspace template has no team to file into.
func (q *Queries) UpdateIssueTemplateEmailIntake(ctx context.Context, arg UpdateIssueTemplateEmailIntakeParams) (UpdateIssueTemplateEmailIntakeRow, error) {
	row := q.db.QueryRow(ctx, updateIssueTemplateEmailIntake,
		arg.EmailIntakeEnabled,
		arg.EmailIntakeToken,
		arg.EmailIntakeAddress,
		arg.ID,
	)
	var i UpdateIssueTemplateEmailIntakeRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TeamID,
		&i.Name,
		&i.Description,
		&i.Title,
		&i.Body,
		&i.Properties,
		&i.SubIssues,
		&i.Position,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailIntakeEnabled,
		&i.EmailIntakeToken,
		&i.EmailIntakeAddress,
	)
	return i, err
}
