// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploaded_files.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUploadedFile = `-- name: CreateUploadedFile :one
INSERT INTO uploaded_file (
  id, workspace_id, creator_id, storage_key, content_type, byte_size,
  original_name, sha256, download_token
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, workspace_id, creator_id, storage_key, content_type, byte_size,
          original_name, sha256, download_token, created_at
`

type CreateUploadedFileParams struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	CreatorID     *uuid.UUID
	StorageKey    string
	ContentType   string
	ByteSize      int64
	OriginalName  string
	Sha256        []byte
	DownloadToken string
}

func (q *Queries) CreateUploadedFile(ctx context.Context, arg CreateUploadedFileParams) (UploadedFile, error) {
	row := q.db.QueryRow(ctx, createUploadedFile,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatorID,
		arg.StorageKey,
		arg.ContentType,
		arg.ByteSize,
		arg.OriginalName,
		arg.Sha256,
		arg.DownloadToken,
	)
	var i UploadedFile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.StorageKey,
		&i.ContentType,
		&i.ByteSize,
		&i.OriginalName,
		&i.Sha256,
		&i.DownloadToken,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadedFile = `-- name: GetUploadedFile :one
SELECT id, workspace_id, creator_id, storage_key, content_type, byte_size,
       original_name, sha256, download_token, created_at
FROM uploaded_file
WHERE id = $1
`

func (q *Queries) GetUploadedFile(ctx context.Context, id uuid.UUID) (UploadedFile, error) {
	row := q.db.QueryRow(ctx, getUploadedFile, id)
	var i UploadedFile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.StorageKey,
		&i.ContentType,
		&i.ByteSize,
		&i.OriginalName,
		&i.Sha256,
		&i.DownloadToken,
		&i.CreatedAt,
	)
	return i, err
}

const getUploadedFileBySHA = `-- name: GetUploadedFileBySHA :one
SELECT id, workspace_id, creator_id, storage_key, content_type, byte_size,
       original_name, sha256, download_token, created_at
FROM uploaded_file
WHERE workspace_id = $1 AND sha256 = $2
`

type GetUploadedFileBySHAParams struct {
	WorkspaceID uuid.UUID
	Sha256      []byte
}

func (q *Queries) GetUploadedFileBySHA(ctx context.Context, arg GetUploadedFileBySHAParams) (UploadedFile, error) {
	row := q.db.QueryRow(ctx, getUploadedFileBySHA, arg.WorkspaceID, arg.Sha256)
	var i UploadedFile
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.StorageKey,
		&i.ContentType,
		&i.ByteSize,
		&i.OriginalName,
		&i.Sha256,
		&i.DownloadToken,
		&i.CreatedAt,
	)
	return i, err
}
