// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const advanceWebhookCursor = `-- name: AdvanceWebhookCursor :exec
INSERT INTO webhook_cursor (workspace_id, version)
VALUES ($1, $2)
ON CONFLICT (workspace_id) DO UPDATE SET version = EXCLUDED.version
WHERE EXCLUDED.version > webhook_cursor.version
`

type AdvanceWebhookCursorParams struct {
	WorkspaceID uuid.UUID
	Version     int64
}

func (q *Queries) AdvanceWebhookCursor(ctx context.Context, arg AdvanceWebhookCursorParams) error {
	_, err := q.db.Exec(ctx, advanceWebhookCursor, arg.WorkspaceID, arg.Version)
	return err
}

const countPendingWebhookDeliveries = `-- name: CountPendingWebhookDeliveries :one
SELECT count(*)::bigint FROM webhook_delivery
WHERE webhook_id = $1 AND delivered_at IS NULL
`

func (q *Queries) CountPendingWebhookDeliveries(ctx context.Context, webhookID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingWebhookDeliveries, webhookID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createWebhook = `-- name: CreateWebhook :one

INSERT INTO webhook (id, workspace_id, creator_id, url, secret, enabled,
                     all_public_teams, team_id, resource_types)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9)
RETURNING id, workspace_id, creator_id, url, enabled, all_public_teams, team_id,
          resource_types, consecutive_failures, disabled_at, created_at, updated_at
`

type CreateWebhookParams struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	CreatorID      uuid.UUID
	Url            string
	Secret         string
	Enabled        bool
	AllPublicTeams bool
	TeamID         *uuid.UUID
	ResourceTypes  []string
}

type CreateWebhookRow struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	CreatorID           uuid.UUID
	Url                 string
	Enabled             bool
	AllPublicTeams      bool
	TeamID              *uuid.UUID
	ResourceTypes       []string
	ConsecutiveFailures int32
	DisabledAt          *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// Webhooks are not replicated. Queries that list or return a webhook to an API caller
// never select `secret`. The delivery path is the one place that needs it, and it is a
// separate query so a future listing that grows a field cannot accidentally start
// returning credentials.
func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (CreateWebhookRow, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatorID,
		arg.Url,
		arg.Secret,
		arg.Enabled,
		arg.AllPublicTeams,
		arg.TeamID,
		arg.ResourceTypes,
	)
	var i CreateWebhookRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Url,
		&i.Enabled,
		&i.AllPublicTeams,
		&i.TeamID,
		&i.ResourceTypes,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :one
DELETE FROM webhook
WHERE id = $1 AND workspace_id = $2
RETURNING id
`

type DeleteWebhookParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteWebhook, arg.ID, arg.WorkspaceID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const disableWebhook = `-- name: DisableWebhook :exec
UPDATE webhook
SET enabled = false, disabled_at = now()
WHERE id = $1 AND enabled = true
`

func (q *Queries) DisableWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableWebhook, id)
	return err
}

const ensureWebhookCursorAtLeast = `-- name: EnsureWebhookCursorAtLeast :exec
INSERT INTO webhook_cursor (workspace_id, version)
VALUES ($1, $2)
ON CONFLICT (workspace_id) DO UPDATE SET version = EXCLUDED.version
WHERE EXCLUDED.version > webhook_cursor.version
`

type EnsureWebhookCursorAtLeastParams struct {
	WorkspaceID uuid.UUID
	Version     int64
}

// Pin the cursor at create time so turning a webhook on does not replay the workspace's
// entire change_log into a stranger's URL.
func (q *Queries) EnsureWebhookCursorAtLeast(ctx context.Context, arg EnsureWebhookCursorAtLeastParams) error {
	_, err := q.db.Exec(ctx, ensureWebhookCursorAtLeast, arg.WorkspaceID, arg.Version)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, workspace_id, creator_id, url, enabled, all_public_teams, team_id,
       resource_types, consecutive_failures, disabled_at, created_at, updated_at
FROM webhook
WHERE id = $1 AND workspace_id = $2
`

type GetWebhookParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

type GetWebhookRow struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	CreatorID           uuid.UUID
	Url                 string
	Enabled             bool
	AllPublicTeams      bool
	TeamID              *uuid.UUID
	ResourceTypes       []string
	ConsecutiveFailures int32
	DisabledAt          *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (GetWebhookRow, error) {
	row := q.db.QueryRow(ctx, getWebhook, arg.ID, arg.WorkspaceID)
	var i GetWebhookRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Url,
		&i.Enabled,
		&i.AllPublicTeams,
		&i.TeamID,
		&i.ResourceTypes,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookCursor = `-- name: GetWebhookCursor :one
SELECT coalesce((SELECT version FROM webhook_cursor WHERE workspace_id = $1), 0)::bigint
`

func (q *Queries) GetWebhookCursor(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getWebhookCursor, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :one
INSERT INTO webhook_delivery (
  id, workspace_id, webhook_id, change_version, entity_type, entity_id, op, payload
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8
)
ON CONFLICT (webhook_id, change_version) DO NOTHING
RETURNING id, workspace_id, webhook_id, change_version, entity_type, entity_id, op,
          payload, attempt, next_attempt_at, last_status, last_error, last_duration_ms,
          last_snippet, delivered_at, created_at
`

type InsertWebhookDeliveryParams struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	WebhookID     uuid.UUID
	ChangeVersion int64
	EntityType    string
	EntityID      uuid.UUID
	Op            string
	Payload       json.RawMessage
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, insertWebhookDelivery,
		arg.ID,
		arg.WorkspaceID,
		arg.WebhookID,
		arg.ChangeVersion,
		arg.EntityType,
		arg.EntityID,
		arg.Op,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.WebhookID,
		&i.ChangeVersion,
		&i.EntityType,
		&i.EntityID,
		&i.Op,
		&i.Payload,
		&i.Attempt,
		&i.NextAttemptAt,
		&i.LastStatus,
		&i.LastError,
		&i.LastDurationMs,
		&i.LastSnippet,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDueWebhookDeliveries = `-- name: ListDueWebhookDeliveries :many
SELECT d.id, d.workspace_id, d.webhook_id, d.change_version, d.entity_type, d.entity_id,
       d.op, d.payload, d.attempt, d.next_attempt_at, d.last_status, d.last_error,
       d.last_duration_ms, d.last_snippet, d.delivered_at, d.created_at,
       w.url, w.secret, w.enabled
FROM webhook_delivery d
JOIN webhook w ON w.id = d.webhook_id
WHERE d.delivered_at IS NULL
  AND d.next_attempt_at <= $1
  AND w.enabled = true
ORDER BY d.next_attempt_at
LIMIT $2
`

type ListDueWebhookDeliveriesParams struct {
	Now      time.Time
	PageSize int32
}

type ListDueWebhookDeliveriesRow struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	WebhookID      uuid.UUID
	ChangeVersion  int64
	EntityType     string
	EntityID       uuid.UUID
	Op             string
	Payload        json.RawMessage
	Attempt        int32
	NextAttemptAt  time.Time
	LastStatus     *int32
	LastError      *string
	LastDurationMs *int32
	LastSnippet    *string
	DeliveredAt    *time.Time
	CreatedAt      time.Time
	Url            string
	Secret         string
	Enabled        bool
}

func (q *Queries) ListDueWebhookDeliveries(ctx context.Context, arg ListDueWebhookDeliveriesParams) ([]ListDueWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listDueWebhookDeliveries, arg.Now, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueWebhookDeliveriesRow{}
	for rows.Next() {
		var i ListDueWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.WebhookID,
			&i.ChangeVersion,
			&i.EntityType,
			&i.EntityID,
			&i.Op,
			&i.Payload,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastDurationMs,
			&i.LastSnippet,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.Url,
			&i.Secret,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledWebhooks = `-- name: ListEnabledWebhooks :many
SELECT id, workspace_id, creator_id, url, enabled, all_public_teams, team_id,
       resource_types, consecutive_failures, disabled_at, created_at, updated_at
FROM webhook
WHERE workspace_id = $1 AND enabled = true
`

type ListEnabledWebhooksRow struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	CreatorID           uuid.UUID
	Url                 string
	Enabled             bool
	AllPublicTeams      bool
	TeamID              *uuid.UUID
	ResourceTypes       []string
	ConsecutiveFailures int32
	DisabledAt          *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) ListEnabledWebhooks(ctx context.Context, workspaceID uuid.UUID) ([]ListEnabledWebhooksRow, error) {
	rows, err := q.db.Query(ctx, listEnabledWebhooks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledWebhooksRow{}
	for rows.Next() {
		var i ListEnabledWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatorID,
			&i.Url,
			&i.Enabled,
			&i.AllPublicTeams,
			&i.TeamID,
			&i.ResourceTypes,
			&i.ConsecutiveFailures,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, workspace_id, webhook_id, change_version, entity_type, entity_id, op,
       payload, attempt, next_attempt_at, last_status, last_error, last_duration_ms,
       last_snippet, delivered_at, created_at
FROM webhook_delivery
WHERE webhook_id = $1 AND workspace_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListWebhookDeliveriesParams struct {
	WebhookID   uuid.UUID
	WorkspaceID uuid.UUID
	PageSize    int32
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.WebhookID, arg.WorkspaceID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.WebhookID,
			&i.ChangeVersion,
			&i.EntityType,
			&i.EntityID,
			&i.Op,
			&i.Payload,
			&i.Attempt,
			&i.NextAttemptAt,
			&i.LastStatus,
			&i.LastError,
			&i.LastDurationMs,
			&i.LastSnippet,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, workspace_id, creator_id, url, enabled, all_public_teams, team_id,
       resource_types, consecutive_failures, disabled_at, created_at, updated_at
FROM webhook
WHERE workspace_id = $1
ORDER BY created_at DESC
`

type ListWebhooksRow struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	CreatorID           uuid.UUID
	Url                 string
	Enabled             bool
	AllPublicTeams      bool
	TeamID              *uuid.UUID
	ResourceTypes       []string
	ConsecutiveFailures int32
	DisabledAt          *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) ListWebhooks(ctx context.Context, workspaceID uuid.UUID) ([]ListWebhooksRow, error) {
	rows, err := q.db.Query(ctx, listWebhooks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhooksRow{}
	for rows.Next() {
		var i ListWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatorID,
			&i.Url,
			&i.Enabled,
			&i.AllPublicTeams,
			&i.TeamID,
			&i.ResourceTypes,
			&i.ConsecutiveFailures,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesWithPendingWebhooks = `-- name: ListWorkspacesWithPendingWebhooks :many
SELECT wv.workspace_id
FROM workspace_version wv
JOIN webhook w ON w.workspace_id = wv.workspace_id AND w.enabled = true
LEFT JOIN webhook_cursor wc ON wc.workspace_id = wv.workspace_id
WHERE wv.version > coalesce(wc.version, 0)
GROUP BY wv.workspace_id
`

func (q *Queries) ListWorkspacesWithPendingWebhooks(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listWorkspacesWithPendingWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var workspace_id uuid.UUID
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryDelivered = `-- name: MarkWebhookDeliveryDelivered :exec
UPDATE webhook_delivery
SET delivered_at = now(),
    attempt = $1,
    last_status = $2,
    last_error = NULL,
    last_duration_ms = $3,
    last_snippet = $4
WHERE id = $5
`

type MarkWebhookDeliveryDeliveredParams struct {
	Attempt        int32
	LastStatus     *int32
	LastDurationMs *int32
	LastSnippet    *string
	ID             uuid.UUID
}

func (q *Queries) MarkWebhookDeliveryDelivered(ctx context.Context, arg MarkWebhookDeliveryDeliveredParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryDelivered,
		arg.Attempt,
		arg.LastStatus,
		arg.LastDurationMs,
		arg.LastSnippet,
		arg.ID,
	)
	return err
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :exec
UPDATE webhook_delivery
SET attempt = $1,
    next_attempt_at = $2,
    last_status = $3,
    last_error = $4,
    last_duration_ms = $5,
    last_snippet = $6
WHERE id = $7
`

type MarkWebhookDeliveryFailedParams struct {
	Attempt        int32
	NextAttemptAt  time.Time
	LastStatus     *int32
	LastError      *string
	LastDurationMs *int32
	LastSnippet    *string
	ID             uuid.UUID
}

func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markWebhookDeliveryFailed,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.LastStatus,
		arg.LastError,
		arg.LastDurationMs,
		arg.LastSnippet,
		arg.ID,
	)
	return err
}

const pruneWebhookDeliveries = `-- name: PruneWebhookDeliveries :execrows
DELETE FROM webhook_delivery WHERE created_at < $1
`

func (q *Queries) PruneWebhookDeliveries(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneWebhookDeliveries, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordWebhookFailure = `-- name: RecordWebhookFailure :one
UPDATE webhook
SET consecutive_failures = consecutive_failures + 1
WHERE id = $1
RETURNING consecutive_failures
`

func (q *Queries) RecordWebhookFailure(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, recordWebhookFailure, id)
	var consecutive_failures int32
	err := row.Scan(&consecutive_failures)
	return consecutive_failures, err
}

const recordWebhookSuccess = `-- name: RecordWebhookSuccess :exec
UPDATE webhook SET consecutive_failures = 0 WHERE id = $1
`

func (q *Queries) RecordWebhookSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordWebhookSuccess, id)
	return err
}

const updateWebhookEnabled = `-- name: UpdateWebhookEnabled :one
UPDATE webhook
SET enabled = $1,
    disabled_at = CASE WHEN $1::boolean THEN NULL ELSE now() END,
    consecutive_failures = CASE WHEN $1::boolean THEN 0 ELSE consecutive_failures END
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, creator_id, url, enabled, all_public_teams, team_id,
          resource_types, consecutive_failures, disabled_at, created_at, updated_at
`

type UpdateWebhookEnabledParams struct {
	Enabled     bool
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

type UpdateWebhookEnabledRow struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	CreatorID           uuid.UUID
	Url                 string
	Enabled             bool
	AllPublicTeams      bool
	TeamID              *uuid.UUID
	ResourceTypes       []string
	ConsecutiveFailures int32
	DisabledAt          *time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) UpdateWebhookEnabled(ctx context.Context, arg UpdateWebhookEnabledParams) (UpdateWebhookEnabledRow, error) {
	row := q.db.QueryRow(ctx, updateWebhookEnabled, arg.Enabled, arg.ID, arg.WorkspaceID)
	var i UpdateWebhookEnabledRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatorID,
		&i.Url,
		&i.Enabled,
		&i.AllPublicTeams,
		&i.TeamID,
		&i.ResourceTypes,
		&i.ConsecutiveFailures,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
